Repository kubernetes/dashboard, pull requests merged in 2018-11, with the labels that each got.

#3316 Remove duplicated code to fix detail pages
  src/app/frontend/common/components/resourcelist/event/template.html
Labels: approved, lgtm, size/XS

#3328 pvc listing and details
  src/app/frontend/common/components/resourcelist/persistentvolumeclaim/template.html
  src/app/frontend/resource/config/persistentvolumeclaim/detail/template.html
  src/app/frontend/typings/backendapi.d.ts
Labels: approved, cncf-cla: yes, lgtm, size/M

#3327 fix: send terminated signal to exec process when socket close
  src/app/backend/handler/terminal.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3317 Enable frontend test in docker
  build/Dockerfile
  build/karma.conf.js
Labels: approved, cncf-cla: yes, lgtm, size/S

#3339 Upgrade build/Dockerfile to use Docker 18.06
  build/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3335 Fix typos: gobal -> global
  src/app/frontend/chrome/state.js
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3344 Migration updates
  src/app/frontend/common/components/card/style.scss
  src/app/frontend/common/components/limits/component.ts
  src/app/frontend/common/components/limits/template.html
  src/app/frontend/common/components/module.ts
  src/app/frontend/common/components/quotas/component.ts
  src/app/frontend/common/components/quotas/template.html
  src/app/frontend/resource/cluster/namespace/detail/template.html
  src/app/frontend/resource/cluster/storageclass/detail/component.ts
  src/app/frontend/resource/cluster/storageclass/detail/template.html
  src/app/frontend_old/common/components/actionbar/actionbarlogs.html
  src/app/frontend_old/common/components/actionbar/actionbarlogs_component.js
  src/app/frontend_old/common/components/actionbar/shell.html
  src/app/frontend_old/common/components/actionbar/shell_component.js
  src/app/frontend_old/common/resource/editresource.scss
  src/app/frontend_old/common/resource/editresource_controller.js
  src/app/frontend_old/common/resource/verber_service.js
  src/app/frontend_old/logs/component.js
  src/app/frontend_old/logs/download/dialog.html
  src/app/frontend_old/logs/download/dialog.js
  src/app/frontend_old/logs/download/dialog.scss
  src/app/frontend_old/logs/download/service.js
  src/app/frontend_old/logs/logs.html
  src/app/frontend_old/logs/logs.scss
  src/app/frontend_old/logs/module.js
  src/app/frontend_old/logs/service.js
  src/app/frontend_old/logs/state.js
  src/app/frontend_old/logs/stateconfig.js
  src/app/frontend_old/resourcelimit/detail.html
  src/app/frontend_old/resourcelimit/detail/detail_component.js
  src/app/frontend_old/resourcelimit/module.js
  src/app/frontend_old/shell/controller.js
  src/app/frontend_old/shell/module.js
  src/app/frontend_old/shell/shell.html
  src/app/frontend_old/shell/shell.scss
  src/app/frontend_old/shell/state.js
  src/app/frontend_old/shell/stateconfig.js
  src/app/frontend_old/shell/termopen_directive.js
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#3347 Bump go version to 1.10.3
  .travis.yml
  build/gocommand.js
  src/app/backend/integration/manager_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3324 Add check-go-format task
  build/check.js
  build/gocommand.js
Labels: approved, cncf-cla: yes, lgtm, size/M
