Repository kubernetes/dashboard, pull requests merged in 2018-08, with the labels that each got.

#3180 API request logging improvements
  src/app/backend/args/builder.go
  src/app/backend/args/holder.go
  src/app/backend/dashboard.go
  src/app/backend/handler/apihandler_test.go
  src/app/backend/handler/filter.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#3099 Include gulp and updated npm in build/Dockerfile for easier development
  build/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3194 update gulp conf/serve to support api-log-level backend arg
  build/conf.js
  build/serve.js
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3198 filter /token/refresh contents from logs
  src/app/backend/handler/filter.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3155 Update Korean translation for pod
  i18n/messages-ko.xtb
Labels: approved, cncf-cla: yes, lgtm, size/L

#3211 Minor tweaks to README
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#3232 Revert "Increase version to 1.10.0"
  build/conf.js
  package-lock.json
  package.json
  src/deploy/alternative/kubernetes-dashboard-arm-head.yaml
  src/deploy/alternative/kubernetes-dashboard-arm.yaml
  src/deploy/alternative/kubernetes-dashboard-head.yaml
  src/deploy/alternative/kubernetes-dashboard.yaml
  src/deploy/recommended/kubernetes-dashboard-arm-head.yaml
  src/deploy/recommended/kubernetes-dashboard-arm.yaml
  src/deploy/recommended/kubernetes-dashboard-head.yaml
  src/deploy/recommended/kubernetes-dashboard.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#3238 Increase version to 1.10.0
  build/conf.js
  package-lock.json
  package.json
  src/deploy/alternative/kubernetes-dashboard-arm-head.yaml
  src/deploy/alternative/kubernetes-dashboard-arm.yaml
  src/deploy/alternative/kubernetes-dashboard-head.yaml
  src/deploy/alternative/kubernetes-dashboard.yaml
  src/deploy/recommended/kubernetes-dashboard-arm-head.yaml
  src/deploy/recommended/kubernetes-dashboard-arm.yaml
  src/deploy/recommended/kubernetes-dashboard-head.yaml
  src/deploy/recommended/kubernetes-dashboard.yaml
Labels: approved, cncf-cla: yes, size/XXL

#3166 Angular migration - pod exec state
  .gitignore
  angular.json
  package-lock.json
  package.json
  src/app/frontend/_theming.scss
  src/app/frontend/common/components/actionbar/detailactions/exec/component.ts
  src/app/frontend/common/components/actionbar/detailactions/exec/template.html
  src/app/frontend/common/components/actionbars/poddetail/template.html
  src/app/frontend/common/components/endpoint/cardlist/template.html
  src/app/frontend/common/components/endpoint/external/template.html
  src/app/frontend/common/components/module.ts
  src/app/frontend/common/params/params.ts
  src/app/frontend/common/services/resource/endpoint.ts
  src/app/frontend/index.module.ts
  src/app/frontend/shared.module.ts
  src/app/frontend/shell/component.ts
  src/app/frontend/shell/module.ts
  src/app/frontend/shell/state.ts
  src/app/frontend/shell/styles.scss
  src/app/frontend/shell/template.html
  src/app/frontend/typings/backendapi.d.ts
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#3233 Don't claim copyright for future years
  build/conf.js
  build/script.js
Labels: approved, cncf-cla: yes, lgtm, size/XS
