Repository kubernetes/dashboard, pull requests merged in 2018-05, with the labels that each got.

#2999 Typo fix: RBACS->RBAC
  src/app/backend/validation/validaterbacstatus.go
  src/app/backend/validation/validaterbacstatus_test.go
  src/app/frontend/chrome/nav/nav.html
Labels: cncf-cla: yes, size/XS

#3015 add some Japanese translation
  i18n/messages-ja.xtb
  src/app/backend/resource/common/pod.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#3024 Update Korean translation
  i18n/messages-ko.xtb
Labels: approved, cncf-cla: yes, lgtm, size/M

#3041 change mouse cursor text to pointer
  src/app/frontend/common/components/graph/graphcard.scss
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3001 Typo fix: targetted->targeted
  i18n/messages-en.xtb
  i18n/messages-ja.xtb
  i18n/messages-ko.xtb
  i18n/messages-zh-tw.xtb
  i18n/messages-zh.xtb
  src/app/frontend/horizontalpodautoscaler/detail/info.html
  src/app/frontend/horizontalpodautoscaler/list/card.html
Labels: approved, cncf-cla: yes, lgtm, size/M

#3031 Some typos fix
  docs/design/thirdpartyresources.md
Labels: cncf-cla: yes, size/XS

#3053 Typo fix: documentaion->documentation
  i18n/messages-en.xtb
  i18n/messages-ja.xtb
  i18n/messages-zh-tw.xtb
  i18n/messages-zh.xtb
Labels: cncf-cla: yes, size/XS

#3062 fix bug: dashboard crashed by terminal with the panic "invalid memory address or nil pointer dereference"
  src/app/backend/handler/terminal.go
Labels: cncf-cla: yes, size/XS

#3057 remove the dead link from OWNERS and OWNERS_ALIASES
  OWNERS
  OWNERS_ALIASES
Labels: cncf-cla: yes, size/XS

#3054 Typo fix: Dashbord -> Dashboard
  i18n/messages-en.xtb
  i18n/messages-ja.xtb
  i18n/messages-zh-tw.xtb
  i18n/messages-zh.xtb
Labels: cncf-cla: yes, size/XS
