Repository kubernetes/dashboard, pull requests merged in 2018-03, with the labels that each got.

#2860 add some Simplified Chinese translation
  i18n/messages-zh.xtb
Labels: approved, cncf-cla: yes, lgtm, size/S

#2881 Update Traditional Chinese translations
  i18n/messages-zh-tw.xtb
Labels: approved, cncf-cla: yes, lgtm, size/L

#2904 Add details of stateful sets
  src/app/frontend/common/components/resourcelist/statefulset/component.ts
  src/app/frontend/common/components/resourcelist/statefulset/template.html
  src/app/frontend/resource/workloads/statefulset/detail/component.ts
  src/app/frontend/resource/workloads/statefulset/detail/state.ts
  src/app/frontend/resource/workloads/statefulset/detail/template.html
  src/app/frontend/resource/workloads/statefulset/module.ts
Labels: approved, cncf-cla: yes, lgtm, size/L

#2908 fix typo.
  src/app/frontend/common/components/breadcrumbs/component.js
Labels: cncf-cla: yes, size/XS

#2907 add history service
  src/app/frontend/common/components/textinput/component.ts
  src/app/frontend/common/services/global/history.ts
  src/app/frontend/common/services/global/module.ts
  src/app/frontend/common/services/global/state.ts
  src/app/frontend/index.router.config.ts
Labels: approved, cncf-cla: yes, size/M

#2927 Add migration note to the README.md
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS
