Repository kubernetes/dashboard, pull requests merged in 2018-07, with the labels that each got.

#2942 Support spec variable in detail pod page.
  src/app/externs/backendapi.js
  src/app/frontend/pod/detail/containerinfo.html
  src/app/frontend/pod/detail/containerinfo_component.js
  src/test/frontend/pod/detail/containerinfo_component_test.js
Labels: cncf-cla: yes, size/M

#3108 fixing issue 3030 pods owning pods on dashboard
  src/app/backend/resource/common/pod.go
  src/app/backend/resource/common/pod_test.go
  src/app/backend/resource/controller/controller.go
  src/app/backend/resource/controller/controller_test.go
  src/app/frontend/pod/detail/creatorinfo.html
Labels: approved, cncf-cla: yes, lgtm, size/L

#3129 Fix HTML encoding in logs (#3125)
  src/app/frontend/logs/component.js
  src/test/frontend/logs/controller_test.js
Labels: approved, cncf-cla: yes, lgtm, size/M

#3121 chore: update github.com/kubernetes-sigs/application
  Gopkg.lock
  vendor/github.com/kubernetes-sigs/application/e2e/testutil/appresource.go
  vendor/github.com/kubernetes-sigs/application/e2e/testutil/customresource.go
  vendor/github.com/kubernetes-sigs/application/e2e/testutil/helpers.go
  vendor/github.com/kubernetes-sigs/application/pkg/apis/app/v1alpha1/application_types.go
  vendor/github.com/kubernetes-sigs/application/pkg/apis/app/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/kubernetes-sigs/application/pkg/apis/app/v1alpha1/zz_generated.kubebuilder.go
  vendor/github.com/kubernetes-sigs/application/pkg/client/clientset/versioned/clientset.go
  vendor/github.com/kubernetes-sigs/application/pkg/client/clientset/versioned/doc.go
  vendor/github.com/kubernetes-sigs/application/pkg/client/clientset/versioned/fake/clientset_generated.go
  vendor/github.com/kubernetes-sigs/application/pkg/client/clientset/versioned/fake/doc.go
  vendor/github.com/kubernetes-sigs/application/pkg/client/clientset/versioned/fake/register.go
  vendor/github.com/kubernetes-sigs/application/pkg/client/clientset/versioned/scheme/doc.go
  vendor/github.com/kubernetes-sigs/application/pkg/client/clientset/versioned/scheme/register.go
  vendor/github.com/kubernetes-sigs/application/pkg/client/clientset/versioned/typed/app/v1alpha1/app_client.go
  vendor/github.com/kubernetes-sigs/application/pkg/client/clientset/versioned/typed/app/v1alpha1/application.go
  vendor/github.com/kubernetes-sigs/application/pkg/client/clientset/versioned/typed/app/v1alpha1/doc.go
  vendor/github.com/kubernetes-sigs/application/pkg/client/clientset/versioned/typed/app/v1alpha1/fake/doc.go
  vendor/github.com/kubernetes-sigs/application/pkg/client/clientset/versioned/typed/app/v1alpha1/fake/fake_app_client.go
  vendor/github.com/kubernetes-sigs/application/pkg/client/clientset/versioned/typed/app/v1alpha1/fake/fake_application.go
  vendor/github.com/kubernetes-sigs/application/pkg/client/clientset/versioned/typed/app/v1alpha1/generated_expansion.go
  vendor/github.com/kubernetes-sigs/application/pkg/client/informers/externalversions/app/interface.go
  vendor/github.com/kubernetes-sigs/application/pkg/client/informers/externalversions/app/v1alpha1/application.go
  vendor/github.com/kubernetes-sigs/application/pkg/client/informers/externalversions/app/v1alpha1/interface.go
  vendor/github.com/kubernetes-sigs/application/pkg/client/informers/externalversions/factory.go
  vendor/github.com/kubernetes-sigs/application/pkg/client/informers/externalversions/generic.go
  vendor/github.com/kubernetes-sigs/application/pkg/client/informers/externalversions/internalinterfaces/factory_interfaces.go
  vendor/github.com/kubernetes-sigs/application/pkg/client/listers/app/v1alpha1/application.go
  vendor/github.com/kubernetes-sigs/application/pkg/client/listers/app/v1alpha1/expansion_generated.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#3098 Fix bug: display job as failed if job backoff limit has reached
  src/app/backend/resource/job/list.go
  src/app/backend/resource/job/list_test.go
  src/app/backend/resource/workload/workload_test.go
  src/app/externs/backendapi.js
  src/app/frontend/job/list/card.html
  src/app/frontend/job/list/card_component.js
  src/test/frontend/job/list/card_component_test.js
Labels: approved, cncf-cla: yes, lgtm, size/M

#3131 Fix incorrect desired number of pods for DaemonSets
  src/app/backend/resource/daemonset/list.go
  src/app/backend/resource/daemonset/list_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#3112 Allow jobs to be manually triggered from cron jobs
  i18n/messages-en.xtb
  i18n/messages-ja.xtb
  i18n/messages-ko.xtb
  i18n/messages-zh-tw.xtb
  i18n/messages-zh.xtb
  src/app/backend/handler/apihandler.go
  src/app/backend/resource/cronjob/jobs.go
  src/app/backend/resource/cronjob/jobs_test.go
  src/app/frontend/common/components/resourcecard/resourcecard_module.js
  src/app/frontend/common/components/resourcecard/resourcecardtriggermenuitem.html
  src/app/frontend/common/components/resourcecard/resourcecardtriggermenuitem_component.js
  src/app/frontend/cronjob/list/card.html
Labels: approved, cncf-cla: yes, lgtm, size/L

#3097 fix(docs): Link Getting started guide to wiki
  docs/design/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3150 Adding Contribution guidelines
  CONTRIBUTING.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#3163 fix: fix circular dependencies issues and enable serve without AoT
  package.json
  src/app/frontend/common/components/module.ts
  src/app/frontend/common/dialogs/module.ts
  src/app/frontend/common/services/global/module.ts
  src/app/frontend/common/services/resource/resource.ts
  src/app/frontend/core.module.ts
  src/app/frontend/index.module.ts
  src/app/frontend/overview/module.ts
  src/app/frontend/polyfills.ts
  src/app/frontend/resource/cluster/clusterrole/module.ts
  src/app/frontend/resource/cluster/module.ts
  src/app/frontend/resource/cluster/namespace/module.ts
  src/app/frontend/resource/cluster/node/module.ts
  src/app/frontend/resource/cluster/persistentvolume/module.ts
  src/app/frontend/resource/cluster/storageclass/module.ts
  src/app/frontend/resource/config/configmap/module.ts
  src/app/frontend/resource/config/module.ts
  src/app/frontend/resource/config/persistentvolumeclaim/module.ts
  src/app/frontend/resource/config/secret/module.ts
  src/app/frontend/resource/discovery/ingress/module.ts
  src/app/frontend/resource/discovery/module.ts
  src/app/frontend/resource/discovery/service/module.ts
  src/app/frontend/resource/workloads/cronjob/module.ts
  src/app/frontend/resource/workloads/daemonset/module.ts
  src/app/frontend/resource/workloads/deployment/module.ts
  src/app/frontend/resource/workloads/job/module.ts
  src/app/frontend/resource/workloads/module.ts
  src/app/frontend/resource/workloads/pod/module.ts
  src/app/frontend/resource/workloads/replicaset/module.ts
  src/app/frontend/resource/workloads/replicationcontroller/module.ts
  src/app/frontend/resource/workloads/statefulset/module.ts
  src/app/frontend/search/module.ts
Labels: approved, cncf-cla: yes, lgtm, size/M

#3153 Angular migration service detail
  src/app/backend/handler/apihandler.go
  src/app/frontend/common/components/endpoint/cardlist/component.ts
  src/app/frontend/common/components/endpoint/cardlist/style.scss
  src/app/frontend/common/components/endpoint/cardlist/template.html
  src/app/frontend/common/components/module.ts
  src/app/frontend/resource/discovery/service/detail/component.ts
  src/app/frontend/resource/discovery/service/detail/state.ts
  src/app/frontend/resource/discovery/service/detail/template.html
  src/app/frontend/typings/backendapi.d.ts
Labels: approved, cncf-cla: yes, lgtm, size/L
