Repository kubernetes/dashboard, pull requests merged in 2018-12, with the labels that each got.

#3393 Typo fixed: "dismissable" -> "dismissible"
  docs/design/navigation-and-scale.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3416 Fix resource editor
  src/app/frontend/common/components/textinput/component.ts
  src/app/frontend/error/handler.ts
  src/app/frontend/polyfills.ts
Labels: approved, cncf-cla: yes, lgtm, size/S

#3399 Update apiVersion
  src/deploy/recommended/kubernetes-dashboard.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3400 Security fix (CVE-2018-18264)
  build/conf.js
  build/karma.conf.js
  build/serve.js
  build/test.js
  src/app/backend/args/builder.go
  src/app/backend/args/holder.go
  src/app/backend/client/manager.go
  src/app/backend/client/manager_test.go
  src/app/backend/dashboard.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#3424 dataselector no necessary continue loop
  src/app/backend/resource/dataselect/dataselect.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3412 Fix typo issue singletone -> singleton
  src/app/backend/args/builder.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3426 Fix typo issue XtbGeneator -> XtbGenerator
  build/postinstall.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3427 Fix typo issue passses -> passes
  build/i18n.js
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3414 Prepare for 1.10.1 release
  build/conf.js
  package.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3338 fix: add lock to terminalSessions to avoid panic when concurrent access
  src/app/backend/handler/apihandler.go
  src/app/backend/handler/terminal.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#3432 Bump version to 1.10.1
  src/deploy/recommended/kubernetes-dashboard-arm.yaml
  src/deploy/recommended/kubernetes-dashboard.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3436 Fix HPA pagination
  src/app/backend/handler/apihandler.go
  src/app/backend/resource/horizontalpodautoscaler/common.go
  src/app/backend/resource/horizontalpodautoscaler/list.go
  src/app/backend/resource/horizontalpodautoscaler/list_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#3433 `servicesAndDiscovery` -> `Discovery`
  src/app/backend/resource/discovery/discovery.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3437 fix: send terminated signal to process when socket error
  src/app/backend/handler/terminal.go
Labels: cncf-cla: yes, lgtm, size/XS

#3434 Fix FilterPodsForJob in backend
  src/app/backend/resource/common/pod.go
  src/app/backend/resource/job/list_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#3360 delete image reference validating info
  src/app/backend/validation/validateimagereference.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3443 Update README.md
  README.md
Labels: approved, cncf-cla: yes, size/XS

#3444 Reverted mixup of ARM and AMD64 version of dashboard deployment manifest
  aio/deploy/recommended/kubernetes-dashboard-arm.yaml
  aio/deploy/recommended/kubernetes-dashboard.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3453 Add @jeefy as a ui lead
  OWNERS_ALIASES
  ROLES.md
  SECURITY_CONTACTS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3456 Fix travis
  src/app/backend/resource/discovery/discovery.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3458 Update README.md
  README.md
  docs/dashboard-ui.png
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3459 Update style formatting script
  package.json
  src/app/frontend_old/components/graph/graphcard.scss
Labels: approved, cncf-cla: yes, lgtm, size/S

#3468 Move template files docs/ to root
  .github/CODE_OF_CONDUCT.md
  .github/CONTRIBUTING.md
  CONTRIBUTING.md
  README.md
  code-of-conduct.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#3462 fix(terminal): syncmutex are used as value
  src/app/backend/handler/terminal.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3466 Update README.md
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS
