Repository kubernetes/dashboard, pull requests merged in 2018-04, with the labels that each got.

#2948 Fix grammar mistake
  src/app/frontend/index_route.js
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2934 fix: deployment to rs reference
  src/app/backend/resource/common/pod.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#2858 hide nodePort in internal endpoints when nodePort is not set
  src/app/frontend/common/components/endpoint/internalendpoint.html
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2975 fix: namespace param should be checked in onEnter hook
  .babelrc
  src/app/externs/uirouter.js
  src/app/frontend/common/namespace/module.js
  src/test/frontend/common/namespace/component_test.js
Labels: approved, cncf-cla: yes, lgtm, size/M

#2979 Typo fix in troubleshooting.md: it's arguments->its arguments
  docs/design/troubleshooting.md
Labels: cncf-cla: yes, size/XS

#2950 Initial Korean localization
  i18n/locale_conf.json
  i18n/messages-ko.xtb
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#2990 Typo fix: there should a->there should be a
  docs/design/access-control.md
Labels: cncf-cla: yes, size/XS
