Repository kubernetes/dashboard, pull requests merged in 2018-06, with the labels that each got.

#3076 Modify for Japanese Translation
  i18n/messages-ja.xtb
Labels: approved, cncf-cla: yes, lgtm, size/L

#3077 Allow disabling the skip button
  src/app/backend/args/builder.go
  src/app/backend/args/holder.go
  src/app/backend/auth/api/types.go
  src/app/backend/auth/handler.go
  src/app/backend/auth/manager.go
  src/app/backend/auth/manager_test.go
  src/app/backend/dashboard.go
  src/app/backend/handler/apihandler_test.go
  src/app/externs/backendapi.js
  src/app/frontend/login/component.js
  src/app/frontend/login/login.html
  src/app/frontend/login/module.js
  src/app/frontend/login/stateconfig.js
  src/test/frontend/login/component_test.js
Labels: approved, cncf-cla: yes, lgtm, size/L

#3074 Typo fix in returned messages: containe->contain/retrun->return
  src/test/frontend/common/docker/dockerimagereference_test.js
Labels: approved, cncf-cla: yes, lgtm, size/S

#3067 Update Korean translation
  i18n/messages-ko.xtb
Labels: approved, cncf-cla: yes, lgtm, size/S

#3095 Typo fix: containe -> contain
  src/test/frontend/common/docker/dockerimagereference_test.js
Labels: cncf-cla: yes, size/XS

#3069 Typo dropdown
  i18n/messages-en.xtb
  i18n/messages-ja.xtb
  i18n/messages-ko.xtb
  i18n/messages-zh-tw.xtb
  i18n/messages-zh.xtb
Labels: approved, cncf-cla: yes, lgtm, size/M

#3106 fix: fix an issue which causes hang after skip login page
  i18n/messages-en.xtb
  i18n/messages-ja.xtb
  i18n/messages-zh-tw.xtb
  i18n/messages-zh.xtb
  src/app/frontend/chrome/component.js
  src/app/frontend/common/namespace/module.js
Labels: approved, cncf-cla: yes, lgtm, size/M

#3103 Support for viewing completed/inactive CronJob jobs
  src/app/backend/resource/cronjob/detail.go
  src/app/backend/resource/cronjob/detail_test.go
  src/app/backend/resource/cronjob/jobs.go
  src/app/frontend/cronjob/detail/detail.html
Labels: approved, cncf-cla: yes, lgtm, size/M
