Repository kubernetes/dashboard, pull requests merged in 2018-02, with the labels that each got.

#2838 Update to v1.8.3
  build/conf.js
  package.json
  src/deploy/alternative/kubernetes-dashboard-arm.yaml
  src/deploy/alternative/kubernetes-dashboard.yaml
  src/deploy/recommended/kubernetes-dashboard-arm.yaml
  src/deploy/recommended/kubernetes-dashboard.yaml
  src/test/integration/stories/deploy_from_valid_file_test.js
Labels: approved, cncf-cla: yes, lgtm, size/S

#2821 Update .eslintrc typo overriden-->overridden
  .eslintrc
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2832 Fix typo in i18n.js
  build/i18n.js
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2831 some typo
  build/build.js
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2830 Fix typos
  src/app/frontend/common/filters/relativetime.js
  src/app/frontend/logs/component.js
  src/test/frontend/deploy/deployfromsettings/createnamespace/dialog_test.js
  src/test/frontend/deploy/deployfromsettings/createsecret/dialog_test.js
  src/test/frontend/service/list/card_component_test.js
Labels: approved, cncf-cla: yes, lgtm, size/S

#2829 fix typo
  src/app/frontend/common/components/conditions/conditionslist.html
Labels: cncf-cla: yes, size/XS

#2828 Update component.js
  src/app/frontend/common/components/graph/component.js
Labels: cncf-cla: yes, size/XS

#2823 Update i18n.md fix typo throught --> through
  docs/design/i18n.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#2818 fix a typo in dashboard.go
  src/app/backend/dashboard.go
Labels: cncf-cla: yes, size/XS

#2804 Add missing Traditional Chinese translations
  i18n/messages-zh-tw.xtb
Labels: cncf-cla: yes, size/L
