Repository kubernetes/dashboard, pull requests merged in 2018-10, with the labels that each got.

#3272 Fix typos issues in backend files
  src/app/backend/auth/api/types.go
  src/app/backend/resource/ingress/detail.go
  src/app/backend/resource/pod/common_test.go
  src/app/backend/resource/secret/detail.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3141 Issue 2330
  build/serve.js
  src/app/frontend/common/components/middleellipsis/component.js
  src/app/frontend/common/components/middleellipsis/middleellipsis.html
  src/app/frontend/common/components/middleellipsis/middleellipsis.scss
  src/test/frontend/common/components/middleellipsis/middleellipsis_controller_test.js
Labels: approved, cncf-cla: yes, lgtm, size/M

#3288 Remove merge leftovers and format files
  .travis.yml
  aio/scripts/lint-backend.sh
  src/app/backend/integration/manager_test.go
  src/app/backend/resource/deployment/detail.go
  src/app/backend/resource/deployment/detail_test.go
  src/app/backend/resource/horizontalpodautoscaler/list_test.go
  src/app/backend/resource/pod/detail.go
  src/app/backend/resource/pod/detail_test.go
  src/app/backend/resource/pod/fieldpath_test.go
  src/app/backend/resource/replicaset/detail.go
  src/app/backend/resource/replicaset/detail_test.go
  src/app/frontend/common/components/commaseparatedlist/component.ts~9b105259e40bac26b1ec1002edcf6eff4b634f72
  src/app/frontend/common/components/commaseparatedlist/component.ts~9b105259e40bac26b1ec1002edcf6eff4b634f72_0
  src/app/frontend/common/components/commaseparatedlist/component.ts~HEAD
  src/app/frontend/common/components/commaseparatedlist/component.ts~HEAD_0
  src/app/frontend/common/components/namespaceselector/component.ts
  src/app/frontend/common/components/resourcecard/resourcecardtriggermenuitem.html
  src/app/frontend/common/components/resourcecard/resourcecardtriggermenuitem_component.js
  src/app/frontend/cronjob/detail/detail.html
  src/app/frontend/cronjob/list/card.html
  src/app/frontend/job/list/card_component.js
  src/app/frontend/pod/detail/containerinfo.html
  src/app/frontend/pod/detail/containerinfo_component.js
  src/app/frontend/pod/detail/creatorinfo.html
Labels: approved, cncf-cla: yes, lgtm, size/XL

#3297 Update README.md
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3289 Fix for unauthenticated secret access
  src/app/backend/auth/api/common.go
  src/app/backend/auth/api/types.go
Labels: approved, cncf-cla: yes, size/S

#3308 fix typo in comments
  docs/testing/container-status/pending.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS
