Repository kubernetes/dashboard, pull requests merged in 2019-04, with the labels that each got.

#3707 Greenkeeper/semver 6.0.0
  package-lock.json
  package.json
Labels: approved, cncf-cla: no, size/M

#3678 Enable `golangci-lint` in `lint-staged`
  package.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3720 Bump `kind` version to 0.2.1
  aio/scripts/conf.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3721 Use settingsApi.SettingsManager in CreateHTTPAPIHandler
  src/app/backend/dashboard.go
  src/app/backend/handler/apihandler.go
  src/app/backend/handler/apihandler_test.go
  src/app/backend/settings/api/types.go
  src/app/backend/settings/handler.go
  src/app/backend/settings/handler_test.go
  src/app/backend/settings/manager.go
  src/app/backend/settings/manager_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#3607 completed some todos
  src/app/frontend/common/components/uploadfile/component.ts
Labels: approved, cncf-cla: yes, lgtm, size/S

#3748 Greenkeeper/xterm 3.12.2
  package-lock.json
  package.json
Labels: approved, cncf-cla: no, size/S

#3745 Fixed `alternative` deploy files
  aio/deploy/alternative/kubernetes-dashboard-arm-head.yaml
  aio/deploy/alternative/kubernetes-dashboard-arm.yaml
  aio/deploy/alternative/kubernetes-dashboard-head.yaml
  aio/deploy/alternative/kubernetes-dashboard.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#3760 Fix e2e tests
  angular.json
  package.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3758 Improve error message when loading serving certs fails
  src/app/backend/dashboard.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#3774 Greenkeeper/karma jasmine html reporter 1.4.2
  package-lock.json
  package.json
Labels: approved, cncf-cla: no, do-not-merge/invalid-commit-message, size/XS

#3775 Greenkeeper/husky 2.1.0
  package-lock.json
  package.json
Labels: approved, cncf-cla: no, do-not-merge/invalid-commit-message, size/L

#3711 Improve container for development
  .gitignore
  aio/develop/Dockerfile
  aio/develop/npm-command.sh
  aio/develop/run-npm-on-container.sh
  aio/protractor.conf.js
  aio/scripts/conf.sh
  aio/scripts/start-cluster.sh
  aio/scripts/stop-cluster.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#3773 manually specify webdriver-manager to support chrome 74
  package-lock.json
  package.json
Labels: approved, cncf-cla: yes, lgtm, size/M
