Repository kubernetes/dashboard, pull requests merged in 2019-12, with the labels that each got.

#4619 Rewrite allocation charts
  i18n/fr/messages.fr.xlf
  i18n/ja/messages.ja.xlf
  i18n/ko/messages.ko.xlf
  i18n/messages.xlf
  i18n/zh/messages.zh.xlf
  src/app/frontend/common/components/allocationchart/component.ts
  src/app/frontend/common/components/allocationchart/template.html
  src/app/frontend/common/components/graph/helper.ts
  src/app/frontend/common/components/module.ts
  src/app/frontend/common/components/workloadstatus/component.spec.ts
  src/app/frontend/overview/component.spec.ts
  src/app/frontend/resource/cluster/node/detail/component.ts
  src/app/frontend/resource/cluster/node/detail/style.scss
  src/app/frontend/resource/cluster/node/detail/template.html
Labels: approved, cncf-cla: yes, language/fr, language/ja, language/ko, language/zh, lgtm, size/XL

#4636 Bump version to v2.0.0-beta7
  aio/deploy/alternative.yaml
  aio/deploy/alternative/06_dashboard-deployment.yaml
  aio/deploy/recommended.yaml
  aio/deploy/recommended/06_dashboard-deployment.yaml
  aio/gulp/conf.js
  docs/user/installation.md
  package-lock.json
  package.json
Labels: approved, cncf-cla: yes, lgtm, size/S

#4637 Fix graph display when values in series have different suffixes
  src/app/frontend/common/components/graph/component.ts
  src/app/frontend/common/components/graph/helper.ts
  src/app/frontend/resource/cluster/node/detail/component.ts
Labels: approved, cncf-cla: yes, lgtm, size/L

#4641 Bump version to v2.0.0-beta8
  aio/deploy/alternative.yaml
  aio/deploy/alternative/06_dashboard-deployment.yaml
  aio/deploy/recommended.yaml
  aio/deploy/recommended/06_dashboard-deployment.yaml
  aio/gulp/conf.js
  docs/user/installation.md
  package-lock.json
  package.json
Labels: approved, cncf-cla: yes, lgtm, size/S

#4645 Deprecate API version in sample plugin-crd
  aio/test-resources/plugin-crd.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4647 Update Plugin docs
  docs/plugins/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4660 Use bionic in Travis CI
  .travis.yml
Labels: approved, cncf-cla: yes, lgtm, size/S

#4657 Add firefox and enable to run test on development container
  aio/develop/Dockerfile
  aio/karma.conf.js
Labels: approved, cncf-cla: yes, lgtm, size/S

#4659 Update creating-sample-user.md
  docs/user/access-control/creating-sample-user.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#4653 Fix sample plugin1 providers
  projects/custom/src/plugin1/plugin1.module.ts
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4667 Modified the PodRequestAndLimits function
  src/app/backend/resource/node/detail.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#4687 Add default sorting to all resource lists
  i18n/fr/messages.fr.xlf
  i18n/ja/messages.ja.xlf
  i18n/ko/messages.ko.xlf
  i18n/messages.xlf
  i18n/zh/messages.zh.xlf
  src/app/frontend/common/components/resourcelist/crd/template.html
  src/app/frontend/common/components/resourcelist/cronjob/template.html
  src/app/frontend/common/components/resourcelist/namespace/template.html
Labels: approved, cncf-cla: yes, language/fr, language/ja, language/ko, language/zh, lgtm, size/S

#4688 Fix container env var flicker on pod details
  src/app/frontend/common/components/container/component.ts
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4558 Skip metrics that do not exist, e.g. when pod is in pending or succeeded phase.
  src/app/backend/integration/metric/api/types.go
  src/app/backend/integration/metric/sidecar/client.go
  src/app/backend/resource/pod/list.go
  src/app/backend/resource/pod/metrics.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#4700 Fix i18n or i18n-matTooltip attributes
  i18n/fr/messages.fr.xlf
  i18n/ja/messages.ja.xlf
  i18n/ko/messages.ko.xlf
  i18n/messages.xlf
  i18n/zh/messages.zh.xlf
  src/app/frontend/common/components/podstatus/template.html
  src/app/frontend/resource/cluster/namespace/detail/actionbar/template.html
  src/app/frontend/resource/cluster/storageclass/detail/template.html
Labels: approved, cncf-cla: yes, language/fr, language/ja, language/ko, language/zh, lgtm, size/L

#4697 Update FR i18n
  i18n/fr/messages.fr.xlf
Labels: approved, cncf-cla: yes, language/fr, lgtm, size/XS

#4702 Update README.md for new release & URL
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4703 Update Japanese translation file
  i18n/ja/messages.ja.xlf
Labels: approved, cncf-cla: yes, language/ja, lgtm, size/S

#4695 Update Korean l10n for Dashboard
  i18n/ko/messages.ko.xlf
Labels: approved, cncf-cla: yes, language/ko, lgtm, size/M

#4706 update zh i18n
  i18n/zh/messages.zh.xlf
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/M

#4709 update zh i18n
  i18n/zh/messages.zh.xlf
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/M

#4710 Update translation files for Chinese
  i18n/zh/messages.zh.xlf
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/L
