Repository kubernetes/dashboard, pull requests merged in 2019-05, with the labels that each got.

#3785 Show all workloads in search result
  src/app/frontend/search/template.html
Labels: approved, cncf-cla: yes, lgtm, size/S

#3794 Update webdriver-manager to 12.1.4
  package-lock.json
  package.json
Labels: approved, cncf-cla: yes, size/XS

#3797 Greenkeeper/sass lint 1.13.1
  package-lock.json
  package.json
Labels: approved, cncf-cla: no, do-not-merge/invalid-commit-message, size/XXL

#3783 Fix selection of other containers in shell
  src/app/frontend/shell/component.ts
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3812 French translation fixes
  .npmrc
  package.json
  src/app/backend/args/builder.go
  src/app/backend/args/holder.go
  src/app/backend/dashboard.go
  src/app/backend/handler/localehandler.go
  src/app/frontend/chrome/notifications/template.html
  src/app/frontend/common/components/card/template.html
Labels: approved, cncf-cla: yes, lgtm, size/M

#3810 Update style format message to correct npm script
  aio/scripts/format.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3767 Show tooltip timestamp on time hover across pages
  src/app/frontend/chrome/notifications/template.html
  src/app/frontend/common/components/condition/template.html
  src/app/frontend/common/components/creator/template.html
  src/app/frontend/common/components/date/component.ts
  src/app/frontend/common/components/date/style.scss
  src/app/frontend/common/components/date/template.html
  src/app/frontend/common/components/module.ts
  src/app/frontend/common/components/objectmeta/template.html
  src/app/frontend/common/components/quotas/template.html
  src/app/frontend/common/components/resourcelist/clusterrole/template.html
  src/app/frontend/common/components/resourcelist/configmap/template.html
  src/app/frontend/common/components/resourcelist/cronjob/template.html
  src/app/frontend/common/components/resourcelist/daemonset/template.html
  src/app/frontend/common/components/resourcelist/deployment/template.html
  src/app/frontend/common/components/resourcelist/ingress/template.html
  src/app/frontend/common/components/resourcelist/job/template.html
  src/app/frontend/common/components/resourcelist/namespace/template.html
  src/app/frontend/common/components/resourcelist/node/template.html
  src/app/frontend/common/components/resourcelist/persistentvolume/template.html
  src/app/frontend/common/components/resourcelist/persistentvolumeclaim/template.html
  src/app/frontend/common/components/resourcelist/pod/template.html
  src/app/frontend/common/components/resourcelist/replicaset/template.html
  src/app/frontend/common/components/resourcelist/replicationcontroller/template.html
  src/app/frontend/common/components/resourcelist/secret/template.html
  src/app/frontend/common/components/resourcelist/service/template.html
  src/app/frontend/common/components/resourcelist/statefulset/template.html
  src/app/frontend/common/components/resourcelist/storageclass/template.html
  src/app/frontend/logs/template.html
  src/app/frontend/resource/workloads/deployment/detail/template.html
Labels: approved, cncf-cla: yes, lgtm, size/L

#3819 explicitly close termianlSession to avoid memory leak
  src/app/backend/handler/terminal.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3766 Move logs icons to a menu
  i18n/messages.fr.xlf
  i18n/messages.xlf
  src/app/frontend/logs/template.html
Labels: approved, cncf-cla: yes, lgtm, size/L

#3837 Update to the new Angular
  .travis.yml
  package-lock.json
  package.json
  src/app/frontend/chrome/nav/component.ts
  src/app/frontend/common/components/list/column/component.ts
  src/app/frontend/common/components/list/filter/component.ts
  src/app/frontend/common/components/namespace/component.ts
  src/app/frontend/common/dialogs/editresource/dialog.ts
  src/app/frontend/common/resources/list.ts
  src/app/frontend/create/from/file/component.ts
  src/app/frontend/logs/component.ts
  src/app/frontend/shell/component.ts
  tslint.json
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#3590 Switch chart engine from nvd3 to c3
  angular.json
  package-lock.json
  package.json
  src/app/frontend/common/components/allocationchart/component.ts
  src/app/frontend/overview/workloadstatus/template.html
Labels: approved, cncf-cla: yes, lgtm, size/XL
