Repository kubernetes/dashboard, pull requests merged in 2019-07, with the labels that each got.

#3988 fixing breadcrumb title on storage class
  src/app/frontend/resource/cluster/storageclass/routing.ts
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3990 Enable `go mod` in container for development
  aio/develop/Dockerfile
  aio/develop/run-npm-on-container.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3994 Nit: Update comment in Github PR template
  .github/ISSUE_TEMPLATE/enhancement.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3991 Add xliffmerge to update translated files
  aio/develop/Dockerfile
  aio/scripts/pre-commit-i18n.sh
  i18n/messages.fr.xlf
  i18n/messages.ja.xlf
  package-lock.json
  package.json
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#3989 Add workload statuses to workloads view
  i18n/messages.xlf
  src/app/frontend/common/components/module.ts
  src/app/frontend/common/components/workloadstatus/component.spec.ts
  src/app/frontend/common/components/workloadstatus/component.ts
  src/app/frontend/common/components/workloadstatus/style.scss
  src/app/frontend/common/components/workloadstatus/template.html
  src/app/frontend/overview/component.spec.ts
  src/app/frontend/overview/component.ts
  src/app/frontend/overview/module.ts
  src/app/frontend/resource/workloads/component.ts
  src/app/frontend/resource/workloads/template.html
Labels: approved, cncf-cla: yes, lgtm, size/L

#4009 Reorganize `docs/`
  README.md
  docs/README.md
  docs/common/README.md
  docs/common/dashboard-arguments.md
  docs/common/faq.md
  docs/common/roadmap.md
  docs/developer/README.md
  docs/developer/architecture.md
  docs/developer/code-conventions.md
  docs/developer/dependency-management.md
  docs/developer/getting-started.md
  docs/developer/internationalization.md
  docs/developer/release-procedures.md
  docs/developer/text-conventions.md
  docs/user/README.md
  docs/user/access-control/README.md
  docs/user/access-control/creating-sample-user.md
  docs/user/accessing-dashboard/1.6.x-and-below.md
  docs/user/accessing-dashboard/1.7.x-and-above.md
  docs/user/accessing-dashboard/README.md
  docs/user/certificate-management.md
  docs/user/installation.md
  docs/user/integrations.md
  docs/user/labels.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#3843 CRD Support - Backend
  go.mod
  go.sum
  src/app/backend/api/types.go
  src/app/backend/auth/manager_test.go
  src/app/backend/client/api/types.go
  src/app/backend/client/manager.go
  src/app/backend/client/manager_test.go
  src/app/backend/client/verber.go
  src/app/backend/handler/apihandler.go
  src/app/backend/resource/common/resourcechannels.go
  src/app/backend/resource/customresourcedefinition/client.go
  src/app/backend/resource/customresourcedefinition/common.go
  src/app/backend/resource/customresourcedefinition/detail.go
  src/app/backend/resource/customresourcedefinition/events.go
  src/app/backend/resource/customresourcedefinition/events_test.go
  src/app/backend/resource/customresourcedefinition/list.go
  src/app/backend/resource/customresourcedefinition/list_test.go
  src/app/backend/resource/customresourcedefinition/objects.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#4020 Fix the wording on settings page
  .gitignore
  i18n/messages.xlf
  src/app/frontend/settings/global/template.html
Labels: approved, cncf-cla: yes, lgtm, size/S

#4019 Update deploy files
  .travis.yml
  aio/deploy/alternative.yaml
  aio/deploy/alternative/00_dashboard-namespace.yaml
  aio/deploy/alternative/01_dashboard-serviceaccount.yaml
  aio/deploy/alternative/02_dashboard-service.yaml
  aio/deploy/alternative/03_dashboard-secret.yaml
  aio/deploy/alternative/04_dashboard-configmap.yaml
  aio/deploy/alternative/05_dashboard-rbac.yaml
  aio/deploy/alternative/06_dashboard-deployment.yaml
  aio/deploy/alternative/07_scraper-service.yaml
  aio/deploy/alternative/08_scraper-deployment.yaml
  aio/deploy/alternative/kubernetes-dashboard-arm-head.yaml
  aio/deploy/alternative/kubernetes-dashboard-arm.yaml
  aio/deploy/alternative/kubernetes-dashboard-head.yaml
  aio/deploy/alternative/kubernetes-dashboard.yaml
  aio/deploy/head.yaml
  aio/deploy/head/00_dashboard-namespace.yaml
  aio/deploy/head/01_dashboard-serviceaccount.yaml
  aio/deploy/head/02_dashboard-service.yaml
  aio/deploy/head/03_dashboard-secret.yaml
  aio/deploy/head/04_dashboard-configmap.yaml
  aio/deploy/head/05_dashboard-rbac.yaml
  aio/deploy/head/06_dashboard-deployment.yaml
  aio/deploy/head/07_scraper-service.yaml
  aio/deploy/head/08_scraper-deployment.yaml
  aio/deploy/recommended.yaml
  aio/deploy/recommended/00_dashboard-namespace.yaml
  aio/deploy/recommended/01_dashboard-serviceaccount.yaml
  aio/deploy/recommended/02_dashboard-service.yaml
  aio/deploy/recommended/03_dashboard-secret.yaml
  aio/deploy/recommended/04_dashboard-configmap.yaml
  aio/deploy/recommended/05_dashboard-rbac.yaml
  aio/deploy/recommended/06_dashboard-deployment.yaml
  aio/deploy/recommended/07_scraper-service.yaml
  aio/deploy/recommended/08_scraper-deployment.yaml
  aio/deploy/recommended/kubernetes-dashboard-arm-head.yaml
  aio/deploy/recommended/kubernetes-dashboard-arm.yaml
  aio/deploy/recommended/kubernetes-dashboard-head.yaml
  aio/deploy/recommended/kubernetes-dashboard.yaml
  aio/gulp/conf.js
  aio/gulp/deploy.js
  i18n/messages.fr.xlf
  i18n/messages.ja.xlf
  package.json
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#4018 Release v2.0.0-beta1
  aio/gulp/conf.js
  package.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4012 Updte parts of docs for developer guide
  docs/developer/README.md
  docs/developer/code-conventions.md
  docs/developer/getting-started.md
  docs/developer/internationalization.md
  docs/developer/text-conventions.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#4045 Fix shell and npm dep vulnerability
  package-lock.json
  package.json
  src/app/frontend/shell/component.ts
Labels: approved, cncf-cla: yes, lgtm, size/S

#4047 Fix and refactor workload statuses
  i18n/messages.fr.xlf
  i18n/messages.ja.xlf
  i18n/messages.xlf
  src/app/frontend/common/components/allocationchart/component.ts
  src/app/frontend/common/components/resourcelist/clusterrole/component.ts
  src/app/frontend/common/components/resourcelist/configmap/component.ts
  src/app/frontend/common/components/resourcelist/cronjob/component.ts
  src/app/frontend/common/components/resourcelist/daemonset/component.ts
  src/app/frontend/common/components/resourcelist/deployment/component.ts
  src/app/frontend/common/components/resourcelist/event/component.ts
  src/app/frontend/common/components/resourcelist/groupids.ts
  src/app/frontend/common/components/resourcelist/ingress/component.ts
  src/app/frontend/common/components/resourcelist/job/component.ts
  src/app/frontend/common/components/resourcelist/namespace/component.ts
  src/app/frontend/common/components/resourcelist/node/component.ts
  src/app/frontend/common/components/resourcelist/persistentvolume/component.ts
  src/app/frontend/common/components/resourcelist/persistentvolumeclaim/component.ts
  src/app/frontend/common/components/resourcelist/pod/component.ts
  src/app/frontend/common/components/resourcelist/replicaset/component.ts
  src/app/frontend/common/components/resourcelist/replicationcontroller/component.ts
  src/app/frontend/common/components/resourcelist/secret/component.ts
  src/app/frontend/common/components/resourcelist/service/component.ts
  src/app/frontend/common/components/resourcelist/statefulset/component.ts
  src/app/frontend/common/components/resourcelist/storageclass/component.ts
  src/app/frontend/common/components/workloadstatus/template.html
  src/app/frontend/common/resources/groupedlist.ts
  src/app/frontend/common/resources/list.ts
  src/app/frontend/overview/component.spec.ts
  src/app/frontend/overview/component.ts
  src/app/frontend/overview/template.html
  src/app/frontend/resource/workloads/component.ts
  src/app/frontend/search/component.ts
  src/app/frontend/typings/frontendapi.ts
Labels: approved, cncf-cla: yes, lgtm, size/L

#4048 Update dependencies to support Kubernetes v15.0.0
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/M

#4050 Remove rf232 from maintainers
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4051 Fix skip button on login view
  src/app/frontend/common/services/global/authentication.ts
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4049 Redesign chips
  i18n/messages.fr.xlf
  i18n/messages.ja.xlf
  i18n/messages.xlf
  src/app/frontend/_theming.scss
  src/app/frontend/common/components/chips/template.html
  src/app/frontend/index.scss
Labels: approved, cncf-cla: yes, lgtm, size/M

#4052 Migrate some of the docs
  README.md
  docs/README.md
  docs/common/dashboard-arguments.md
  docs/common/faq.md
  docs/common/roadmap.md
  docs/developer/architecture.md
  docs/developer/dependency-management.md
  docs/developer/release-procedures.md
  docs/developer/text-conventions.md
  docs/images/architecture.png
  docs/images/dashboard-ui.png
  docs/images/kubecon-infographic-nov2016.png
  docs/user/access-control/README.md
  docs/user/access-control/creating-sample-user.md
  docs/user/accessing-dashboard/1.6.x-and-below.md
  docs/user/accessing-dashboard/1.7.x-and-above.md
  docs/user/accessing-dashboard/README.md
  docs/user/certificate-management.md
  docs/user/installation.md
  docs/user/integrations.md
  docs/user/labels.md
  src/app/frontend/about/actionbar/template.html
Labels: approved, cncf-cla: yes, lgtm, size/L

#4017 Plugin controller to manage plugin source from dashboard backend
  aio/gulp/check.js
  aio/scripts/license-header.go.txt
  aio/scripts/update-codegen.sh
  aio/test-resources/plugin-crd.yml
  aio/test-resources/plugin-test.yml
  go.sum
  src/app/backend/auth/manager_test.go
  src/app/backend/client/api/types.go
  src/app/backend/client/manager.go
  src/app/backend/handler/apihandler.go
  src/app/backend/plugin/apis/register.go
  src/app/backend/plugin/apis/v1alpha1/doc.go
  src/app/backend/plugin/apis/v1alpha1/register.go
  src/app/backend/plugin/apis/v1alpha1/types.go
  src/app/backend/plugin/apis/v1alpha1/zz_generated.deepcopy.go
  src/app/backend/plugin/client/clientset/versioned/clientset.go
  src/app/backend/plugin/client/clientset/versioned/doc.go
  src/app/backend/plugin/client/clientset/versioned/fake/clientset_generated.go
  src/app/backend/plugin/client/clientset/versioned/fake/doc.go
  src/app/backend/plugin/client/clientset/versioned/fake/register.go
  src/app/backend/plugin/client/clientset/versioned/scheme/doc.go
  src/app/backend/plugin/client/clientset/versioned/scheme/register.go
  src/app/backend/plugin/client/clientset/versioned/typed/apis/v1alpha1/apis_client.go
  src/app/backend/plugin/client/clientset/versioned/typed/apis/v1alpha1/doc.go
  src/app/backend/plugin/client/clientset/versioned/typed/apis/v1alpha1/fake/doc.go
  src/app/backend/plugin/client/clientset/versioned/typed/apis/v1alpha1/fake/fake_apis_client.go
  src/app/backend/plugin/client/clientset/versioned/typed/apis/v1alpha1/fake/fake_plugin.go
  src/app/backend/plugin/client/clientset/versioned/typed/apis/v1alpha1/generated_expansion.go
  src/app/backend/plugin/client/clientset/versioned/typed/apis/v1alpha1/plugin.go
  src/app/backend/plugin/client/informers/externalversions/apis/interface.go
  src/app/backend/plugin/client/informers/externalversions/apis/v1alpha1/interface.go
  src/app/backend/plugin/client/informers/externalversions/apis/v1alpha1/plugin.go
  src/app/backend/plugin/client/informers/externalversions/factory.go
  src/app/backend/plugin/client/informers/externalversions/generic.go
  src/app/backend/plugin/client/informers/externalversions/internalinterfaces/factory_interfaces.go
  src/app/backend/plugin/client/listers/apis/v1alpha1/expansion_generated.go
  src/app/backend/plugin/client/listers/apis/v1alpha1/plugin.go
  src/app/backend/plugin/detail.go
  src/app/backend/plugin/detail_test.go
  src/app/backend/plugin/handler.go
  src/app/backend/plugin/handler_test.go
  src/app/backend/plugin/list.go
  src/app/backend/plugin/list_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#4062 Migrate docs for `Labels`
  docs/user/labels.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#4033 Fix ingress endpoint resolution
  src/app/backend/resource/ingress/list.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4063 init Chinese translation
  i18n/locale_conf.json
  i18n/messages.zh.xlf
  package.json
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#4074 Correct typo in markdown formatting
  docs/developer/getting-started.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4080 Restore history service and add auto-refresh
  i18n/messages.fr.xlf
  i18n/messages.ja.xlf
  i18n/messages.xlf
  i18n/messages.zh.xlf
  src/app/backend/settings/api/types.go
  src/app/frontend/chrome/component.ts
  src/app/frontend/common/components/actionbar/detailactions/delete/component.ts
  src/app/frontend/common/components/actionbar/detailactions/edit/component.ts
  src/app/frontend/common/components/actionbar/detailactions/scale/component.ts
  src/app/frontend/common/components/actionbar/detailactions/trigger/component.ts
  src/app/frontend/common/components/list/column/menu/component.ts
  src/app/frontend/common/components/namespace/component.ts
  src/app/frontend/common/components/resourcelist/pod/component.ts
  src/app/frontend/common/resources/list.ts
  src/app/frontend/common/resources/resource.ts
  src/app/frontend/common/services/global/globalsettings.ts
  src/app/frontend/common/services/global/history.ts
  src/app/frontend/common/services/global/module.ts
  src/app/frontend/common/services/resource/resource.ts
  src/app/frontend/logs/component.ts
  src/app/frontend/settings/global/component.ts
  src/app/frontend/settings/global/template.html
  src/app/frontend/typings/backendapi.d.ts
Labels: approved, cncf-cla: yes, lgtm, size/L

#4046 Support dashboard-metrics-scraper on development container
  .gitignore
  .npmrc
  aio/develop/Dockerfile
  aio/develop/npm-command.sh
  aio/develop/run-npm-on-container.sh
  package.json
Labels: approved, cncf-cla: yes, lgtm, size/M

#4082 impersonation support for the dashboard
  docs/user/README.md
  docs/user/images/dashboard-impersonation.png
  i18n/messages.fr.xlf
  i18n/messages.ja.xlf
  i18n/messages.xlf
  src/app/backend/client/manager.go
  src/app/backend/client/manager_test.go
  src/app/backend/validation/validateloginstatus.go
  src/app/frontend/chrome/userpanel/template.html
Labels: approved, cncf-cla: yes, lgtm, size/L

#4081 Reenable namespace change dialog
  src/app/frontend/common/components/namespace/component.ts
  src/app/frontend/common/services/global/namespace.ts
Labels: approved, cncf-cla: yes, lgtm, size/L

#4083 Make deployment files consistent
  aio/deploy/alternative.yaml
  aio/deploy/alternative/07_scraper-service.yaml
  aio/deploy/alternative/08_scraper-deployment.yaml
  aio/deploy/head.yaml
  aio/deploy/head/05_dashboard-rbac.yaml
  aio/deploy/head/07_scraper-service.yaml
  aio/deploy/head/08_scraper-deployment.yaml
  aio/deploy/recommended.yaml
  aio/deploy/recommended/07_scraper-service.yaml
  aio/deploy/recommended/08_scraper-deployment.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#4084 Bump version to v2.0.0-beta2
  aio/deploy/alternative.yaml
  aio/deploy/alternative/06_dashboard-deployment.yaml
  aio/deploy/alternative/08_scraper-deployment.yaml
  aio/deploy/recommended.yaml
  aio/deploy/recommended/06_dashboard-deployment.yaml
  aio/deploy/recommended/08_scraper-deployment.yaml
  aio/gulp/conf.js
  package.json
Labels: approved, cncf-cla: yes, lgtm, size/S

#4087 add tmp-volume to metrics-scraper
  aio/deploy/alternative.yaml
  aio/deploy/alternative/08_scraper-deployment.yaml
  aio/deploy/head.yaml
  aio/deploy/head/08_scraper-deployment.yaml
  aio/deploy/recommended.yaml
  aio/deploy/recommended/08_scraper-deployment.yaml
  aio/test-resources/kubernetes-dashboard-local.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#4103 Make Resource information card title consistent
  i18n/messages.fr.xlf
  i18n/messages.ja.xlf
  i18n/messages.xlf
  i18n/messages.zh.xlf
  src/app/frontend/resource/cluster/namespace/detail/template.html
  src/app/frontend/resource/cluster/node/detail/template.html
  src/app/frontend/resource/cluster/persistentvolume/detail/template.html
  src/app/frontend/resource/cluster/storageclass/detail/template.html
  src/app/frontend/resource/config/persistentvolumeclaim/detail/template.html
  src/app/frontend/resource/discovery/service/detail/template.html
  src/app/frontend/resource/workloads/cronjob/detail/template.html
  src/app/frontend/resource/workloads/daemonset/detail/template.html
  src/app/frontend/resource/workloads/deployment/detail/template.html
  src/app/frontend/resource/workloads/job/detail/template.html
  src/app/frontend/resource/workloads/pod/detail/template.html
  src/app/frontend/resource/workloads/replicaset/detail/template.html
  src/app/frontend/resource/workloads/replicationcontroller/detail/template.html
  src/app/frontend/resource/workloads/statefulset/detail/template.html
Labels: approved, cncf-cla: yes, lgtm, size/XL

#4106 [bugfix] Change golang tag
  aio/develop/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4109 Update errors.ts
  src/app/frontend/common/errors/errors.ts
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4113 Re-install git in development container and suppress download from `golangci-lint`
  .golangci.yml
  aio/develop/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/S

#3593 Support $KUBECONFIG
  package.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4119 Remove auth cookies when forced logged out
  package-lock.json
  package.json
  src/app/frontend/common/services/global/authentication.ts
  src/app/frontend/error/handler.ts
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#4120 Fix GID on development container
  aio/develop/gosu-command.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4118 Fix chips styling
  src/app/frontend/index.scss
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4122 Fix text input
  src/app/frontend/common/components/textinput/component.ts
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4143 add metrics-provider's no check metrics option
  src/app/backend/dashboard.go
Labels: approved, cncf-cla: yes, lgtm, size/XS
