Repository kubernetes/dashboard, pull requests merged in 2019-10, with the labels that each got.

#4358 Update docs for i18n
  docs/developer/internationalization.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#4362 Add README for Japanese i18n team
  i18n/ja/README.md
Labels: approved, cncf-cla: yes, language/ja, lgtm, size/L

#4346 Update Kubernetes deps to v1.16
  go.mod
  go.sum
  src/app/backend/resource/customresourcedefinition/client.go
  src/app/backend/resource/node/detail.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#4378 Fix graph refresh on namespace change
  src/app/frontend/common/components/graph/component.ts
  src/app/frontend/common/components/graphcard/component.spec.ts
Labels: approved, cncf-cla: yes, lgtm, size/M

#4383 Add "language/xx" to "labels" in all i18n OWNERS
  i18n/fr/OWNERS
  i18n/ja/OWNERS
  i18n/ko/OWNERS
  i18n/zh/OWNERS
Labels: approved, cncf-cla: yes, language/fr, language/ja, language/ko, language/zh, lgtm, size/XS

#4390 Fix const misspell in chips component
  src/app/frontend/common/components/chips/component.ts
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4396 [IMP] correct some grammar mistakes to improve clarity
  docs/user/accessing-dashboard/1.7.x-and-above.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4344 Disables namespace input autocomplete (#4343)
  src/app/frontend/common/components/namespace/template.html
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4377 Update API versions
  aio/deploy/alternative.yaml
  aio/deploy/alternative/06_dashboard-deployment.yaml
  aio/deploy/head.yaml
  aio/test-resources/nginx-daemon-daemon-set.yaml
  aio/test-resources/plugin-crd.yml
  src/app/backend/api/types.go
  src/app/backend/client/manager.go
  src/app/backend/client/verber_test.go
  src/app/backend/resource/deployment/deploy.go
  src/app/backend/scaling/scale.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#4384 Redesign errors on login page
  i18n/fr/messages.fr.xlf
  i18n/ja/messages.ja.xlf
  i18n/ko/messages.ko.xlf
  i18n/messages.xlf
  i18n/zh/messages.zh.xlf
  src/app/frontend/login/style.scss
  src/app/frontend/login/template.html
Labels: approved, cncf-cla: yes, language/fr, language/ja, language/ko, language/zh, lgtm, size/L

#4409 docs(internationalization): fix typo
  docs/developer/internationalization.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4412 Enlarge the "Edit a resource" modal
  src/app/frontend/common/components/textinput/component.ts
  src/app/frontend/common/services/global/verber.ts
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4419 Release v2.0.0-beta5
  aio/deploy/alternative.yaml
  aio/deploy/alternative/06_dashboard-deployment.yaml
  aio/deploy/recommended.yaml
  aio/deploy/recommended/06_dashboard-deployment.yaml
  aio/gulp/conf.js
  docs/user/installation.md
  package-lock.json
  package.json
Labels: approved, cncf-cla: yes, lgtm, size/S

#4407 add user to zh/OWNERS
  i18n/zh/OWNERS
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/XS

#4424 Reduce code duplication and fix typo
  src/app/backend/api/types.go
  src/app/backend/handler/apihandler.go
  src/app/backend/scaling/scale.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#4432 Use golint
  src/app/backend/cert/api/types.go
  src/app/backend/cert/manager.go
  src/app/backend/client/api/types.go
  src/app/backend/client/verber.go
  src/app/backend/resource/deployment/common.go
  src/app/backend/resource/deployment/detail.go
  src/app/backend/resource/deployment/list.go
  src/app/backend/resource/deployment/newreplicasets.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#4437 use golint and fix typo
  src/app/backend/errors/errors.go
  src/app/backend/errors/handler.go
  src/app/backend/resource/pod/common.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#4438 fix golint failures
  src/app/backend/integration/metric/heapster/selector.go
  src/app/backend/integration/metric/sidecar/selector.go
  src/app/backend/resource/secret/list.go
  src/app/backend/resource/service/list.go
  src/app/backend/resource/statefulset/list.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#4439 fix golint failures
  src/app/backend/resource/common/pod.go
  src/app/backend/resource/configmap/list.go
  src/app/backend/resource/cronjob/list.go
  src/app/backend/resource/daemonset/detail.go
  src/app/backend/resource/daemonset/list.go
  src/app/backend/resource/ingress/list.go
  src/app/backend/resource/job/list.go
  src/app/backend/resource/limitrange/detail.go
  src/app/backend/resource/persistentvolumeclaim/list.go
  src/app/backend/resource/pod/list.go
  src/app/backend/resource/replicaset/list.go
  src/app/backend/resource/replicationcontroller/list.go
  src/app/backend/systembanner/api/types.go
  src/app/backend/validation/validaterbacstatus.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#4448 add me to approver of dashboard
  i18n/zh/OWNERS
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/XS

#4457 Block search engines from indexing Dashboard
  angular.json
  src/app/frontend/assets/robots.txt
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4468 remove some useless codes
  src/app/backend/handler/apihandler.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4483 Fix openssl command in docs
  docs/user/certificate-management.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4458 fix golint failures
  src/app/backend/resource/common/resourcechannels.go
  src/app/backend/resource/daemonset/common.go
  src/app/backend/resource/dataselect/dataselectquery.go
  src/app/backend/resource/dataselect/stdcomparabletypes.go
  src/app/backend/resource/event/common.go
  src/app/backend/resource/horizontalpodautoscaler/common.go
  src/app/backend/resource/logs/logs.go
  src/app/backend/resource/resourcequota/detail.go
  src/app/backend/settings/api/types.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#4463 go lint failure
  src/app/backend/auth/jwe/util.go
  src/app/backend/handler/apihandler.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#4475 remove some useless code in handler/apihandler.api
  src/app/backend/handler/apihandler.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4465 Add metric graphs on cronjob, job and pod list pages.
  src/app/frontend/common/components/resourcelist/cronjob/component.ts
  src/app/frontend/common/components/resourcelist/cronjob/template.html
  src/app/frontend/common/components/resourcelist/job/component.ts
  src/app/frontend/common/components/resourcelist/job/template.html
  src/app/frontend/common/components/resourcelist/pod/component.ts
  src/app/frontend/common/components/resourcelist/pod/template.html
  src/app/frontend/overview/component.spec.ts
  src/app/frontend/resource/workloads/cronjob/list/component.ts
  src/app/frontend/resource/workloads/job/list/component.ts
  src/app/frontend/resource/workloads/pod/list/component.ts
  src/app/frontend/typings/backendapi.d.ts
Labels: approved, cncf-cla: yes, lgtm, size/M

#4480 add list/details for Role resource
  src/app/backend/api/types.go
  src/app/backend/handler/apihandler.go
  src/app/backend/resource/common/resourcechannels.go
  src/app/backend/resource/role/common.go
  src/app/backend/resource/role/detail.go
  src/app/backend/resource/role/list.go
  src/app/backend/resource/role/list_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L
