Repository kubernetes/dashboard, pull requests merged in 2019-02, with the labels that each got.

#3544 Add new issue templates for failing tests and support
  .github/ISSUE_TEMPLATE/failing-test.md
  .github/ISSUE_TEMPLATE/support.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#3540 Change e2e tests to use kind
  .travis.yml
  aio/scripts/conf.sh
  aio/scripts/start-cluster.sh
  aio/scripts/stop-cluster.sh
  package.json
Labels: approved, cncf-cla: yes, do-not-merge/hold, lgtm, size/M

#3547 Updated OWNERS file to include link to docs
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3514 align actionbar actions with context actions
  src/app/frontend/common/components/actionbar/detailactions/component.ts
  src/app/frontend/common/components/list/column/menu/component.ts
  src/app/frontend/common/components/list/column/menu/template.html
Labels: approved, cncf-cla: yes, lgtm, size/M

#3549 Use client-go/dynamic instead client-go/deprecated-dynamic
  Gopkg.lock
  src/app/backend/resource/deployment/deploy.go
  vendor/k8s.io/client-go/deprecated-dynamic/bad_debt.go
  vendor/k8s.io/client-go/deprecated-dynamic/client.go
  vendor/k8s.io/client-go/deprecated-dynamic/client_pool.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#3469 Rework resource Status for Job List Pie Chart
  src/app/backend/resource/job/common.go
  src/app/backend/resource/job/list.go
  src/app/backend/resource/job/list_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#3558 Show light-colored scrollbar in dark logs mode
  src/app/frontend/logs/style.scss
  src/app/frontend/logs/template.html
Labels: approved, cncf-cla: yes, lgtm, size/S

#3559 Added tooltip for Timestamp icon on Logs page
  src/app/frontend/logs/template.html
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3562 Display query in search bar after namespace change and page reload
  src/app/frontend/chrome/search/component.ts
Labels: approved, cncf-cla: yes, do-not-merge/hold, lgtm, size/XS

#3323 Add container for development outside cluster
  aio/develop/Dockerfile
  aio/develop/npm-command.sh
  aio/develop/run-npm-on-container.sh
  aio/karma.conf.js
Labels: approved, cncf-cla: yes, lgtm, size/L

#3575 Add option to trigger cron jobs and remove unused button components
  src/app/frontend/common/components/actionbar/detailactions/trigger/component.ts
  src/app/frontend/common/components/actionbar/detailactions/trigger/template.html
  src/app/frontend/common/components/actionbars/triggerdefault/component.ts
  src/app/frontend/common/components/actionbars/triggerdefault/template.html
  src/app/frontend/common/components/list/column/deletebutton/component.ts
  src/app/frontend/common/components/list/column/deletebutton/template.html
  src/app/frontend/common/components/list/column/editbutton/component.ts
  src/app/frontend/common/components/list/column/execbutton/component.ts
  src/app/frontend/common/components/list/column/execbutton/template.html
  src/app/frontend/common/components/list/column/menu/component.ts
  src/app/frontend/common/components/list/column/menu/template.html
  src/app/frontend/common/components/list/column/scalebutton/component.ts
  src/app/frontend/common/components/list/column/scalebutton/template.html
  src/app/frontend/common/components/module.ts
  src/app/frontend/common/components/resourcelist/pod/component.ts
  src/app/frontend/common/dialogs/module.ts
  src/app/frontend/common/dialogs/triggerresource/dialog.ts
  src/app/frontend/common/dialogs/triggerresource/template.html
  src/app/frontend/common/services/global/verber.ts
  src/app/frontend/resource/workloads/cronjob/detail/state.ts
Labels: approved, cncf-cla: yes, lgtm, size/L

#3579 Let's not lint the whole k/* directory :)
  aio/scripts/lint-backend.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3586 Fix bug in CPU allocation chart
  src/app/frontend/resource/cluster/node/detail/template.html
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3596 Use blue as primary color for dark theme
  src/app/frontend/_dark.scss
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3315 Enable check:backend task on Travis CI and add goimports check
  aio/scripts/lint-backend.sh
  src/app/backend/resource/job/list_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#3594 Add list of inactive cron jobs and refactor backend structs
  src/app/backend/handler/apihandler.go
  src/app/backend/resource/cronjob/detail.go
  src/app/backend/resource/cronjob/detail_test.go
  src/app/backend/resource/cronjob/jobs.go
  src/app/frontend/resource/workloads/cronjob/detail/component.ts
  src/app/frontend/resource/workloads/cronjob/detail/template.html
Labels: approved, cncf-cla: yes, lgtm, size/L

#3561 Logs Auto Scroll
  src/app/frontend/common/services/global/logs.ts
  src/app/frontend/logs/component.ts
  src/app/frontend/logs/template.html
Labels: approved, cncf-cla: yes, lgtm, size/L

#3612 Lint fixes
  src/app/backend/handler/apihandler.go
  src/app/backend/resource/cronjob/detail.go
  src/app/backend/resource/cronjob/detail_test.go
Labels: approved, cncf-cla: yes, size/M

#3611 Greenkeeper/webpack dev server 3.2.1
  package-lock.json
  package.json
Labels: approved, cncf-cla: no, size/XL

#3605 Bump golangci-lint to 1.15.0 and add go linter for pre-commit
  .golangci.yml
  aio/scripts/lint-backend.sh
  package.json
Labels: approved, cncf-cla: yes, lgtm, size/M

#3598 Avoid throwing error when controller kind is unknown
  src/app/backend/resource/controller/controller.go
  src/app/backend/resource/pod/detail.go
  src/app/backend/resource/pod/detail_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#3613 Fix link to docs
  src/app/frontend/create/from/file/template.html
Labels: approved, cncf-cla: yes, lgtm, size/XS
