Repository kubernetes/dashboard, pull requests merged in 2019-08, with the labels that each got.

#4030 CRD Support - Frontend
  angular.json
  go.mod
  go.sum
  i18n/messages.fr.xlf
  i18n/messages.ja.xlf
  i18n/messages.xlf
  i18n/messages.zh.xlf
  package-lock.json
  package.json
  src/app/backend/api/types.go
  src/app/backend/auth/manager_test.go
  src/app/backend/client/api/types.go
  src/app/backend/client/manager.go
  src/app/backend/client/manager_test.go
  src/app/backend/client/verber.go
  src/app/backend/client/verber_test.go
  src/app/backend/errors/errors.go
  src/app/backend/handler/apihandler.go
  src/app/backend/resource/customresourcedefinition/client.go
  src/app/backend/resource/customresourcedefinition/common.go
  src/app/backend/resource/customresourcedefinition/detail.go
  src/app/backend/resource/customresourcedefinition/list.go
  src/app/backend/resource/customresourcedefinition/list_test.go
  src/app/backend/resource/customresourcedefinition/objects.go
  src/app/frontend/chrome/nav/template.html
  src/app/frontend/chrome/routing.ts
  src/app/frontend/common/components/breadcrumbs/component.ts
  src/app/frontend/common/components/condition/component.ts
  src/app/frontend/common/components/condition/template.html
  src/app/frontend/common/components/module.ts
  src/app/frontend/common/components/resourcelist/crd/component.ts
  src/app/frontend/common/components/resourcelist/crd/template.html
  src/app/frontend/common/components/resourcelist/crdobject/component.ts
  src/app/frontend/common/components/resourcelist/crdobject/template.html
  src/app/frontend/common/components/resourcelist/crdversion/component.ts
  src/app/frontend/common/components/resourcelist/crdversion/template.html
  src/app/frontend/common/components/resourcelist/groupids.ts
  src/app/frontend/common/services/resource/endpoint.ts
  src/app/frontend/common/services/resource/resource.ts
  src/app/frontend/crd/crdobject/component.ts
  src/app/frontend/crd/crdobject/template.html
  src/app/frontend/crd/detail/component.ts
  src/app/frontend/crd/detail/template.html
  src/app/frontend/crd/list/component.ts
  src/app/frontend/crd/module.ts
  src/app/frontend/crd/routing.ts
  src/app/frontend/typings/backendapi.d.ts
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#4130 Add context menus in list views for cluster resources
  src/app/frontend/common/components/resourcelist/clusterrole/template.html
  src/app/frontend/common/components/resourcelist/namespace/template.html
  src/app/frontend/common/components/resourcelist/node/template.html
  src/app/frontend/common/components/resourcelist/persistentvolume/template.html
  src/app/frontend/common/components/resourcelist/storageclass/template.html
Labels: approved, cncf-cla: yes, lgtm, size/M

#4002 Migrate e2e tests to Cypress
  .gitignore
  .travis.yml
  aio/protractor.conf.js
  aio/tsconfig.e2e.json
  angular.json
  cypress.json
  cypress/fixtures/.keep
  cypress/fixtures/README.md
  cypress/integration/basic.spec.js
  cypress/plugins/README.md
  cypress/plugins/index.js
  cypress/support/README.md
  cypress/support/commands.js
  cypress/support/index.js
  package-lock.json
  package.json
  src/test/e2e/app.e2e-spec.ts
  src/test/e2e/app.po.ts
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#4152 Prepare for v2.0.0-beta3
  aio/deploy/alternative.yaml
  aio/deploy/alternative/06_dashboard-deployment.yaml
  aio/deploy/recommended.yaml
  aio/deploy/recommended/06_dashboard-deployment.yaml
  aio/gulp/conf.js
  package-lock.json
  package.json
Labels: approved, cncf-cla: yes, lgtm, size/S

#4155 Implement CRD Objects Events Section
  src/app/frontend/crd/crdobject/component.ts
  src/app/frontend/crd/crdobject/template.html
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4156 Show time tooltips for events FirstSeen and LastSeen
  src/app/frontend/common/components/date/template.html
  src/app/frontend/common/components/resourcelist/event/template.html
Labels: approved, cncf-cla: yes, lgtm, size/S

#4164 Migrate docs for dashboard arguments
  docs/common/dashboard-arguments.md
  src/app/backend/dashboard.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#4165 Support cypress in development container
  aio/develop/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4141 Correct the resourcechannels comment
  src/app/backend/resource/common/resourcechannels.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#4171 Fix typo: requestes -> requests
  i18n/messages.fr.xlf
  i18n/messages.ja.xlf
  i18n/messages.xlf
  i18n/messages.zh.xlf
  src/app/frontend/common/components/resourcelist/node/template.html
Labels: approved, cncf-cla: yes, lgtm, size/S

#4172 Migrate DOCKER_CLI_EXPERIMENTAL and GOPROXY env from travis
  .travis.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4173 Update translations for Japanese
  i18n/messages.fr.xlf
  i18n/messages.ja.xlf
  i18n/messages.xlf
  i18n/messages.zh.xlf
Labels: approved, cncf-cla: yes, lgtm, size/M

#4174 Add Korean localization for Dashboard
  i18n/locale_conf.json
  i18n/messages.ko.xlf
  package.json
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#4170 Add `go mod download` in `postinstall`
  package.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4162 Adding unit tests for login component (#3865)
  src/app/frontend/login/component.spec.ts
Labels: approved, cncf-cla: yes, lgtm, size/L

#4169 Migrate docs for release procedures
  docs/developer/dependency-management.md
  docs/developer/getting-started.md
  docs/developer/release-procedures.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#4199 Fix typo in metrics-scraper Service deploy manifest
  aio/deploy/head/07_scraper-service.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4189 Improve Namespace-awareness for CRDs
  src/app/backend/resource/customresourcedefinition/objects.go
  src/app/frontend/crd/routing.ts
Labels: approved, cncf-cla: yes, lgtm, size/S

#4151 Use binary search in getLineIndex method
  src/app/backend/resource/container/logs_test.go
  src/app/backend/resource/logs/logs.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#4219 Set GOPROXY environment variable in development container
  aio/develop/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4220 Migrate documentation for installation
  docs/user/certificate-management.md
  docs/user/installation.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#4233 Release v2.0.0-beta4
  aio/deploy/alternative.yaml
  aio/deploy/alternative/06_dashboard-deployment.yaml
  aio/deploy/recommended.yaml
  aio/deploy/recommended/06_dashboard-deployment.yaml
  aio/gulp/conf.js
  docs/user/installation.md
  package-lock.json
  package.json
Labels: approved, cncf-cla: yes, lgtm, size/S

#4195 Support 'Scale' subresource for CRDs
  i18n/messages.fr.xlf
  i18n/messages.ja.xlf
  i18n/messages.ko.xlf
  i18n/messages.xlf
  i18n/messages.zh.xlf
  src/app/backend/api/types.go
  src/app/backend/handler/apihandler.go
  src/app/backend/resource/customresourcedefinition/detail.go
  src/app/backend/resource/customresourcedefinition/objects.go
  src/app/backend/resource/deployment/detail_test.go
  src/app/backend/resource/deployment/list_test.go
  src/app/backend/resource/replicaset/common_test.go
  src/app/backend/resource/replicaset/detail_test.go
  src/app/backend/resource/replicaset/list_test.go
  src/app/backend/resource/replicationcontroller/list_test.go
  src/app/backend/resource/statefulset/list_test.go
  src/app/backend/scaling/scale.go
  src/app/frontend/common/components/actionbars/scaledefault/component.ts
  src/app/frontend/common/components/actionbars/scaledefault/template.html
  src/app/frontend/common/components/list/column/menu/component.ts
  src/app/frontend/common/components/resourcelist/crdobject/template.html
  src/app/frontend/common/dialogs/scaleresource/dialog.ts
  src/app/frontend/common/services/global/verber.ts
  src/app/frontend/crd/detail/template.html
  src/app/frontend/crd/routing.ts
  src/app/frontend/typings/backendapi.d.ts
Labels: approved, cncf-cla: yes, lgtm, size/L

#4235 Fix prod build for macOS
  aio/gulp/backend.js
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4237 Fix text input component
  src/app/frontend/common/components/textinput/component.ts
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4236 Fix issue with error handling on login view
  i18n/messages.ko.xlf
  src/app/frontend/common/errors/errors.ts
  src/app/frontend/login/component.ts
Labels: approved, cncf-cla: yes, lgtm, size/M
