Repository kubernetes/dashboard, pull requests merged in 2019-11, with the labels that each got.

#4498 fix golint failures
  src/app/backend/integration/metric/heapster/client_test.go
  src/app/backend/integration/metric/sidecar/client_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#4507 Corrected Certificate installation incstructions
  docs/user/installation.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#4506 Fix metrics
  i18n/fr/messages.fr.xlf
  i18n/ja/messages.ja.xlf
  i18n/ko/messages.ko.xlf
  i18n/messages.xlf
  i18n/zh/messages.zh.xlf
  package.json
  src/app/backend/integration/metric/api/types.go
  src/app/backend/integration/metric/sidecar/client.go
  src/app/backend/resource/pod/list.go
  src/app/backend/resource/pod/metrics.go
Labels: approved, cncf-cla: yes, language/fr, language/ja, language/ko, language/zh, lgtm, size/XXL

#4544 Prepare for beta 6 release
  aio/deploy/alternative.yaml
  aio/deploy/alternative/06_dashboard-deployment.yaml
  aio/deploy/recommended.yaml
  aio/deploy/recommended/06_dashboard-deployment.yaml
  aio/gulp/conf.js
  docs/user/installation.md
  package-lock.json
  package.json
Labels: approved, cncf-cla: yes, size/S

#4573 Escape the pipe character in table form dashboard-arguments.md
  docs/common/dashboard-arguments.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4581 Improve contras ratio for dark theme
  src/app/frontend/_dark.scss
  src/app/frontend/_light.scss
  src/app/frontend/_theming.scss
Labels: approved, cncf-cla: yes, lgtm, size/S

#4597 Support filtering according to the type of service
  src/app/backend/resource/dataselect/propertyname.go
  src/app/backend/resource/service/common.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4607 update URL in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: cncf-cla: yes, size/XS

#4609 Initialze overwatches restartCount map
  src/app/backend/sync/overwatch.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/XS

#4605 Add Shu as an approver
  OWNERS_ALIASES
Labels: approved, cncf-cla: yes, lgtm, size/S

#4614 update URL in docs/design/troubleshooting.md
  docs/design/troubleshooting.md
Labels: cncf-cla: yes, size/XS

#4615 Add hpa handler for deployment
  src/app/backend/handler/apihandler.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#4582 Fix workload statuses
  i18n/fr/messages.fr.xlf
  i18n/ja/messages.ja.xlf
  i18n/ko/messages.ko.xlf
  i18n/messages.xlf
  i18n/zh/messages.zh.xlf
  package-lock.json
  package.json
  src/app/frontend/common/components/allocationchart/component.ts
  src/app/frontend/common/components/workloadstatus/component.spec.ts
  src/app/frontend/common/components/workloadstatus/component.ts
  src/app/frontend/common/components/workloadstatus/template.html
  src/app/frontend/overview/helper.ts
  src/app/frontend/overview/template.html
  src/app/frontend/shared.module.ts
  src/app/frontend/typings/frontendapi.ts
Labels: approved, cncf-cla: yes, language/fr, language/ja, language/ko, language/zh, lgtm, size/XL

#4620 Use ngx-charts to display graphs
  aio/karma-test-shim.js
  aio/karma.conf.js
  package-lock.json
  package.json
  src/app/frontend/_theming.scss
  src/app/frontend/common/components/allocationchart/component.ts
  src/app/frontend/common/components/graph/component.ts
  src/app/frontend/common/components/graph/helper.ts
  src/app/frontend/common/components/graph/template.html
  src/app/frontend/common/components/graphcard/component.spec.ts
  src/app/frontend/common/components/graphcard/component.ts
  src/app/frontend/common/components/graphcard/template.html
  src/app/frontend/common/components/graphmetrics/component.ts
  src/app/frontend/common/components/graphmetrics/template.html
  src/app/frontend/common/services/resource/resource.ts
Labels: approved, cncf-cla: yes, lgtm, size/XXL
