Repository kubernetes/dashboard, pull requests merged in 2019-06, with the labels that each got.

#3849 Remove unused functions
  .golangci.yml
  src/app/backend/handler/apihandler.go
  src/app/backend/integration/manager_test.go
  src/app/backend/resource/pod/common.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#3853 Bump node.js to 11.x in container for development
  aio/develop/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3874 Fix PVC view
  src/app/frontend/resource/config/persistentvolumeclaim/module.ts
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3894 Suppress angular analytics dialog on develop container
  aio/develop/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3885 Update go-restful to the latest version
  Gopkg.lock
  Gopkg.toml
  vendor/github.com/emicklei/go-restful/.travis.yml
  vendor/github.com/emicklei/go-restful/CHANGES.md
  vendor/github.com/emicklei/go-restful/Makefile
  vendor/github.com/emicklei/go-restful/README.md
  vendor/github.com/emicklei/go-restful/compress.go
  vendor/github.com/emicklei/go-restful/compressors.go
  vendor/github.com/emicklei/go-restful/container.go
  vendor/github.com/emicklei/go-restful/cors_filter.go
  vendor/github.com/emicklei/go-restful/curly.go
  vendor/github.com/emicklei/go-restful/curly_route.go
  vendor/github.com/emicklei/go-restful/doc.go
  vendor/github.com/emicklei/go-restful/entity_accessors.go
  vendor/github.com/emicklei/go-restful/filter.go
  vendor/github.com/emicklei/go-restful/install.sh
  vendor/github.com/emicklei/go-restful/json.go
  vendor/github.com/emicklei/go-restful/jsoniter.go
  vendor/github.com/emicklei/go-restful/jsr311.go
  vendor/github.com/emicklei/go-restful/log/log.go
  vendor/github.com/emicklei/go-restful/logger.go
  vendor/github.com/emicklei/go-restful/mime.go
  vendor/github.com/emicklei/go-restful/options_filter.go
  vendor/github.com/emicklei/go-restful/parameter.go
  vendor/github.com/emicklei/go-restful/path_expression.go
  vendor/github.com/emicklei/go-restful/path_processor.go
  vendor/github.com/emicklei/go-restful/request.go
  vendor/github.com/emicklei/go-restful/response.go
  vendor/github.com/emicklei/go-restful/route.go
  vendor/github.com/emicklei/go-restful/route_builder.go
  vendor/github.com/emicklei/go-restful/router.go
  vendor/github.com/emicklei/go-restful/web_service.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#3891 Modify parameter name for getNodeConditions
  src/app/backend/resource/node/common.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3800 add GraphCardComponent
  src/app/frontend/common/components/card/component.ts
  src/app/frontend/common/components/card/style.scss
  src/app/frontend/common/components/card/template.html
  src/app/frontend/common/components/graph/component.ts
  src/app/frontend/common/components/graph/helper.ts
  src/app/frontend/common/components/graph/template.html
  src/app/frontend/common/components/graphcard/component.spec.ts
  src/app/frontend/common/components/graphcard/component.ts
  src/app/frontend/common/components/graphcard/template.html
  src/app/frontend/common/components/module.ts
  src/app/frontend/overview/component.ts
  src/app/frontend/overview/style.scss
  src/app/frontend/overview/template.html
Labels: approved, cncf-cla: yes, lgtm, size/L

#3923 Do not try to refresh token when login is disabled
  src/app/frontend/common/services/global/authentication.ts
  src/app/frontend/login/component.ts
Labels: approved, cncf-cla: yes, lgtm, size/S

#3883 #3861 Remove the border of the graphs in the dark theme
  src/app/frontend/_dark.scss
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3928 fix error view
  src/app/frontend/error/component.ts
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3938 Download golangci-lint via curl
  package.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3933 Specify version for GO image and golangci-lint for develop container
  aio/develop/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3937 replace CommaSeparatedListComponent with pipe
  src/app/frontend/common/components/commaseparatedlist/template.html
  src/app/frontend/common/components/module.ts
  src/app/frontend/common/components/policyrule/template.html
  src/app/frontend/common/pipes/commaseparated.ts
  src/app/frontend/common/pipes/module.ts
Labels: approved, cncf-cla: yes, lgtm, size/M

#3943 Fix golanci-lint for pre-commit
  package.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3944 Use minimist instead of gulp-util
  aio/gulp/conf.js
  package.json
Labels: approved, cncf-cla: yes, lgtm, size/M

#3946 Add query to search breadcrumb
  src/app/frontend/common/components/breadcrumbs/component.ts
  src/app/frontend/search/routing.ts
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3951 Various fixes and improvements
  aio/closure/.closure.conf
  aio/closure/main.aot.ts
  aio/closure/webpack.config.js
  src/app/backend/integration/metric/api/types.go
  src/app/backend/integration/metric/sidecar/client.go
  src/app/backend/resource/node/list.go
  src/app/backend/resource/pod/list.go
  src/app/frontend/_theming.scss
  src/app/frontend/common/components/breadcrumbs/component.ts
  src/app/frontend/common/components/card/template.html
  src/app/frontend/common/components/module.ts
  src/app/frontend/common/components/resourcelist/pod/template.html
  src/app/frontend/common/components/sparkline/cpu/component.ts
  src/app/frontend/common/components/sparkline/cpu/style.scss
  src/app/frontend/common/components/sparkline/cpu/template.html
  src/app/frontend/common/components/sparkline/memory/component.ts
  src/app/frontend/common/components/sparkline/memory/style.scss
  src/app/frontend/common/components/sparkline/memory/template.html
  src/app/frontend/common/components/sparkline/sparkline.ts
  src/app/frontend/common/components/sparkline/template.html
  src/app/frontend/common/pipes/coreformatter.ts
  src/app/frontend/common/pipes/memoryformatter.ts
  src/app/frontend/common/pipes/module.ts
  src/app/frontend/index.html
  src/app/frontend/index.module.ts
  src/app/frontend/overview/component.ts
  src/app/frontend/overview/template.html
  src/app/frontend/overview/workloadstatus/template.html
Labels: approved, cncf-cla: yes, lgtm, size/XL

#3954 Update copyRightYear to 2019
  src/app/frontend/about/component.spec.ts
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3965 Regen package-lock.json
  package-lock.json
Labels: approved, cncf-cla: yes, lgtm, size/L

#3960 Fix remote sidecar url
  src/app/backend/integration/metric/sidecar/client.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3959 Breadcrumbs are missing after page refresh
  src/app/frontend/common/components/breadcrumbs/component.ts
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3979 Greenkeeper/xterm 3.14.4
  package-lock.json
  package.json
Labels: approved, cncf-cla: no, do-not-merge/invalid-commit-message, size/XS

#3971 Add `i18n` tasks
  aio/develop/Dockerfile
  aio/scripts/pre-commit-i18n.sh
  i18n/messages.xlf
  package.json
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#3984 Greenkeeper/@angular devkit/build angular 0.800.6
  package-lock.json
  package.json
Labels: approved, cncf-cla: no, do-not-merge/invalid-commit-message, size/L

#3969 Add `insecure-bind-address` option for `npm run start:prod`
  .npmrc
  aio/develop/npm-command.sh
  aio/develop/run-npm-on-container.sh
  package.json
Labels: approved, cncf-cla: yes, lgtm, size/S

#3975 Japanese translation
  i18n/locale_conf.json
  i18n/messages.ja.xlf
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#3980 Switch user in container for development
  aio/develop/Dockerfile
  aio/develop/gosu-command.sh
  aio/develop/npm-command.sh
  aio/develop/run-npm-on-container.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#3986 Reload logs and shell on container change
  src/app/frontend/chrome/routing.ts
  src/app/frontend/index.module.ts
  src/app/frontend/index.routing.ts
  src/app/frontend/logs/component.ts
  src/app/frontend/shell/component.ts
Labels: approved, cncf-cla: yes, lgtm, size/L
