Repository kubernetes/dashboard, pull requests merged in 2019-03, with the labels that each got.

#3610 toggle selected mode
  src/app/frontend/common/dialogs/editresource/dialog.ts
  src/app/frontend/common/dialogs/editresource/template.html
Labels: approved, cncf-cla: yes, lgtm, size/S

#3635 Greenkeeper/@types/node 11.10.5
  package-lock.json
  package.json
Labels: approved, cncf-cla: no, size/XS

#3143 Update to build and push multi-arch manifests
  .travis.yml
  aio/gulp/backend.js
  aio/gulp/conf.js
  aio/gulp/deploy.js
  package.json
Labels: approved, cncf-cla: yes, lgtm, size/L

#3640 Update embargo doc link in SECURITY_OWNERS and change PST to PSC
  SECURITY_CONTACTS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3644 Greenkeeper/@types/node 11.11.0
  package-lock.json
  package.json
Labels: approved, cncf-cla: no, size/XS

#3646 removed i18n directory
  i18n/messages-ko.xtb
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#3659 Greenkeeper/@types/node 11.11.3
  package-lock.json
  package.json
Labels: approved, cncf-cla: no, size/XS

#3668 revert mistake from #3657
  package-lock.json
  package.json
Labels: approved, cncf-cla: yes, size/L

#3666 fix property error in ReplicationControllerListComponent template
  src/app/frontend/common/components/resourcelist/replicationcontroller/template.html
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3676 Remove `golangci-lint` temporarily from `lint-staged`
  package.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3630 Replace history when the log page appends container param
  src/app/frontend/logs/component.ts
Labels: approved, cncf-cla: yes, lgtm, size/XS

#3679 Cleanup travis environment
  .travis.yml
  aio/scripts/conf.sh
  aio/scripts/lint-backend.sh
  package.json
  src/app/backend/resource/deployment/detail_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#3691 Greenkeeper/@types/node 11.11.6
  package-lock.json
  package.json
Labels: cncf-cla: no

#3706 Greenkeeper/@types/node 11.12.2
  package-lock.json
  package.json
Labels: approved, cncf-cla: no, size/XS
