Repository kubernetes/dashboard, pull requests merged in 2020-11, with the labels that each got.

#5673 Chinese translation update
  i18n/zh-Hans/messages.zh-Hans.xlf
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/M

#5676 fix code style
  src/app/backend/handler/apihandler.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5680 Bump k8s modules to 0.19.3
  aio/scripts/conf.sh
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/L

#5681 Remove unnecessary return
  src/app/backend/handler/download.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5685 Bump k8s modules to 1.19.4
  aio/scripts/conf.sh
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/M

#5687 Bump actions/setup-node to v2.1.2
  .github/workflows/cd-workflow.yml
  .github/workflows/ci-license-workflow.yml
  .github/workflows/ci-workflow.yml
Labels: approved, cncf-cla: yes, lgtm, size/S

#5666 Update helm stable repo
  .github/workflows/ci-helm-workflow.yml
  aio/deploy/helm-chart/.helm-chart-testing.yaml
  aio/deploy/helm-chart/kubernetes-dashboard/Chart.yaml
  aio/deploy/helm-chart/kubernetes-dashboard/requirements.lock
  aio/deploy/helm-chart/kubernetes-dashboard/requirements.yaml
  aio/scripts/helm-release-chart.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#5684 update zh translation
  i18n/zh-Hans/messages.zh-Hans.xlf
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/M

#5691 Helm Chart: Fix chart-testing, upgrade ingress to networking.k8s.io/v1beta1, set metrics-provider=none if metrics scraper is not enabled.
  .github/workflows/ci-helm-workflow.yml
  aio/deploy/helm-chart/kubernetes-dashboard/Chart.yaml
  aio/deploy/helm-chart/kubernetes-dashboard/README.md
  aio/deploy/helm-chart/kubernetes-dashboard/templates/deployment.yaml
  aio/deploy/helm-chart/kubernetes-dashboard/templates/ingress.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#5693 Add change language option.
  aio/scripts/build.sh
  angular.json
  i18n/de/messages.de.xlf
  i18n/fr/messages.fr.xlf
  i18n/ja/messages.ja.xlf
  i18n/ko/messages.ko.xlf
  i18n/messages.xlf
  i18n/zh-Hans/messages.zh-Hans.xlf
  i18n/zh-Hant-HK/messages.zh-Hant-HK.xlf
  i18n/zh-Hant/messages.zh-Hant.xlf
  src/app/backend/handler/localehandler.go
  src/app/frontend/common/components/namespace/component.ts
  src/app/frontend/common/services/global/authentication.ts
  src/app/frontend/common/services/global/interceptor.ts
  src/app/frontend/common/services/global/namespace.ts
  src/app/frontend/create/from/form/createnamespace/dialog.ts
  src/app/frontend/create/from/form/createsecret/dialog.ts
  src/app/frontend/index.config.ts
  src/app/frontend/settings/local/component.ts
  src/app/frontend/settings/local/template.html
  src/app/frontend/typings/frontendapi.ts
Labels: approved, cncf-cla: yes, language/de, language/fr, language/ja, language/ko, language/zh, lgtm, size/L

#5672 Update German translation.
  i18n/de/messages.de.xlf
Labels: approved, cncf-cla: yes, language/de, lgtm, size/M

#5694 add test intro for i18n
  docs/developer/getting-started.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#5696 add france for language selector
  src/app/frontend/index.config.ts
Labels: approved, cncf-cla: yes, lgtm, size/XS
