Repository kubernetes/dashboard, pull requests merged in 2020-09, with the labels that each got.

#5497 Update core modules to v1.19 and Go to v1.15
  .github/workflows/cd-workflow.yml
  .github/workflows/ci-license-workflow.yml
  .github/workflows/ci-workflow.yml
  .golangci.yml
  aio/develop/Dockerfile
  docs/developer/getting-started.md
  go.mod
  go.sum
  package.json
Labels: approved, cncf-cla: yes, size/L

#5498 Bump version to 2.0.4
  README.md
  aio/deploy/alternative.yaml
  aio/deploy/alternative/06_dashboard-deployment.yaml
  aio/deploy/recommended.yaml
  aio/deploy/recommended/06_dashboard-deployment.yaml
  aio/gulp/conf.js
  docs/user/installation.md
  package-lock.json
  package.json
Labels: approved, cncf-cla: yes, size/S

#5513 cleaning up sample user creation
  docs/user/access-control/creating-sample-user.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#5508 add dashboard settings config in the helm chart
  aio/deploy/helm-chart/kubernetes-dashboard/Chart.yaml
  aio/deploy/helm-chart/kubernetes-dashboard/README.md
  aio/deploy/helm-chart/kubernetes-dashboard/ci/settings-values.yaml
  aio/deploy/helm-chart/kubernetes-dashboard/templates/configmap.yaml
  aio/deploy/helm-chart/kubernetes-dashboard/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#5525 Helm Chart: Add options for extraVolumes and extraVolumeMounts
  aio/deploy/helm-chart/kubernetes-dashboard/Chart.yaml
  aio/deploy/helm-chart/kubernetes-dashboard/README.md
  aio/deploy/helm-chart/kubernetes-dashboard/templates/deployment.yaml
  aio/deploy/helm-chart/kubernetes-dashboard/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#5526 Update dependencies
  go.mod
  go.sum
  i18n/de/messages.de.xlf
  i18n/fr/messages.fr.xlf
  i18n/ja/messages.ja.xlf
  i18n/ko/messages.ko.xlf
  i18n/messages.xlf
  i18n/zh-Hans/messages.zh-Hans.xlf
  i18n/zh-Hant-HK/messages.zh-Hant-HK.xlf
  i18n/zh-Hant/messages.zh-Hant.xlf
  package-lock.json
  package.json
  src/app/frontend/common/components/resourcelist/crdobject/template.html
  src/app/frontend/common/components/resourcelist/pod/template.html
  src/app/frontend/common/components/zerostate/template.html
Labels: approved, cncf-cla: yes, language/de, language/fr, language/ja, language/ko, language/zh, size/XXL

#5530 fix: convert dashboard settings configmap to string of json instead of yaml
  aio/deploy/helm-chart/kubernetes-dashboard/Chart.yaml
  aio/deploy/helm-chart/kubernetes-dashboard/templates/configmap.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5529 Move local settings from cookies to local storage
  src/app/frontend/common/services/global/localsettings.ts
Labels: approved, cncf-cla: yes, size/XS

#5516 Helm Chart CD: do not change creation date of existing chart versions
  aio/scripts/helm-release-chart.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#5444 Helm chart: Add option to enable a Pod Security Policy
  aio/deploy/helm-chart/kubernetes-dashboard/Chart.yaml
  aio/deploy/helm-chart/kubernetes-dashboard/README.md
  aio/deploy/helm-chart/kubernetes-dashboard/ci/podsecurity-policy-values.yaml
  aio/deploy/helm-chart/kubernetes-dashboard/templates/psp.yaml
  aio/deploy/helm-chart/kubernetes-dashboard/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#5517 Helm chart: Update dashboard to 2.0.4.
  aio/deploy/helm-chart/kubernetes-dashboard/Chart.yaml
  aio/deploy/helm-chart/kubernetes-dashboard/README.md
  aio/deploy/helm-chart/kubernetes-dashboard/values.yaml
Labels: approved, cncf-cla: yes, size/XS

#5550 Trim login token input and clean up go.mod
  go.mod
  go.sum
  src/app/frontend/login/component.ts
Labels: approved, cncf-cla: yes, lgtm, size/M

#5551 Fix menu and card paddings
  i18n/de/messages.de.xlf
  i18n/fr/messages.fr.xlf
  i18n/ja/messages.ja.xlf
  i18n/ko/messages.ko.xlf
  i18n/messages.xlf
  i18n/zh-Hans/messages.zh-Hans.xlf
  i18n/zh-Hant-HK/messages.zh-Hant-HK.xlf
  i18n/zh-Hant/messages.zh-Hant.xlf
  src/app/frontend/_variables.scss
  src/app/frontend/chrome/nav/item/style.scss
  src/app/frontend/chrome/nav/style.scss
  src/app/frontend/chrome/nav/template.html
  src/app/frontend/chrome/style.scss
  src/app/frontend/index.scss
Labels: approved, cncf-cla: yes, language/de, language/fr, language/ja, language/ko, language/zh, lgtm, size/XXL

#5560 Update Japanese translations
  i18n/ja/messages.ja.xlf
Labels: approved, cncf-cla: yes, language/ja, lgtm, size/L

#5561 Update dashboard-arguments.md
  docs/common/dashboard-arguments.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5576 Helm support for pinned CRDs
  aio/deploy/helm-chart/kubernetes-dashboard/Chart.yaml
  aio/deploy/helm-chart/kubernetes-dashboard/README.md
  aio/deploy/helm-chart/kubernetes-dashboard/templates/configmap.yaml
  aio/deploy/helm-chart/kubernetes-dashboard/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S
