Repository kubernetes/dashboard, pull requests merged in 2020-03, with the labels that each got.

#4918 Add approvers for 'de' translations.
  i18n/de/OWNERS
Labels: approved, cncf-cla: yes, language/de, lgtm, size/XS

#4979 Fix go.sum for k8s.io/code-generator
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/S

#4980 Fix line graph width
  package-lock.json
  package.json
  src/app/frontend/common/components/graphcard/template.html
  src/app/frontend/common/components/graphmetrics/component.ts
  src/app/frontend/common/components/graphmetrics/style.scss
  src/app/frontend/common/components/graphmetrics/template.html
Labels: approved, cncf-cla: yes, lgtm, size/L

#5002 Fix create form
  src/app/backend/client/manager.go
  src/app/backend/resource/deployment/deploy.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#5003 Disable Angular analytics
  angular.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5000 Hide area under zero in graph
  src/app/frontend/common/components/graph/component.ts
  src/app/frontend/common/components/graph/template.html
Labels: approved, cncf-cla: yes, lgtm, size/S

#5007 Bump version to v2.0.0-rc6
  README.md
  aio/deploy/alternative.yaml
  aio/deploy/alternative/06_dashboard-deployment.yaml
  aio/deploy/recommended.yaml
  aio/deploy/recommended/06_dashboard-deployment.yaml
  aio/gulp/conf.js
  docs/user/installation.md
  package-lock.json
  package.json
Labels: approved, cncf-cla: yes, lgtm, size/S

#5010 update service list to show correct "success" status for "ExternalName"
  src/app/backend/resource/service/list.go
  src/app/frontend/common/components/resourcelist/service/component.ts
Labels: cncf-cla: yes, size/M

#5013 Set MinVersion for TLS
  src/app/backend/dashboard.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5004 Add option to disable access denied notifications
  i18n/de/messages.de.xlf
  i18n/fr/messages.fr.xlf
  i18n/ja/messages.ja.xlf
  i18n/ko/messages.ko.xlf
  i18n/messages.xlf
  i18n/zh-Hans-SG/messages.zh-Hans-SG.xlf
  i18n/zh-Hans/messages.zh-Hans.xlf
  i18n/zh-Hant-HK/messages.zh-Hant-HK.xlf
  i18n/zh-Hant/messages.zh-Hant.xlf
  i18n/zh/messages.zh.xlf
  src/app/backend/settings/api/types.go
  src/app/backend/settings/handler.go
  src/app/frontend/chrome/notifications/component.ts
  src/app/frontend/common/components/namespace/component.ts
  src/app/frontend/common/services/global/globalsettings.ts
  src/app/frontend/common/services/global/notifications.ts
  src/app/frontend/index.scss
  src/app/frontend/settings/global/component.ts
  src/app/frontend/settings/global/style.scss
  src/app/frontend/settings/global/template.html
  src/app/frontend/typings/backendapi.ts
Labels: approved, cncf-cla: yes, language/de, language/fr, language/ja, language/ko, language/zh, lgtm, size/L

#5016 Fix CRD details switch
  i18n/de/messages.de.xlf
  i18n/fr/messages.fr.xlf
  i18n/ja/messages.ja.xlf
  i18n/ko/messages.ko.xlf
  i18n/messages.xlf
  i18n/zh-Hans-SG/messages.zh-Hans-SG.xlf
  i18n/zh-Hans/messages.zh-Hans.xlf
  i18n/zh-Hant-HK/messages.zh-Hant-HK.xlf
  i18n/zh-Hant/messages.zh-Hant.xlf
  i18n/zh/messages.zh.xlf
  src/app/backend/settings/api/types.go
  src/app/frontend/chrome/nav/pinner/template.html
  src/app/frontend/common/components/actionbar/detailactions/pin/component.ts
  src/app/frontend/common/components/list/column/component.ts
  src/app/frontend/common/components/list/column/menu/component.ts
  src/app/frontend/common/components/resourcelist/crdobject/component.ts
  src/app/frontend/common/resources/list.ts
  src/app/frontend/common/services/global/pinner.ts
  src/app/frontend/crd/detail/component.ts
  src/app/frontend/crd/detail/template.html
  src/app/frontend/typings/backendapi.ts
  src/app/frontend/typings/frontendapi.ts
Labels: approved, cncf-cla: yes, language/de, language/fr, language/ja, language/ko, language/zh, lgtm, size/L

#5020 Update German translation
  i18n/de/messages.de.xlf
Labels: approved, cncf-cla: yes, language/de, lgtm, size/XS

#5022 Fix deploying Dashboard on a sub-paths
  angular.json
Labels: approved, cncf-cla: yes, lgtm, size/S

#5024 update translation
  i18n/zh-Hans-SG/messages.zh-Hans-SG.xlf
  i18n/zh-Hans/messages.zh-Hans.xlf
  i18n/zh-Hant-HK/messages.zh-Hant-HK.xlf
  i18n/zh-Hant/messages.zh-Hant.xlf
  i18n/zh/messages.zh.xlf
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/S

#5023 Update Japanese translation
  i18n/ja/messages.ja.xlf
Labels: approved, cncf-cla: yes, language/ja, lgtm, size/S

#5025 fix some zh translate
  i18n/zh/messages.zh.xlf
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/M

#5029 Update Korean translation
  i18n/ko/messages.ko.xlf
Labels: approved, cncf-cla: yes, language/ko, lgtm, size/XS

#5030 Autofocus filter input
  i18n/de/messages.de.xlf
  i18n/fr/messages.fr.xlf
  i18n/ja/messages.ja.xlf
  i18n/ko/messages.ko.xlf
  i18n/messages.xlf
  i18n/zh-Hans-SG/messages.zh-Hans-SG.xlf
  i18n/zh-Hans/messages.zh-Hans.xlf
  i18n/zh-Hant-HK/messages.zh-Hant-HK.xlf
  i18n/zh-Hant/messages.zh-Hant.xlf
  i18n/zh/messages.zh.xlf
  src/app/frontend/common/components/list/filter/component.ts
  src/app/frontend/common/components/list/filter/template.html
  src/app/frontend/common/components/module.ts
  src/app/frontend/common/directives/autofocus/directive.ts
  src/app/frontend/common/directives/module.ts
Labels: approved, cncf-cla: yes, language/de, language/fr, language/ja, language/ko, language/zh, lgtm, size/L

#5033 Fix deply redirect and error messages
  src/app/frontend/common/errors/errors.ts
  src/app/frontend/common/services/create/service.ts
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5041 FR Translations
  i18n/fr/messages.fr.xlf
Labels: approved, cncf-cla: yes, language/fr, lgtm, size/XS

#5042 v2.0.0-rc7
  README.md
  aio/deploy/alternative.yaml
  aio/deploy/alternative/06_dashboard-deployment.yaml
  aio/deploy/alternative/08_scraper-deployment.yaml
  aio/deploy/recommended.yaml
  aio/deploy/recommended/06_dashboard-deployment.yaml
  aio/deploy/recommended/08_scraper-deployment.yaml
  aio/gulp/conf.js
  docs/user/installation.md
  package-lock.json
  package.json
Labels: approved, cncf-cla: yes, lgtm, size/M
