Repository kubernetes/dashboard, pull requests merged in 2020-06, with the labels that each got.

#4502 Add Helm Chart
  .travis.yml
  aio/deploy/helm-chart/kubernetes-dashboard/.helmignore
  aio/deploy/helm-chart/kubernetes-dashboard/Chart.yaml
  aio/deploy/helm-chart/kubernetes-dashboard/OWNERS
  aio/deploy/helm-chart/kubernetes-dashboard/README.md
  aio/deploy/helm-chart/kubernetes-dashboard/ci/default-values.yaml
  aio/deploy/helm-chart/kubernetes-dashboard/ci/ingress-values.yaml
  aio/deploy/helm-chart/kubernetes-dashboard/ci/metrics-scraper-values.yaml
  aio/deploy/helm-chart/kubernetes-dashboard/ci/network-policy-values.yaml
  aio/deploy/helm-chart/kubernetes-dashboard/ci/pdb-values.yaml
  aio/deploy/helm-chart/kubernetes-dashboard/ci/rbac-cluster-readonly-role-values.yaml
  aio/deploy/helm-chart/kubernetes-dashboard/requirements.lock
  aio/deploy/helm-chart/kubernetes-dashboard/requirements.yaml
  aio/deploy/helm-chart/kubernetes-dashboard/templates/NOTES.txt
  aio/deploy/helm-chart/kubernetes-dashboard/templates/_helpers.tpl
  aio/deploy/helm-chart/kubernetes-dashboard/templates/clusterrole-metrics.yaml
  aio/deploy/helm-chart/kubernetes-dashboard/templates/clusterrole-readonly.yaml
  aio/deploy/helm-chart/kubernetes-dashboard/templates/clusterrolebinding-metrics.yaml
  aio/deploy/helm-chart/kubernetes-dashboard/templates/clusterrolebinding-readonly.yaml
  aio/deploy/helm-chart/kubernetes-dashboard/templates/deployment.yaml
  aio/deploy/helm-chart/kubernetes-dashboard/templates/ingress.yaml
  aio/deploy/helm-chart/kubernetes-dashboard/templates/networkpolicy.yaml
  aio/deploy/helm-chart/kubernetes-dashboard/templates/pdb.yaml
  aio/deploy/helm-chart/kubernetes-dashboard/templates/role.yaml
  aio/deploy/helm-chart/kubernetes-dashboard/templates/rolebinding.yaml
  aio/deploy/helm-chart/kubernetes-dashboard/templates/secret.yaml
  aio/deploy/helm-chart/kubernetes-dashboard/templates/service.yaml
  aio/deploy/helm-chart/kubernetes-dashboard/templates/serviceaccount.yaml
  aio/deploy/helm-chart/kubernetes-dashboard/values.yaml
  aio/scripts/helm-lint.sh
  aio/scripts/helm-release-chart.sh
  docs/developer/release-procedures.md
  license-checker-config.json
Labels: cncf-cla: yes, size/XXL

#4742 Dashboard fix pod status
  src/app/backend/resource/common/resourcestatus.go
  src/app/backend/resource/pod/common.go
Labels: approved, cncf-cla: yes, lgtm, lifecycle/frozen, size/S

#5215 Add condition to job status return in backend
  src/app/backend/resource/job/list.go
  src/app/backend/resource/job/list_test.go
  src/app/frontend/resource/workloads/job/detail/template.html
  src/app/frontend/typings/backendapi.ts
Labels: approved, cncf-cla: yes, lgtm, size/M

#5246 Save login mode into cookie
  src/app/frontend/index.config.ts
  src/app/frontend/login/component.spec.ts
  src/app/frontend/login/component.ts
Labels: approved, cncf-cla: yes, lgtm, size/M

#5257 Update German translations.
  i18n/de/messages.de.xlf
Labels: approved, cncf-cla: yes, language/de, lgtm, size/S

#5269 README.md section 'Upgrade from 1.x.x to 2.x.x' enableSkipLogin and e…
  aio/deploy/helm-chart/kubernetes-dashboard/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5263 Helm Chart: Document alternate install method using Helm + improve helm chart readme
  README.md
  aio/deploy/helm-chart/kubernetes-dashboard/README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#5256 [handler] log the real client address
  src/app/backend/handler/filter.go
Labels: approved, cncf-cla: yes, size/M

#5250 Move namespace selector
  i18n/de/messages.de.xlf
  i18n/fr/messages.fr.xlf
  i18n/ja/messages.ja.xlf
  i18n/ko/messages.ko.xlf
  i18n/messages.xlf
  i18n/zh-Hans/messages.zh-Hans.xlf
  i18n/zh-Hant-HK/messages.zh-Hant-HK.xlf
  i18n/zh-Hant/messages.zh-Hant.xlf
  license-checker-config.json
  package.json
  src/app/backend/settings/api/types.go
  src/app/frontend/_theming.scss
  src/app/frontend/_variables.scss
  src/app/frontend/chrome/nav/component.ts
  src/app/frontend/chrome/nav/item/component.ts
  src/app/frontend/chrome/nav/item/style.scss
  src/app/frontend/chrome/nav/item/template.html
  src/app/frontend/chrome/nav/pinner/template.html
  src/app/frontend/chrome/nav/style.scss
  src/app/frontend/chrome/nav/template.html
  src/app/frontend/chrome/template.html
  src/app/frontend/chrome/userpanel/style.scss
  src/app/frontend/chrome/userpanel/template.html
  src/app/frontend/common/components/actionbar/detailactions/pin/component.ts
  src/app/frontend/common/components/actionbars/pindefault/template.html
  src/app/frontend/common/components/list/column/component.ts
  src/app/frontend/common/components/list/column/menu/component.ts
  src/app/frontend/common/components/namespace/style.scss
  src/app/frontend/common/components/namespace/template.html
  src/app/frontend/common/services/global/actionbar.ts
  src/app/frontend/common/services/global/pinner.ts
  src/app/frontend/crd/detail/component.ts
  src/app/frontend/typings/backendapi.ts
  src/app/frontend/typings/frontendapi.ts
Labels: approved, cncf-cla: yes, language/de, language/fr, language/ja, language/ko, language/zh, size/XXL

#5279 Fix E2E
  aio/scripts/coverage-backend.sh
  cypress/integration/specs/nav.spec.ts
  src/app/backend/client/verber_test.go
  src/app/backend/integration/manager_test.go
  src/app/backend/integration/metric/heapster/client_test.go
  src/app/backend/integration/metric/sidecar/client_test.go
Labels: approved, cncf-cla: yes, size/M

#5281 Remove Travis in favor of Github Workflows
  .travis.yml
Labels: approved, cncf-cla: yes, lgtm, size/L

#5273 Bump k8s modules to 0.18.4
  aio/scripts/conf.sh
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, size/M

#5284 Move SA to the Cluster section
  package-lock.json
  package.json
  src/app/frontend/chrome/routing.ts
  src/app/frontend/resource/cluster/serviceaccount/detail/component.ts
  src/app/frontend/resource/cluster/serviceaccount/detail/template.html
  src/app/frontend/resource/cluster/serviceaccount/list/component.ts
  src/app/frontend/resource/cluster/serviceaccount/module.ts
  src/app/frontend/resource/cluster/serviceaccount/routing.ts
  src/app/frontend/resource/cluster/template.html
  src/app/frontend/resource/config/template.html
Labels: approved, cncf-cla: yes, size/XXL

#5285 Bump version to v2.0.2
  README.md
  aio/deploy/alternative.yaml
  aio/deploy/alternative/06_dashboard-deployment.yaml
  aio/deploy/helm-chart/kubernetes-dashboard/Chart.yaml
  aio/deploy/helm-chart/kubernetes-dashboard/README.md
  aio/deploy/helm-chart/kubernetes-dashboard/values.yaml
  aio/deploy/recommended.yaml
  aio/deploy/recommended/06_dashboard-deployment.yaml
  aio/gulp/conf.js
  docs/user/installation.md
  package-lock.json
  package.json
Labels: approved, cncf-cla: yes, size/S

#5287 Helm chart: fix link to access guide in README
  aio/deploy/helm-chart/kubernetes-dashboard/README.md
Labels: cncf-cla: yes, size/XS

#5292 Bump version to 2.0.3
  README.md
  aio/deploy/alternative.yaml
  aio/deploy/alternative/06_dashboard-deployment.yaml
  aio/deploy/helm-chart/kubernetes-dashboard/Chart.yaml
  aio/deploy/helm-chart/kubernetes-dashboard/README.md
  aio/deploy/helm-chart/kubernetes-dashboard/values.yaml
  aio/deploy/recommended.yaml
  aio/deploy/recommended/06_dashboard-deployment.yaml
  aio/gulp/conf.js
  docs/user/installation.md
  package.json
Labels: approved, cncf-cla: yes, size/S

#5297 styles: Turn off hover effects on disabled buttons
  src/app/frontend/_theming.scss
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5237 feat(aio/Dockerfile): Add nonroot user to final image
  aio/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/S

#5276 Adding override for ingress paths
  aio/deploy/helm-chart/kubernetes-dashboard/Chart.yaml
  aio/deploy/helm-chart/kubernetes-dashboard/README.md
  aio/deploy/helm-chart/kubernetes-dashboard/ci/ingress-customPaths-values.yaml
  aio/deploy/helm-chart/kubernetes-dashboard/templates/ingress.yaml
  aio/deploy/helm-chart/kubernetes-dashboard/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#5309 Update CI
  .github/workflows/cd-workflow.yml
  .github/workflows/ci-helm-workflow.yml
  .github/workflows/ci-license-workflow.yml
  .github/workflows/ci-workflow.yml
  aio/templates/header.txt
  aio/templates/header_html.txt
  docs/developer/code-conventions.md
  license-checker-config.json
Labels: approved, cncf-cla: yes, size/L

#5311 Helm Chart CD: create PR instead of trying to push to protected branch
  .github/workflows/cd-helm-workflow.yml
Labels: approved, cncf-cla: yes, lgtm, size/S

#5283 support loadBalancerIP in helm chart for service
  aio/deploy/helm-chart/kubernetes-dashboard/Chart.yaml
  aio/deploy/helm-chart/kubernetes-dashboard/README.md
  aio/deploy/helm-chart/kubernetes-dashboard/templates/service.yaml
  aio/deploy/helm-chart/kubernetes-dashboard/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS
