Repository kubernetes/dashboard, pull requests merged in 2020-10, with the labels that each got.

#5588 Update triage/support label references to kind/support
  .github/ISSUE_TEMPLATE/support.md
  docs/user/labels.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5593 Upgraded to a slightly newer kubernetesui/metrics-scraper
  aio/deploy/alternative.yaml
  aio/deploy/alternative/08_scraper-deployment.yaml
  aio/deploy/helm-chart/kubernetes-dashboard/Chart.yaml
  aio/deploy/helm-chart/kubernetes-dashboard/README.md
  aio/deploy/helm-chart/kubernetes-dashboard/values.yaml
  aio/deploy/recommended.yaml
  aio/deploy/recommended/08_scraper-deployment.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#5601 Bump golangci-lint to v1.30.0 for development container
  aio/develop/Dockerfile
Labels: approved, cncf-cla: yes, size/XS

#5602 Fix frontend tests
  src/app/frontend/about/component.spec.ts
  src/app/frontend/common/components/card/component.spec.ts
  src/app/frontend/common/components/graphcard/component.spec.ts
  src/app/frontend/common/components/objectmeta/component.spec.ts
  src/app/frontend/common/components/workloadstatus/component.spec.ts
  src/app/frontend/index.spec.ts
  src/app/frontend/login/component.spec.ts
  src/app/frontend/overview/component.spec.ts
  src/app/frontend/resource/discovery/ingress/detail/component.spec.ts
  src/app/frontend/resource/discovery/service/detail/component.spec.ts
Labels: approved, cncf-cla: yes, lgtm, size/XL

#5604 Show relative time for events
  i18n/de/messages.de.xlf
  i18n/fr/messages.fr.xlf
  i18n/ja/messages.ja.xlf
  i18n/ko/messages.ko.xlf
  i18n/messages.xlf
  i18n/zh-Hans/messages.zh-Hans.xlf
  i18n/zh-Hant-HK/messages.zh-Hant-HK.xlf
  i18n/zh-Hant/messages.zh-Hant.xlf
  src/app/frontend/common/components/resourcelist/event/template.html
Labels: approved, cncf-cla: yes, language/de, language/fr, language/ja, language/ko, language/zh, size/S

#5605 Remove use of awk and other awkward commands
  docs/user/access-control/creating-sample-user.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#5618 Revert "Remove use of awk and other awkward commands"
  docs/user/access-control/creating-sample-user.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#5615 Bump k8s modules to 0.19.2
  aio/scripts/conf.sh
  go.mod
  go.sum
  src/app/backend/plugin/client/clientset/versioned/fake/register.go
  src/app/backend/plugin/client/listers/apis/v1alpha1/plugin.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#5631 Update Korean translation
  i18n/ko/messages.ko.xlf
Labels: approved, cncf-cla: yes, language/ko, lgtm, size/L

#5636 Update dependencies and remove tslint leftovers
  angular.json
  cypress/support/commands.ts
  docs/developer/code-conventions.md
  package-lock.json
  package.json
  src/app/frontend/common/resources/resource.ts
  src/app/frontend/common/services/global/interceptor.ts
  src/app/frontend/index.spec.ts
  src/app/frontend/plugin/holder.ts
  src/app/frontend/polyfills.ts
  src/app/frontend/shell/component.ts
  src/app/frontend/systemjs.d.ts
  src/app/frontend/typings/backendapi.ts
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#5629 update chinese translation
  i18n/zh-Hans/messages.zh-Hans.xlf
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/L

#5652 Bump go-restful from v2 to v3
  go.mod
  go.sum
  src/app/backend/auth/handler.go
  src/app/backend/auth/handler_test.go
  src/app/backend/auth/manager_test.go
  src/app/backend/client/api/types.go
  src/app/backend/client/manager.go
  src/app/backend/client/manager_test.go
  src/app/backend/errors/handler.go
  src/app/backend/handler/apihandler.go
  src/app/backend/handler/apihandler_test.go
  src/app/backend/handler/download.go
  src/app/backend/handler/filter.go
  src/app/backend/handler/parser/parser.go
  src/app/backend/handler/terminal.go
  src/app/backend/integration/handler.go
  src/app/backend/integration/handler_test.go
  src/app/backend/integration/metric/heapster/selector.go
  src/app/backend/integration/metric/sidecar/selector.go
  src/app/backend/plugin/config.go
  src/app/backend/plugin/config_test.go
  src/app/backend/plugin/detail_test.go
  src/app/backend/plugin/handler.go
  src/app/backend/plugin/handler_test.go
  src/app/backend/plugin/list_test.go
  src/app/backend/settings/handler.go
  src/app/backend/settings/handler_test.go
  src/app/backend/systembanner/handler.go
  src/app/backend/validation/validateloginstatus.go
  src/app/backend/validation/validateloginstatus_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#5660 Sync pod status logic with kubectl and simplify API
  src/app/backend/resource/pod/common.go
  src/app/backend/resource/pod/common_test.go
  src/app/backend/resource/pod/detail.go
  src/app/backend/resource/pod/detail_test.go
  src/app/backend/resource/pod/list.go
  src/app/backend/resource/pod/list_test.go
  src/app/backend/resource/service/pods_test.go
  src/app/frontend/_theming.scss
  src/app/frontend/common/components/namespace/component.ts
  src/app/frontend/common/components/resourcelist/pod/component.ts
  src/app/frontend/common/resources/list.ts
  src/app/frontend/resource/discovery/service/detail/component.spec.ts
  src/app/frontend/typings/backendapi.ts
Labels: approved, cncf-cla: yes, lgtm, size/L

#5661 Bump go-restful to v3.3.3
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5663 Bump metrics to 1.0.6
  aio/deploy/alternative.yaml
  aio/deploy/alternative/08_scraper-deployment.yaml
  aio/deploy/helm-chart/kubernetes-dashboard/Chart.yaml
  aio/deploy/helm-chart/kubernetes-dashboard/README.md
  aio/deploy/helm-chart/kubernetes-dashboard/values.yaml
  aio/deploy/recommended.yaml
  aio/deploy/recommended/08_scraper-deployment.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S
