Repository kubernetes/dashboard, pull requests merged in 2020-05, with the labels that each got.

#5108 Do not crash chip dialog if the prettify function fails
  src/app/frontend/common/components/textinput/component.ts
Labels: approved, cncf-cla: yes, lgtm, size/S

#5109 Update empty list message for CRD object list
  i18n/de/messages.de.xlf
  i18n/fr/messages.fr.xlf
  i18n/ja/messages.ja.xlf
  i18n/ko/messages.ko.xlf
  i18n/messages.xlf
  i18n/zh-Hans/messages.zh-Hans.xlf
  i18n/zh-Hant-HK/messages.zh-Hant-HK.xlf
  i18n/zh-Hant/messages.zh-Hant.xlf
  src/app/frontend/common/components/list/zerostate/component.ts
  src/app/frontend/common/components/list/zerostate/template.html
  src/app/frontend/common/components/module.ts
  src/app/frontend/common/components/resourcelist/crdobject/component.ts
  src/app/frontend/common/components/resourcelist/crdobject/template.html
  src/app/frontend/crd/detail/component.ts
  src/app/frontend/crd/detail/template.html
Labels: approved, cncf-cla: yes, language/de, language/fr, language/ja, language/ko, language/zh, lgtm, size/L

#5115 Fix list default sort problem
  src/app/frontend/common/components/resourcelist/configmap/template.html
  src/app/frontend/common/components/resourcelist/crd/template.html
  src/app/frontend/common/components/resourcelist/crdobject/template.html
  src/app/frontend/common/components/resourcelist/cronjob/template.html
  src/app/frontend/common/components/resourcelist/daemonset/template.html
  src/app/frontend/common/components/resourcelist/deployment/template.html
  src/app/frontend/common/components/resourcelist/horizontalpodautoscaler/template.html
  src/app/frontend/common/components/resourcelist/ingress/template.html
  src/app/frontend/common/components/resourcelist/job/template.html
  src/app/frontend/common/components/resourcelist/persistentvolumeclaim/template.html
  src/app/frontend/common/components/resourcelist/plugin/template.html
  src/app/frontend/common/components/resourcelist/pod/template.html
  src/app/frontend/common/components/resourcelist/replicaset/template.html
  src/app/frontend/common/components/resourcelist/replicationcontroller/template.html
  src/app/frontend/common/components/resourcelist/secret/template.html
  src/app/frontend/common/components/resourcelist/service/template.html
  src/app/frontend/common/components/resourcelist/statefulset/template.html
Labels: approved, cncf-cla: yes, lgtm, size/M

#5107 Use Page Visibility API to stop background tasks when page is inactive
  i18n/de/messages.de.xlf
  i18n/fr/messages.fr.xlf
  i18n/ja/messages.ja.xlf
  i18n/ko/messages.ko.xlf
  i18n/messages.xlf
  i18n/zh-Hans/messages.zh-Hans.xlf
  i18n/zh-Hant-HK/messages.zh-Hant-HK.xlf
  i18n/zh-Hant/messages.zh-Hant.xlf
  package-lock.json
  package.json
  src/app/frontend/chrome/component.ts
  src/app/frontend/chrome/module.ts
  src/app/frontend/common/services/global/globalsettings.ts
  src/app/frontend/index.module.ts
  src/app/frontend/logs/component.ts
  src/app/frontend/logs/template.html
Labels: approved, cncf-cla: yes, language/de, language/fr, language/ja, language/ko, language/zh, lgtm, size/XXL

#5120 Fix ace editor config on a sub-paths
  src/app/frontend/common/components/textinput/component.ts
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5121 Disable sort by pod status
  i18n/de/messages.de.xlf
  i18n/fr/messages.fr.xlf
  i18n/ja/messages.ja.xlf
  i18n/ko/messages.ko.xlf
  i18n/messages.xlf
  i18n/zh-Hans/messages.zh-Hans.xlf
  i18n/zh-Hant-HK/messages.zh-Hant-HK.xlf
  i18n/zh-Hant/messages.zh-Hant.xlf
  src/app/backend/resource/pod/common.go
  src/app/frontend/common/components/resourcelist/pod/template.html
Labels: approved, cncf-cla: yes, language/de, language/fr, language/ja, language/ko, language/zh, lgtm, size/M

#5124 Detect insecure login
  docs/user/access-control/README.md
  docs/user/access-control/creating-sample-user.md
  docs/user/accessing-dashboard/1.6.x-and-below.md
  docs/user/accessing-dashboard/1.7.x-and-above.md
  docs/user/accessing-dashboard/README.md
  docs/user/images/dashboard-login-disabled.png
  docs/user/installation.md
  i18n/de/messages.de.xlf
  i18n/fr/messages.fr.xlf
  i18n/ja/messages.ja.xlf
  i18n/ko/messages.ko.xlf
  i18n/messages.xlf
  i18n/zh-Hans/messages.zh-Hans.xlf
  i18n/zh-Hant-HK/messages.zh-Hant-HK.xlf
  i18n/zh-Hant/messages.zh-Hant.xlf
  src/app/frontend/common/services/global/authentication.ts
  src/app/frontend/login/component.spec.ts
  src/app/frontend/login/component.ts
  src/app/frontend/login/template.html
Labels: approved, cncf-cla: yes, language/de, language/fr, language/ja, language/ko, language/zh, lgtm, size/XL

#5161 Fix card expand animation
  src/app/frontend/common/animations/animations.ts
  src/app/frontend/common/components/card/component.ts
  src/app/frontend/common/components/card/style.scss
  src/app/frontend/common/components/card/template.html
Labels: approved, cncf-cla: yes, lgtm, size/M

#5160 Fix cookie handling in Firefox when using HTTP
  aio/gulp/conf.js
  aio/gulp/serve.js
  src/app/frontend/common/services/global/authentication.ts
  src/app/frontend/login/component.spec.ts
  src/app/frontend/login/component.ts
Labels: approved, cncf-cla: yes, lgtm, size/L

#5162 Update dependencies and limit secret editor size
  i18n/de/messages.de.xlf
  i18n/fr/messages.fr.xlf
  i18n/ja/messages.ja.xlf
  i18n/ko/messages.ko.xlf
  i18n/messages.xlf
  i18n/zh-Hans/messages.zh-Hans.xlf
  i18n/zh-Hant-HK/messages.zh-Hant-HK.xlf
  i18n/zh-Hant/messages.zh-Hant.xlf
  package-lock.json
  package.json
  src/app/frontend/resource/config/secret/detail/edit/template.html
Labels: approved, cncf-cla: yes, language/de, language/fr, language/ja, language/ko, language/zh, lgtm, size/XXL

#5163 Update auto-logout and fix breadcrumbs console error
  aio/gulp/conf.js
  aio/gulp/serve.js
  src/app/frontend/common/components/breadcrumbs/component.ts
  src/app/frontend/error/handler.ts
Labels: approved, cncf-cla: yes, lgtm, size/S

#5164 Bump version to v2.0.1
  README.md
  aio/deploy/alternative.yaml
  aio/deploy/alternative/06_dashboard-deployment.yaml
  aio/deploy/recommended.yaml
  aio/deploy/recommended/06_dashboard-deployment.yaml
  aio/gulp/conf.js
  docs/user/installation.md
  package-lock.json
  package.json
Labels: approved, cncf-cla: yes, lgtm, size/S

#5168 :fire: dead link
  docs/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5173 Bump k8s modules to 0.18.3
  aio/scripts/conf.sh
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/M

#5174 Update Japanese translations
  i18n/ja/messages.ja.xlf
Labels: approved, cncf-cla: yes, language/ja, lgtm, size/S

#5179 update zh-hans translation
  i18n/zh-Hans/messages.zh-Hans.xlf
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/S

#5182 Fix can-i check for settings configmap
  src/app/backend/client/api/common.go
  src/app/backend/client/api/common_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#5198 Disable graph refresh when it is not visible
  package-lock.json
  package.json
  src/app/frontend/common/components/graph/component.ts
  src/app/frontend/common/components/graph/template.html
  src/app/frontend/shared.module.ts
  src/app/frontend/typings/frontendapi.ts
Labels: approved, cncf-cla: yes, lgtm, size/M

#5204 delete 。in chinese translation
  i18n/zh-Hans/messages.zh-Hans.xlf
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/XS

#5207 fix typo in german translation
  i18n/de/messages.de.xlf
Labels: approved, cncf-cla: yes, language/de, lgtm, size/XS
