Repository kubernetes/dashboard, pull requests merged in 2020-08, with the labels that each got.

#5393 Add repo SECURITY.md
  SECURITY.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#5407 Fix development container to pass correctly args to K8S_DASHBOARD_NPM_CMD
  aio/develop/run-npm-on-container.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5408 Replications Controllers → Replication Controllers
  src/app/frontend/common/components/resourcelist/replicationcontroller/template.html
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5439 feat:update the zh/trans
  i18n/zh-Hans/messages.zh-Hans.xlf
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/S

#5428 Support roles
  i18n/de/messages.de.xlf
  i18n/fr/messages.fr.xlf
  i18n/ja/messages.ja.xlf
  i18n/ko/messages.ko.xlf
  i18n/messages.xlf
  i18n/zh-Hans/messages.zh-Hans.xlf
  i18n/zh-Hant-HK/messages.zh-Hant-HK.xlf
  i18n/zh-Hant/messages.zh-Hant.xlf
  src/app/backend/api/types.go
  src/app/frontend/chrome/nav/template.html
  src/app/frontend/chrome/routing.ts
  src/app/frontend/common/components/module.ts
  src/app/frontend/common/components/policyrule/template.html
  src/app/frontend/common/components/resourcelist/groupids.ts
  src/app/frontend/common/components/resourcelist/role/component.ts
  src/app/frontend/common/components/resourcelist/role/template.html
  src/app/frontend/common/services/resource/endpoint.ts
  src/app/frontend/resource/cluster/role/detail/component.ts
  src/app/frontend/resource/cluster/role/detail/template.html
  src/app/frontend/resource/cluster/role/list/component.ts
  src/app/frontend/resource/cluster/role/module.ts
  src/app/frontend/resource/cluster/role/routing.ts
  src/app/frontend/typings/backendapi.ts
Labels: approved, cncf-cla: yes, language/de, language/fr, language/ja, language/ko, language/zh, lgtm, size/XXL

#5473 refresh the way to import rxjs operators and Subject.
  src/app/frontend/common/components/breadcrumbs/component.ts
  src/app/frontend/common/components/list/filter/component.ts
  src/app/frontend/common/components/namespace/component.ts
  src/app/frontend/common/resources/list.ts
  src/app/frontend/common/services/guard/auth.ts
Labels: approved, cncf-cla: yes, lgtm, size/M

#5477 Add setting for limit of displayed labels
  i18n/de/messages.de.xlf
  i18n/fr/messages.fr.xlf
  i18n/ja/messages.ja.xlf
  i18n/ko/messages.ko.xlf
  i18n/messages.xlf
  i18n/zh-Hans/messages.zh-Hans.xlf
  i18n/zh-Hant-HK/messages.zh-Hant-HK.xlf
  i18n/zh-Hant/messages.zh-Hant.xlf
  src/app/backend/settings/api/types.go
  src/app/frontend/common/components/chips/component.ts
  src/app/frontend/common/components/objectmeta/template.html
  src/app/frontend/common/services/global/globalsettings.ts
  src/app/frontend/resource/cluster/networkpolicy/detail/template.html
  src/app/frontend/resource/cluster/node/detail/template.html
  src/app/frontend/resource/cluster/persistentvolume/detail/source/template.html
  src/app/frontend/resource/cluster/persistentvolume/detail/template.html
  src/app/frontend/resource/config/persistentvolumeclaim/detail/template.html
  src/app/frontend/resource/discovery/service/detail/template.html
  src/app/frontend/resource/workloads/daemonset/detail/template.html
  src/app/frontend/resource/workloads/deployment/detail/template.html
  src/app/frontend/resource/workloads/job/detail/template.html
  src/app/frontend/resource/workloads/replicaset/detail/template.html
  src/app/frontend/resource/workloads/replicationcontroller/detail/template.html
  src/app/frontend/resource/workloads/statefulset/detail/template.html
  src/app/frontend/settings/global/component.ts
  src/app/frontend/settings/global/template.html
  src/app/frontend/typings/backendapi.ts
Labels: approved, cncf-cla: yes, language/de, language/fr, language/ja, language/ko, language/zh, lgtm, size/XXL

#5475 Fix style kubernetes/dashboard/README.md
  aio/deploy/helm-chart/kubernetes-dashboard/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS
