Repository kubernetes/dashboard, pull requests merged in 2020-01, with the labels that each got.

#4708 Update documents about greenkeeper in favor of dependabot
  docs/developer/dependency-management.md
  docs/user/labels.md
Labels: approved, cncf-cla: yes, size/XS

#4726 fix: node pie graphs to use consistent powers in divisor
  src/app/frontend/common/components/graph/helper.ts
  src/app/frontend/resource/cluster/node/detail/component.ts
Labels: approved, cncf-cla: yes, lgtm, size/S

#4698 fix bug for pod status in replicaSet
  src/app/backend/resource/replicaset/pods.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#4625 add hpa list and detail front-end
  i18n/fr/messages.fr.xlf
  i18n/ja/messages.ja.xlf
  i18n/ko/messages.ko.xlf
  i18n/messages.xlf
  i18n/zh/messages.zh.xlf
  src/app/backend/handler/apihandler.go
  src/app/backend/resource/horizontalpodautoscaler/list.go
  src/app/frontend/common/components/module.ts
  src/app/frontend/common/components/resourcelist/groupids.ts
  src/app/frontend/common/components/resourcelist/horizontalpodautoscaler/component.ts
  src/app/frontend/common/components/resourcelist/horizontalpodautoscaler/template.html
  src/app/frontend/common/services/resource/endpoint.ts
  src/app/frontend/resource/workloads/deployment/detail/component.ts
  src/app/frontend/resource/workloads/deployment/detail/template.html
Labels: approved, cncf-cla: yes, language/fr, language/ja, language/ko, language/zh, lgtm, size/L

#4746 Update version to 2.0.0-rc1
  README.md
  aio/deploy/alternative.yaml
  aio/deploy/alternative/06_dashboard-deployment.yaml
  aio/deploy/recommended.yaml
  aio/deploy/recommended/06_dashboard-deployment.yaml
  aio/gulp/conf.js
  docs/user/installation.md
  package.json
Labels: approved, cncf-cla: yes, lgtm, size/S

#4768 Fix version for kubernetesui/metrics-scraper image
  aio/deploy/recommended.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4776 Fix version for kubernetesui/metrics-scraper image
  aio/deploy/alternative.yaml
  aio/deploy/alternative/08_scraper-deployment.yaml
  aio/deploy/recommended/08_scraper-deployment.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4775 golangci-lint need to run against whole go files
  aio/develop/Dockerfile
  aio/scripts/pre-commit-golangci-lint.sh
  package.json
Labels: approved, cncf-cla: yes, lgtm, size/S

#4783 Change license check packages
  aio/develop/Dockerfile
  aio/develop/gosu-command.sh
  aio/develop/npm-command.sh
  aio/develop/run-npm-on-container.sh
  aio/gulp/check.js
  aio/karma-test-shim.js
  aio/scripts/license-header.txt
  aio/scripts/pre-commit-i18n.sh
  aio/scripts/xliffmerge.sh
  docs/developer/code-conventions.md
  gulpfile.babel.js
  license-checker-config.json
  package-lock.json
  package.json
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#4790 Remove chart animations
  i18n/fr/messages.fr.xlf
  i18n/ja/messages.ja.xlf
  i18n/ko/messages.ko.xlf
  i18n/messages.xlf
  i18n/zh/messages.zh.xlf
  src/app/frontend/common/components/workloadstatus/template.html
  src/app/frontend/resource/cluster/node/detail/template.html
Labels: approved, cncf-cla: yes, language/fr, language/ja, language/ko, language/zh, lgtm, size/L

#4791 Restore PVC list on pod details view
  i18n/fr/messages.fr.xlf
  i18n/ja/messages.ja.xlf
  i18n/ko/messages.ko.xlf
  i18n/messages.xlf
  i18n/zh/messages.zh.xlf
  package-lock.json
  package.json
  src/app/frontend/common/services/global/verber.ts
  src/app/frontend/resource/workloads/pod/detail/component.ts
  src/app/frontend/resource/workloads/pod/detail/template.html
Labels: approved, cncf-cla: yes, language/fr, language/ja, language/ko, language/zh, lgtm, size/XXL

#4792 Add additional locale directories for zh
  docs/developer/internationalization.md
  i18n/locale_conf.json
  i18n/zh-cn/OWNERS
  i18n/zh-cn/messages.zh-cn.xlf
  i18n/zh-hk/OWNERS
  i18n/zh-hk/messages.zh-hk.xlf
  i18n/zh-sg/OWNERS
  i18n/zh-sg/messages.zh-sg.xlf
  i18n/zh-tw/OWNERS
  i18n/zh-tw/messages.zh-tw.xlf
  package.json
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#4793 Update documentation
  README.md
  docs/common/faq.md
  docs/images/dashboard-ui.png
  docs/user/integrations.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#4794 Bump Dashboard to v2.0.0-rc2
  README.md
  aio/deploy/alternative.yaml
  aio/deploy/alternative/06_dashboard-deployment.yaml
  aio/deploy/recommended.yaml
  aio/deploy/recommended/06_dashboard-deployment.yaml
  aio/gulp/conf.js
  docs/user/installation.md
  package-lock.json
  package.json
Labels: approved, cncf-cla: yes, lgtm, size/S

#4796 update documentation for building on darwin
  docs/developer/getting-started.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4784 Update Japanese translation
  i18n/ja/README.md
  i18n/ja/messages.ja.xlf
Labels: approved, cncf-cla: yes, language/ja, lgtm, size/S

#4811 Add git dependance
  docs/developer/getting-started.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4816 add bc dependence
  docs/developer/getting-started.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4817 comment curl
  docs/developer/getting-started.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4819 Update Korean translation
  i18n/ko/OWNERS
  i18n/ko/messages.ko.xlf
Labels: approved, cncf-cla: yes, language/ko, lgtm, size/XS

#4813 Fix links in docs
  docs/common/faq.md
  docs/common/roadmap.md
  docs/developer/README.md
  docs/developer/code-conventions.md
  docs/user/integrations.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#4829 Update plugin codebases
  aio/scripts/update-codegen.sh
  src/app/backend/plugin/client/clientset/versioned/clientset.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#4825 Add chenrui333 to reviewer list
  i18n/zh-cn/OWNERS
  i18n/zh-hk/OWNERS
  i18n/zh-sg/OWNERS
  i18n/zh-tw/OWNERS
  i18n/zh/OWNERS
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/S

#4828 FR translations
  i18n/fr/messages.fr.xlf
Labels: approved, cncf-cla: yes, language/fr, lgtm, size/S

#4814 Support multi locales in one translation file
  .gitignore
  aio/scripts/build.sh
  aio/scripts/xliffmerge.sh
  docs/developer/internationalization.md
  i18n/zh-cn/messages.zh-cn.xlf
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/XXL

#4835 Fixes for graphs/firefox/configmap display
  aio/scripts/conf.sh
  aio/scripts/install-codegen.sh
  aio/scripts/update-codegen.sh
  go.mod
  go.sum
  package.json
  src/app/backend/client/verber_test.go
  src/app/backend/plugin/client/clientset/versioned/clientset.go
  src/app/frontend/common/components/graph/component.ts
  src/app/frontend/common/components/textinput/component.ts
  src/app/frontend/common/services/global/verber.ts
Labels: approved, cncf-cla: yes, lgtm, size/L

#4836 Bump version to v2.0.0-rc3
  README.md
  aio/deploy/alternative.yaml
  aio/deploy/alternative/06_dashboard-deployment.yaml
  aio/deploy/alternative/08_scraper-deployment.yaml
  aio/deploy/recommended.yaml
  aio/deploy/recommended/06_dashboard-deployment.yaml
  aio/deploy/recommended/08_scraper-deployment.yaml
  aio/gulp/conf.js
  docs/user/installation.md
  src/app/backend/client/verber_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L
