Repository kubernetes/dashboard, pull requests merged in 2020-07, with the labels that each got.

#5071 fix(code-style): polish the logs/logs.go
  src/app/backend/resource/logs/logs.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#5345 Remove missing link in `docs/user`
  docs/user/README.md
Labels: approved, cncf-cla: yes, size/XS

#5363 Add ability to define custom podLabels
  aio/deploy/helm-chart/kubernetes-dashboard/Chart.yaml
  aio/deploy/helm-chart/kubernetes-dashboard/README.md
  aio/deploy/helm-chart/kubernetes-dashboard/templates/deployment.yaml
  aio/deploy/helm-chart/kubernetes-dashboard/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5368 i18n: fix zh-hans translation of "Scale"
  i18n/zh-Hans/messages.zh-Hans.xlf
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/XS

#5359 Remove inactive members from OWNERS
  OWNERS_ALIASES
  ROLES.md
  SECURITY_CONTACTS
Labels: approved, cncf-cla: yes, lgtm, size/S

#5375 Allow getting node details without pod/event privileges
  src/app/backend/resource/event/common.go
  src/app/backend/resource/node/detail.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#5374 Bump Angular to v10
  package-lock.json
  package.json
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#5376 Update codecov config
  .codecov.yml
  .github/workflows/ci-workflow.yml
Labels: approved, cncf-cla: yes, size/M

#5383 Add value for cluster service label
  aio/deploy/helm-chart/kubernetes-dashboard/Chart.yaml
  aio/deploy/helm-chart/kubernetes-dashboard/README.md
  aio/deploy/helm-chart/kubernetes-dashboard/templates/service.yaml
  aio/deploy/helm-chart/kubernetes-dashboard/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S
