Repository kubernetes/dashboard, pull requests merged in 2021-06, with the labels that each got.

#6124 Ingress v1 2021
  src/app/backend/api/types.go
  src/app/backend/auth/manager_test.go
  src/app/backend/client/manager.go
  src/app/backend/client/verber.go
  src/app/backend/resource/ingress/common.go
  src/app/backend/resource/ingress/detail.go
  src/app/backend/resource/ingress/list.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#6142 Revert "Bump @angular-devkit/build-angular from 12.0.2 to 12.0.3"
  package-lock.json
  package.json
Labels: approved, cncf-cla: yes, do-not-merge/invalid-commit-message, size/L

#6144 fix how we display nfs mounts
  src/app/frontend/typings/volume.api.ts
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6143 Use valid YAML code for snippets
  docs/user/access-control/creating-sample-user.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6132 ingress ui shows service names and ports again (because of networking.k8s.io/v1)
  src/app/frontend/common/components/ingressrulelist/template.html
  src/app/frontend/resource/discovery/ingress/detail/component.spec.ts
  src/app/frontend/resource/discovery/ingress/detail/template.html
  src/app/frontend/typings/root.api.ts
Labels: approved, cncf-cla: yes, lgtm, size/M

#6145 Pod HealthCheck
  i18n/de/messages.de.xlf
  i18n/fr/messages.fr.xlf
  i18n/ja/messages.ja.xlf
  i18n/ko/messages.ko.xlf
  i18n/messages.xlf
  i18n/zh-Hans/messages.zh-Hans.xlf
  i18n/zh-Hant-HK/messages.zh-Hant-HK.xlf
  i18n/zh-Hant/messages.zh-Hant.xlf
  src/app/backend/resource/pod/detail.go
  src/app/frontend/common/components/container/template.html
  src/app/frontend/common/components/module.ts
  src/app/frontend/common/components/probe/component.ts
  src/app/frontend/common/components/probe/template.html
  src/app/frontend/typings/root.api.ts
Labels: approved, cncf-cla: yes, language/de, language/fr, language/ja, language/ko, language/zh, lgtm, size/XXL

#6155 Fix typo
  i18n/de/messages.de.xlf
  i18n/fr/messages.fr.xlf
  i18n/ja/messages.ja.xlf
  i18n/ko/messages.ko.xlf
  i18n/messages.xlf
  i18n/zh-Hans/messages.zh-Hans.xlf
  i18n/zh-Hant-HK/messages.zh-Hant-HK.xlf
  i18n/zh-Hant/messages.zh-Hant.xlf
  src/app/frontend/chrome/notifications/template.html
Labels: approved, cncf-cla: yes, language/de, language/fr, language/ja, language/ko, language/zh, lgtm, size/XL

#6156 Bump version to v2.3.0
  README.md
  aio/deploy/alternative.yaml
  aio/deploy/alternative/06_dashboard-deployment.yaml
  aio/deploy/recommended.yaml
  aio/deploy/recommended/06_dashboard-deployment.yaml
  aio/gulp/conf.js
  docs/user/installation.md
  package-lock.json
  package.json
Labels: approved, cncf-cla: yes, lgtm, size/S

#6158 Bump chart version after release
  aio/deploy/helm-chart/kubernetes-dashboard/Chart.yaml
  aio/deploy/helm-chart/kubernetes-dashboard/README.md
  aio/deploy/helm-chart/kubernetes-dashboard/values.yaml
Labels: approved, cncf-cla: yes, size/XS

#6162 Moving jeefy to emeritus
  OWNERS_ALIASES
  ROLES.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6163 metricsScraper use logrus instead of klog
  aio/deploy/helm-chart/kubernetes-dashboard/Chart.yaml
  aio/deploy/helm-chart/kubernetes-dashboard/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6166 Remove `highlight.js`
  angular.json
  package-lock.json
  package.json
  src/app/frontend/crd/crdobject/component.ts
Labels: approved, cncf-cla: yes, lgtm, size/L

#6177 Fix pod details page loading
  i18n/de/messages.de.xlf
  i18n/fr/messages.fr.xlf
  i18n/ja/messages.ja.xlf
  i18n/ko/messages.ko.xlf
  i18n/messages.xlf
  i18n/zh-Hans/messages.zh-Hans.xlf
  i18n/zh-Hant-HK/messages.zh-Hant-HK.xlf
  i18n/zh-Hant/messages.zh-Hant.xlf
  src/app/frontend/common/components/probe/component.ts
  src/app/frontend/common/components/probe/template.html
Labels: approved, cncf-cla: yes, language/de, language/fr, language/ja, language/ko, language/zh, lgtm, size/XL

#6178 Bump version to v2.3.1
  README.md
  aio/deploy/alternative.yaml
  aio/deploy/alternative/06_dashboard-deployment.yaml
  aio/deploy/recommended.yaml
  aio/deploy/recommended/06_dashboard-deployment.yaml
  aio/gulp/conf.js
  docs/user/installation.md
  package-lock.json
  package.json
Labels: approved, cncf-cla: yes, size/S

#6176 Add shu-mutou to leads
  OWNERS_ALIASES
  ROLES.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6179 Support more log options when downloading log file
  src/app/backend/handler/apihandler.go
  src/app/backend/resource/container/logs.go
  src/app/frontend/common/dialogs/download/dialog.ts
  src/app/frontend/typings/root.api.ts
Labels: approved, cncf-cla: yes, lgtm, size/M

#6184 Bump k8s modules to 0.21.2
  aio/scripts/conf.sh
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/L

#6183 i18n/de: remove leftover french from german i18n
  i18n/de/messages.de.xlf
Labels: approved, cncf-cla: yes, language/de, lgtm, size/XS

#6169 PersistentVolumeClaim details pane now shows a link to it's PersistVolume (if any)
  i18n/de/messages.de.xlf
  i18n/fr/messages.fr.xlf
  i18n/ja/messages.ja.xlf
  i18n/ko/messages.ko.xlf
  i18n/zh-Hans/messages.zh-Hans.xlf
  i18n/zh-Hant-HK/messages.zh-Hant-HK.xlf
  i18n/zh-Hant/messages.zh-Hant.xlf
  src/app/frontend/resource/config/persistentvolumeclaim/detail/component.ts
  src/app/frontend/resource/config/persistentvolumeclaim/detail/template.html
Labels: approved, cncf-cla: yes, language/de, language/fr, language/ja, language/ko, language/zh, lgtm, size/L

#6211 Bump angular staffs to 12.1.0
  package-lock.json
  package.json
Labels: approved, cncf-cla: yes, lgtm, size/XXL
