Repository kubernetes/dashboard, pull requests merged in 2021-09, with the labels that each got.

#6424 Bump angular staffs from 12.2.3 to 12.2.4.
  aio/scripts/conf.sh
  package-lock.json
  package.json
Labels: cncf-cla: yes, size/L, approved, lgtm

#6442 Bump angular staffs from 12.2.4 to 12.2.5
  package-lock.json
  package.json
Labels: cncf-cla: yes, size/XXL, approved, lgtm

#6465 Bump k8s modules to 0.22.2
  aio/scripts/conf.sh
  go.mod
  go.sum
Labels: cncf-cla: yes, size/M, approved, lgtm

#6464 Bump Angular staffs from 12.2.5 to 12.2.6.
  package-lock.json
  package.json
Labels: cncf-cla: yes, size/L, approved, lgtm

#6472 refactor: move from io/ioutil to io and os package
  src/app/backend/cert/ecdsa/creator.go
  src/app/backend/handler/filter.go
  src/app/backend/handler/localehandler.go
  src/app/backend/handler/localehandler_test.go
  src/app/backend/resource/container/logs.go
Labels: cncf-cla: yes, size/S, approved, lgtm

#6478 Bump angular staffs from 12.2.6 to 12.2.7.
  i18n/de/messages.de.xlf
  i18n/fr/messages.fr.xlf
  i18n/ja/messages.ja.xlf
  i18n/ko/messages.ko.xlf
  i18n/messages.xlf
  i18n/zh-Hans/messages.zh-Hans.xlf
  i18n/zh-Hant-HK/messages.zh-Hant-HK.xlf
  i18n/zh-Hant/messages.zh-Hant.xlf
  package-lock.json
  package.json
Labels: cncf-cla: yes, size/XXL, approved, lgtm, language/ja, language/zh, language/ko, language/fr, language/de
