Repository kubernetes/dashboard, pull requests merged in 2021-12, with the labels that each got.

#6642 Bump xterm to 4.15.0
  package-lock.json
  package.json
Labels: cncf-cla: yes, size/L, approved, lgtm

#6646 Update cypress configuration
  .gitignore
  Makefile
  aio/scripts/conf.sh
  aio/scripts/start-cluster.sh
  aio/tsconfig.e2e.json
  cypress.json
  cypress/integration/specs/nav.spec.ts
  cypress/pages/abstractPage.ts
  cypress/plugins/cy-ts-preprocessor.ts
  cypress/plugins/index.ts
  cypress/support/index.ts
  package-lock.json
  package.json
Labels: cncf-cla: yes, size/L, approved, lgtm

#6644 Add Restart action to Deployment details page
  i18n/de/messages.de.xlf
  i18n/fr/messages.fr.xlf
  i18n/ja/messages.ja.xlf
  i18n/ko/messages.ko.xlf
  i18n/messages.xlf
  i18n/zh-Hans/messages.zh-Hans.xlf
  i18n/zh-Hant-HK/messages.zh-Hant-HK.xlf
  i18n/zh-Hant/messages.zh-Hant.xlf
  src/app/backend/api/types.go
  src/app/backend/resource/deployment/detail_test.go
  src/app/backend/resource/deployment/list_test.go
  src/app/frontend/common/components/actionbar/detailactions/restart/component.ts
  src/app/frontend/common/components/actionbar/detailactions/restart/template.html
  src/app/frontend/common/components/actionbars/scaledefault/component.ts
  src/app/frontend/common/components/actionbars/scaledefault/template.html
  src/app/frontend/common/components/list/column/menu/component.ts
  src/app/frontend/common/components/module.ts
  src/app/frontend/typings/root.api.ts
Labels: cncf-cla: yes, size/XXL, approved, lgtm, language/ja, language/zh, language/ko, language/fr, language/de

#6651 docs: fix and update docs link
  docs/developer/code-conventions.md
  docs/developer/dependency-management.md
  docs/developer/getting-started.md
Labels: cncf-cla: yes, size/XS, approved, lgtm

#6567 Fix doc link to privileged mode containers in create from form
  src/app/frontend/create/from/form/template.html
Labels: cncf-cla: yes, size/XS, approved, lgtm

#6613 Grammar corrections for creating-sample-user
  docs/user/access-control/creating-sample-user.md
Labels: cncf-cla: yes, size/S

#6652 Fix npm start commands for development container
  .npmrc
  Makefile
  package.json
Labels: cncf-cla: yes, size/S, approved, lgtm

#6655 Fix air config
  .air.toml
Labels: cncf-cla: yes, size/XS, approved, lgtm

#6660 Fix container build (make docker-build-head)
  Makefile
Labels: cncf-cla: yes, size/XS, approved, lgtm

#6662 Fix dependencies
  i18n/de/messages.de.xlf
  i18n/fr/messages.fr.xlf
  i18n/ja/messages.ja.xlf
  i18n/ko/messages.ko.xlf
  i18n/messages.xlf
  i18n/zh-Hans/messages.zh-Hans.xlf
  i18n/zh-Hant-HK/messages.zh-Hant-HK.xlf
  i18n/zh-Hant/messages.zh-Hant.xlf
  package-lock.json
  package.json
Labels: cncf-cla: yes, size/XXL, approved, lgtm, language/ja, language/zh, language/ko, language/fr, language/de

#6667 Fix advanced settings button name on create form
  i18n/de/messages.de.xlf
  i18n/fr/messages.fr.xlf
  i18n/ja/messages.ja.xlf
  i18n/ko/messages.ko.xlf
  i18n/messages.xlf
  i18n/zh-Hans/messages.zh-Hans.xlf
  i18n/zh-Hant-HK/messages.zh-Hant-HK.xlf
  i18n/zh-Hant/messages.zh-Hant.xlf
  src/app/frontend/create/from/form/template.html
Labels: cncf-cla: yes, size/XXL, approved, lgtm, language/ja, language/zh, language/ko, language/fr, language/de

#6672 Bump k8s modules to 0.23.1
  Makefile
  aio/scripts/conf.sh
  go.mod
  go.sum
  src/app/backend/plugin/client/clientset/versioned/clientset.go
  src/app/backend/plugin/client/clientset/versioned/typed/apis/v1alpha1/apis_client.go
  src/app/backend/plugin/client/clientset/versioned/typed/apis/v1alpha1/fake/fake_plugin.go
Labels: cncf-cla: yes, size/L, approved, lgtm

#6647 Add settings defaulting and fix app initialization issue
  src/app/frontend/common/services/global/globalsettings.ts
  src/app/frontend/common/services/global/module.ts
  src/app/frontend/common/services/global/plugin.ts
Labels: cncf-cla: yes, size/M, approved, lgtm

#6664 migrate ingress from extensions/v1beta1 to networking/v1
  src/app/backend/auth/manager_test.go
  src/app/backend/client/manager.go
  src/app/backend/client/verber.go
  src/app/backend/client/verber_test.go
  src/app/backend/resource/common/resourcechannels.go
  src/app/backend/resource/customresourcedefinition/common.go
  src/app/backend/resource/customresourcedefinition/v1beta1/client.go
  src/app/backend/resource/customresourcedefinition/v1beta1/common.go
  src/app/backend/resource/customresourcedefinition/v1beta1/detail.go
  src/app/backend/resource/customresourcedefinition/v1beta1/list.go
  src/app/backend/resource/customresourcedefinition/v1beta1/list_test.go
  src/app/backend/resource/customresourcedefinition/v1beta1/objects.go
Labels: cncf-cla: yes, size/XL, approved, lgtm

#6657 Update multiarch docker build
  .github/workflows/cd-workflow.yml
  Makefile
  aio/Dockerfile
  aio/tsconfig.app.json
  aio/tsconfig.e2e.json
  aio/tsconfig.spec.json
  package-lock.json
  package.json
  src/app/frontend/common/services/global/history.ts
Labels: cncf-cla: yes, size/XL, approved, lgtm

#6678 remove duplicate metadata.annotation key from psp template in helm chart
  aio/deploy/helm-chart/kubernetes-dashboard/Chart.yaml
  aio/deploy/helm-chart/kubernetes-dashboard/templates/psp.yaml
Labels: cncf-cla: yes, size/XS, approved, lgtm
