Repository kubernetes/dashboard, pull requests merged in 2021-04, with the labels that each got.

#5931 Migrate from karma to jest
  aio/jest.config.js
  aio/karma.conf.js
  aio/tsconfig.app.json
  aio/tsconfig.spec.json
  angular.json
  package-lock.json
  package.json
  src/app/frontend/about/component.spec.ts
  src/app/frontend/common/components/graphcard/component.spec.ts
  src/app/frontend/common/components/objectmeta/component.spec.ts
  src/app/frontend/common/components/workloadstatus/component.spec.ts
  src/app/frontend/index.spec.ts
  src/app/frontend/login/component.spec.ts
  src/app/frontend/resource/discovery/ingress/detail/component.spec.ts
  src/app/frontend/resource/discovery/service/detail/component.spec.ts
  src/app/frontend/test.base.mocks.ts
  src/app/frontend/test.base.ts
  tsconfig.json
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#5950 Restrict npm version to v6
  .npmrc
  package.json
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5951 Update dependencies and fix audit issues
  i18n/de/messages.de.xlf
  i18n/fr/messages.fr.xlf
  i18n/ja/messages.ja.xlf
  i18n/ko/messages.ko.xlf
  i18n/messages.xlf
  i18n/zh-Hans/messages.zh-Hans.xlf
  i18n/zh-Hant-HK/messages.zh-Hant-HK.xlf
  i18n/zh-Hant/messages.zh-Hant.xlf
  package-lock.json
  package.json
Labels: approved, cncf-cla: yes, language/de, language/fr, language/ja, language/ko, language/zh, size/XXL

#5917 Implements rollout APIs for deployment
  i18n/de/messages.de.xlf
  i18n/fr/messages.fr.xlf
  i18n/ja/messages.ja.xlf
  i18n/ko/messages.ko.xlf
  i18n/messages.xlf
  i18n/zh-Hans/messages.zh-Hans.xlf
  i18n/zh-Hant-HK/messages.zh-Hant-HK.xlf
  i18n/zh-Hant/messages.zh-Hant.xlf
  src/app/backend/handler/apihandler.go
  src/app/backend/resource/deployment/rollout.go
  src/app/frontend/common/components/list/column/menu/component.ts
  src/app/frontend/common/components/list/column/menu/template.html
  src/app/frontend/common/dialogs/module.ts
  src/app/frontend/common/dialogs/restartresource/dialog.ts
  src/app/frontend/common/dialogs/restartresource/template.html
  src/app/frontend/common/services/global/verber.ts
Labels: approved, cncf-cla: yes, language/de, language/fr, language/ja, language/ko, language/zh, lgtm, size/XXL

#5965 Update Helm chart's TL;DR for Helm v3.
  aio/deploy/helm-chart/kubernetes-dashboard/Chart.yaml
  aio/deploy/helm-chart/kubernetes-dashboard/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5976 Bump k8s modules to 0.21.0
  aio/scripts/conf.sh
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/L

#5977 Update Japanese translation
  i18n/ja/messages.ja.xlf
Labels: approved, cncf-cla: yes, language/ja, lgtm, size/M

#5975 Fix ingress view and long container env variables display
  i18n/de/messages.de.xlf
  i18n/fr/messages.fr.xlf
  i18n/ja/messages.ja.xlf
  i18n/ko/messages.ko.xlf
  i18n/messages.xlf
  i18n/zh-Hans/messages.zh-Hans.xlf
  i18n/zh-Hant-HK/messages.zh-Hant-HK.xlf
  i18n/zh-Hant/messages.zh-Hant.xlf
  src/app/backend/resource/pod/detail.go
  src/app/frontend/common/components/condition/template.html
  src/app/frontend/common/components/container/component.ts
  src/app/frontend/common/components/container/style.scss
  src/app/frontend/common/components/container/template.html
  src/app/frontend/common/components/endpoint/cardlist/template.html
  src/app/frontend/common/components/endpoint/internal/style.scss
  src/app/frontend/common/components/ingressrulelist/component.ts
  src/app/frontend/common/components/ingressrulelist/template.html
  src/app/frontend/common/components/limits/template.html
  src/app/frontend/common/components/policyrule/template.html
  src/app/frontend/common/components/quotas/template.html
  src/app/frontend/common/components/resourcelist/crd/component.ts
  src/app/frontend/common/components/resourcelist/crdversion/template.html
  src/app/frontend/common/components/resourcelist/event/template.html
  src/app/frontend/common/components/resourcelist/horizontalpodautoscaler/template.html
  src/app/frontend/common/components/resourcelist/service/component.ts
  src/app/frontend/common/components/resourcelist/statuses.ts
  src/app/frontend/common/components/subject/template.html
  src/app/frontend/common/components/volumemount/template.html
  src/app/frontend/index.scss
  src/app/frontend/resource/cluster/persistentvolume/detail/template.html
  src/app/frontend/resource/workloads/job/detail/component.ts
  src/app/frontend/resource/workloads/pod/detail/component.ts
  src/app/frontend/resource/workloads/pod/detail/style.scss
  src/app/frontend/resource/workloads/pod/detail/template.html
  src/app/frontend/typings/root.api.ts
Labels: approved, cncf-cla: yes, language/de, language/fr, language/ja, language/ko, language/zh, lgtm, size/XXL

#5964 update chinese translations
  i18n/zh-Hans/messages.zh-Hans.xlf
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/L

#5983 Create codeql-analysis.yml
  .github/workflows/codeql-analysis.yml
Labels: approved, cncf-cla: yes, lgtm, size/M

#5993 Update flag description
  src/app/backend/dashboard.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#6005 Bump nodejs from 12.x to 14.16.1
  .babelrc
  .github/workflows/cd-workflow.yml
  .github/workflows/ci-license-workflow.yml
  .github/workflows/ci-workflow.yml
  .gitignore
  aio/develop/Dockerfile
  aio/gulp/gocommand.js
  aio/tsconfig.app.json
  docs/developer/getting-started.md
  i18n/de/messages.de.xlf
  i18n/fr/messages.fr.xlf
  i18n/ja/messages.ja.xlf
  i18n/ko/messages.ko.xlf
  i18n/zh-Hans/messages.zh-Hans.xlf
  i18n/zh-Hant-HK/messages.zh-Hant-HK.xlf
  i18n/zh-Hant/messages.zh-Hant.xlf
  package-lock.json
  package.json
  tsconfig.json
Labels: approved, cncf-cla: yes, language/de, language/fr, language/ja, language/ko, language/zh, lgtm, size/XXL

#6026 Bump kind to 0.10.0
  aio/scripts/conf.sh
  aio/scripts/start-cluster.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5994 Add labels to workload status charts
  i18n/de/messages.de.xlf
  i18n/fr/messages.fr.xlf
  i18n/ja/messages.ja.xlf
  i18n/ko/messages.ko.xlf
  i18n/messages.xlf
  i18n/zh-Hans/messages.zh-Hans.xlf
  i18n/zh-Hant-HK/messages.zh-Hant-HK.xlf
  i18n/zh-Hant/messages.zh-Hant.xlf
  src/app/frontend/common/components/workloadstatus/component.ts
  src/app/frontend/common/components/workloadstatus/template.html
Labels: approved, cncf-cla: yes, language/de, language/fr, language/ja, language/ko, language/zh, lgtm, size/XXL
