Repository kubernetes/dashboard, pull requests merged in 2021-01, with the labels that each got.

#5742 backend: ingress will now use the networking/v1beta1 API instead of extensions/v1beta1
  src/app/backend/api/types.go
  src/app/backend/resource/ingress/common.go
  src/app/backend/resource/ingress/detail.go
  src/app/backend/resource/ingress/list.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#5737 Strip ansi color codes and do not use bypass HTML function
  package-lock.json
  package.json
  src/app/frontend/common/pipes/safehtml.ts
  src/app/frontend/logs/component.ts
  src/app/frontend/logs/template.html
  src/app/frontend/typings/backendapi.ts
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#5745 Dump angular 11
  angular.json
  package-lock.json
  package.json
  src/app/frontend/common/pipes/coreformatter.spec.ts
  src/app/frontend/common/pipes/coreformatter.ts
  src/app/frontend/common/pipes/memoryformatter.spec.ts
  src/app/frontend/common/pipes/memoryformatter.ts
  src/app/frontend/common/pipes/module.ts
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#5621 Remove use of awk and other awkward commands, 2nd try
  docs/user/access-control/creating-sample-user.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#5765 Bump k8s modules to v0.20.2
  aio/scripts/conf.sh
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/M

#5734 The Ingress Detail pane now has an extra table which shows all the rules
  src/app/frontend/common/components/ingressrulelist/component.ts
  src/app/frontend/common/components/ingressrulelist/template.html
  src/app/frontend/common/components/module.ts
  src/app/frontend/resource/discovery/ingress/detail/component.spec.ts
  src/app/frontend/resource/discovery/ingress/detail/template.html
  src/app/frontend/typings/backendapi.ts
Labels: approved, cncf-cla: yes, language/de, language/fr, language/ja, language/ko, language/zh, lgtm, size/L

#5767 On the PV detail page, the PVC should be a link
  src/app/frontend/resource/cluster/persistentvolume/detail/component.ts
  src/app/frontend/resource/cluster/persistentvolume/detail/template.html
Labels: approved, cncf-cla: yes, lgtm, size/S

#5768 add reviewer for i18n zh
  i18n/zh-Hans/OWNERS
  i18n/zh-Hant-HK/OWNERS
  i18n/zh-Hant/OWNERS
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/XS

#5762 Update Traditional Chinese translations
  i18n/zh-Hant/messages.zh-Hant.xlf
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/XS

#5761 Reduce the pressure on api server caused by daemonset related pod queries
  src/app/backend/resource/daemonset/pods.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5766 Fix i18n extract option
  i18n/de/messages.de.xlf
  i18n/fr/messages.fr.xlf
  i18n/ja/messages.ja.xlf
  i18n/ko/messages.ko.xlf
  i18n/messages.xlf
  i18n/zh-Hans/messages.zh-Hans.xlf
  i18n/zh-Hant-HK/messages.zh-Hant-HK.xlf
  i18n/zh-Hant/messages.zh-Hant.xlf
  package.json
Labels: approved, cncf-cla: yes, language/de, language/fr, language/ja, language/ko, language/zh, lgtm, size/XXL

#5773 Remove horizontal lines below the card titles
  src/app/frontend/common/components/card/template.html
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5774 BugFix: raw API calls for ingress should use NetworkingV1beta1 client
  src/app/backend/api/types.go
  src/app/backend/auth/manager_test.go
  src/app/backend/client/manager.go
  src/app/backend/client/verber.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#5777 Preserve deep-links after logging in
  src/app/frontend/common/services/global/history.ts
  src/app/frontend/common/services/guard/auth.ts
  src/app/frontend/login/component.ts
Labels: approved, cncf-cla: yes, lgtm, size/S

#5782 Fix showing pods that mount HostPath
  src/app/frontend/common/components/volumemount/component.ts
  src/app/frontend/common/components/volumemount/template.html
  src/app/frontend/typings/volume.api.ts
Labels: approved, cncf-cla: yes, lgtm, size/M

#5763 Improve theming options
  i18n/de/messages.de.xlf
  i18n/fr/messages.fr.xlf
  i18n/ja/messages.ja.xlf
  i18n/ko/messages.ko.xlf
  i18n/messages.xlf
  i18n/zh-Hans/messages.zh-Hans.xlf
  i18n/zh-Hant-HK/messages.zh-Hant-HK.xlf
  i18n/zh-Hant/messages.zh-Hant.xlf
  src/app/frontend/common/components/textinput/component.ts
  src/app/frontend/common/services/global/localsettings.ts
  src/app/frontend/common/services/global/module.ts
  src/app/frontend/common/services/global/theme.ts
  src/app/frontend/custom-themes.json
  src/app/frontend/index.component.ts
  src/app/frontend/settings/local/component.ts
  src/app/frontend/settings/local/style.scss
  src/app/frontend/settings/local/template.html
  src/app/frontend/typings/root.api.ts
  tsconfig.json
Labels: approved, cncf-cla: yes, language/de, language/fr, language/ja, language/ko, language/zh, lgtm, size/XXL
