Repository kubernetes/dashboard, pull requests merged in 2021-07, with the labels that each got.

#6181 Migrate from "import" to "use", avoid division in stylesheets and switch from sass-lint to stylelint
  .sass-lint.yml
  aio/gulp/backend.js
  aio/scripts/conf.sh
  aio/scripts/format.sh
  docs/developer/code-conventions.md
  go.mod
  go.sum
  package-lock.json
  package.json
  src/app/frontend/_dark.scss
  src/app/frontend/_light.scss
  src/app/frontend/_mixins.scss
  src/app/frontend/_theming.scss
  src/app/frontend/_variables.scss
  src/app/frontend/about/style.scss
  src/app/frontend/chrome/nav/item/style.scss
  src/app/frontend/chrome/nav/style.scss
  src/app/frontend/chrome/notifications/style.scss
  src/app/frontend/chrome/search/style.scss
  src/app/frontend/chrome/style.scss
  src/app/frontend/chrome/userpanel/style.scss
  src/app/frontend/common/components/breadcrumbs/style.scss
  src/app/frontend/common/components/card/style.scss
  src/app/frontend/common/components/container/style.scss
  src/app/frontend/common/components/endpoint/cardlist/style.scss
  src/app/frontend/common/components/endpoint/external/style.scss
  src/app/frontend/common/components/endpoint/internal/style.scss
  src/app/frontend/common/components/graph/style.scss
  src/app/frontend/common/components/hiddenproperty/style.scss
  src/app/frontend/common/components/list/filter/style.scss
  src/app/frontend/common/components/list/rowdetail/style.scss
  src/app/frontend/common/components/list/zerostate/style.scss
  src/app/frontend/common/components/namespace/style.scss
  src/app/frontend/common/components/property/style.scss
  src/app/frontend/common/components/resourcelist/ingress/style.scss
  src/app/frontend/common/components/textinput/style.scss
  src/app/frontend/common/components/uploadfile/style.scss
  src/app/frontend/common/components/workloadstatus/style.scss
  src/app/frontend/common/components/zerostate/style.scss
  src/app/frontend/common/dialogs/download/style.scss
  src/app/frontend/create/from/file/style.scss
  src/app/frontend/create/from/form/helpsection/style.scss
  src/app/frontend/create/from/form/helpsection/userhelp/style.scss
  src/app/frontend/create/from/form/style.scss
  src/app/frontend/create/from/input/style.scss
  src/app/frontend/create/style.scss
  src/app/frontend/error/style.scss
  src/app/frontend/index.scss
  src/app/frontend/login/style.scss
  src/app/frontend/logs/style.scss
  src/app/frontend/resource/config/secret/detail/edit/style.scss
  src/app/frontend/resource/config/storageclass/detail/style.scss
  src/app/frontend/resource/workloads/pod/detail/style.scss
  src/app/frontend/settings/global/namespace/style.scss
  src/app/frontend/settings/global/style.scss
  src/app/frontend/settings/local/style.scss
  src/app/frontend/shell/styles.scss
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#6218 Refactor check and fix html
  aio/scripts/conf.sh
  aio/scripts/format-html.sh
  package.json
Labels: approved, cncf-cla: yes, lgtm, size/M

#6219 Remove `./.husky/.gitignore`
  .husky/.gitignore
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6236 Properly decode base64 encoded UTF-8 strings
  src/app/frontend/common/components/container/component.ts
  src/app/frontend/common/components/container/template.html
  src/app/frontend/common/services/global/decoder.ts
  src/app/frontend/common/services/global/module.ts
  src/app/frontend/resource/config/secret/detail/component.ts
  src/app/frontend/resource/config/secret/detail/edit/component.ts
  src/app/frontend/resource/config/secret/detail/template.html
Labels: approved, cncf-cla: yes, size/M

#6220 Add events list to the global sidebar
  i18n/de/messages.de.xlf
  i18n/fr/messages.fr.xlf
  i18n/ja/messages.ja.xlf
  i18n/ko/messages.ko.xlf
  i18n/messages.xlf
  i18n/zh-Hans/messages.zh-Hans.xlf
  i18n/zh-Hant-HK/messages.zh-Hant-HK.xlf
  i18n/zh-Hant/messages.zh-Hant.xlf
  src/app/backend/handler/apihandler.go
  src/app/backend/resource/common/event.go
  src/app/backend/resource/dataselect/propertyname.go
  src/app/backend/resource/event/common.go
  src/app/backend/resource/event/list.go
  src/app/frontend/chrome/nav/template.html
  src/app/frontend/chrome/routing.ts
  src/app/frontend/common/components/resourcelist/event/component.ts
  src/app/frontend/common/components/resourcelist/event/template.html
  src/app/frontend/common/components/resourcelist/pod/template.html
  src/app/frontend/common/resources/list.ts
  src/app/frontend/common/services/global/namespace.ts
  src/app/frontend/resource/cluster/event/list/component.ts
  src/app/frontend/resource/cluster/event/module.ts
  src/app/frontend/resource/cluster/event/routing.ts
  src/app/frontend/typings/root.api.ts
Labels: approved, cncf-cla: yes, language/de, language/fr, language/ja, language/ko, language/zh, lgtm, size/XXL

#6249 Update Japanese translation
  i18n/de/messages.de.xlf
  i18n/fr/messages.fr.xlf
  i18n/ja/messages.ja.xlf
  i18n/ko/messages.ko.xlf
  i18n/messages.xlf
  i18n/zh-Hans/messages.zh-Hans.xlf
  i18n/zh-Hant-HK/messages.zh-Hant-HK.xlf
  i18n/zh-Hant/messages.zh-Hant.xlf
Labels: approved, cncf-cla: yes, language/de, language/fr, language/ja, language/ko, language/zh, lgtm, size/XXL

#6248 Bump angular staffs from 12.1.0 to 12.1.1
  package-lock.json
  package.json
Labels: approved, cncf-cla: yes, lgtm, size/L

#6254 Respect selected editor format when downloading the data
  src/app/frontend/crd/crdobject/component.ts
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6264 Helm: update to v2.3.1 & update helm CI
  .github/workflows/ci-helm-workflow.yml
  aio/deploy/helm-chart/kubernetes-dashboard/Chart.yaml
  aio/deploy/helm-chart/kubernetes-dashboard/README.md
  aio/deploy/helm-chart/kubernetes-dashboard/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#6268 Bump k8s modules to 0.21.3
  aio/scripts/conf.sh
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/M

#6265 Bump angular staffs from 12.1.1 to 12.1.3
  package-lock.json
  package.json
Labels: approved, cncf-cla: yes, lgtm, size/XL

#6278 Ingress Detail: shows default backend, IngressClass + a small fix
  i18n/de/messages.de.xlf
  i18n/fr/messages.fr.xlf
  i18n/ja/messages.ja.xlf
  i18n/ko/messages.ko.xlf
  i18n/messages.xlf
  i18n/zh-Hans/messages.zh-Hans.xlf
  i18n/zh-Hant-HK/messages.zh-Hant-HK.xlf
  i18n/zh-Hant/messages.zh-Hant.xlf
  src/app/frontend/common/components/ingressrulelist/component.ts
  src/app/frontend/common/components/ingressrulelist/template.html
  src/app/frontend/common/components/volumemount/component.ts
  src/app/frontend/resource/discovery/ingress/detail/template.html
  src/app/frontend/typings/root.api.ts
  src/app/frontend/typings/root.shared.ts
Labels: approved, cncf-cla: yes, language/de, language/fr, language/ja, language/ko, language/zh, lgtm, size/XXL
