Repository kubernetes/dashboard, pull requests merged in 2021-11, with the labels that each got.

#6598 Bump angular staffs from 12.2.11 to 12.2.12.
  package-lock.json
  package.json
Labels: cncf-cla: yes, size/L, approved

#6595 Update method ToEvent to compatible with new event api
  src/app/backend/resource/event/common.go
Labels: cncf-cla: yes, size/S, approved, lgtm

#6608 Bump k8s modules from 0.22.2 to 0.22.3
  aio/scripts/conf.sh
  go.mod
  go.sum
Labels: cncf-cla: yes, size/M, approved

#6625 Update README for Japanese i18n Team
  i18n/ja/README.md
Labels: cncf-cla: yes, size/S, lgtm, language/ja

#6619 [zh-Hans] translate some place
  i18n/zh-Hans/messages.zh-Hans.xlf
Labels: cncf-cla: yes, size/XS, approved, lgtm, language/zh

#6351 Migrate Gulp scripts to Makefile, add latest tag for releases and update dependencies
  .air.toml
  .dockerignore
  .github/workflows/cd-workflow.yml
  .github/workflows/ci-license-workflow.yml
  .github/workflows/ci-workflow.yml
  .gitignore
  .husky/pre-push
  .npmrc
  Makefile
  aio/develop/Dockerfile
  aio/develop/gosu-command.sh
  aio/develop/npm-command.sh
  aio/gulp/backend.js
  aio/gulp/common.js
  aio/gulp/conf.js
  aio/gulp/deploy.js
  aio/gulp/gocommand.js
  aio/gulp/serve.js
  aio/scripts/build.sh
  aio/scripts/conf.sh
  aio/scripts/coverage-backend.sh
  aio/scripts/install-codegen.sh
  aio/scripts/pre-commit-golangci-lint.sh
  docs/common/faq.md
  docs/developer/code-conventions.md
  docs/developer/dependency-management.md
  docs/developer/getting-started.md
  docs/developer/release-procedures.md
  gulpfile.babel.js
  license-checker-config.json
  package-lock.json
  package.json
  src/app/frontend/_theming.scss
  src/app/frontend/index.scss
Labels: cncf-cla: yes, size/XXL, approved, lgtm

#6641 Bump k8s modules from 0.22.4 to 0.22.4.
  .gitignore
  Makefile
  aio/scripts/conf.sh
  go.mod
  go.sum
Labels: cncf-cla: yes, size/M, approved, lgtm

#6615 Added seccompProfile to dashboard spec
  aio/deploy/alternative.yaml
  aio/deploy/head.yaml
  aio/deploy/recommended.yaml
Labels: cncf-cla: yes, size/XS, approved, lgtm

#6643 Fix scripts for pre-commit and pre-push.
  .husky/pre-push
  aio/scripts/pre-commit-i18n.sh
  docs/developer/code-conventions.md
Labels: cncf-cla: yes, size/XS, approved, lgtm
