Repository kubernetes/dashboard, pull requests merged in 2021-08, with the labels that each got.

#6291 Readme update: Add note about Basic authentication being deprecated.
  docs/user/access-control/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6326 Disable directory listing and update ignored files
  .gitignore
  go.sum
  i18n/de/messages.de.xlf
  i18n/fr/messages.fr.xlf
  i18n/ja/messages.ja.xlf
  i18n/ko/messages.ko.xlf
  i18n/messages.xlf
  i18n/zh-Hans/messages.zh-Hans.xlf
  i18n/zh-Hant-HK/messages.zh-Hant-HK.xlf
  i18n/zh-Hant/messages.zh-Hant.xlf
  src/app/backend/handler/localehandler.go
Labels: approved, cncf-cla: yes, language/de, language/fr, language/ja, language/ko, language/zh, lgtm, size/XXL

#6299 add ingressclass capability to ingress template
  aio/deploy/helm-chart/kubernetes-dashboard/Chart.yaml
  aio/deploy/helm-chart/kubernetes-dashboard/README.md
  aio/deploy/helm-chart/kubernetes-dashboard/templates/ingress.yaml
  aio/deploy/helm-chart/kubernetes-dashboard/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#6327 Helm chart: drop values in README in order to avoid maintenance burden, like it is done in many other helm repository.
  aio/deploy/helm-chart/kubernetes-dashboard/Chart.yaml
  aio/deploy/helm-chart/kubernetes-dashboard/README.md
  aio/deploy/helm-chart/kubernetes-dashboard/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/L

#6345 Bump angular staffs to 12.2.1
  package-lock.json
  package.json
Labels: cncf-cla: yes, size/L, approved, lgtm

#6342 Bump k8s modules to 0.22.0 and golang to 1.16.7
  .github/workflows/cd-workflow.yml
  .github/workflows/ci-license-workflow.yml
  .github/workflows/ci-workflow.yml
  aio/develop/Dockerfile
  aio/gulp/gocommand.js
  aio/scripts/conf.sh
  docs/developer/getting-started.md
  go.mod
  go.sum
  package.json
  src/app/backend/plugin/client/clientset/versioned/fake/clientset_generated.go
Labels: cncf-cla: yes, size/L, approved, lgtm

#6350 Make system theme default
  src/app/frontend/common/services/global/localsettings.ts
  src/app/frontend/common/services/global/theme.ts
  src/app/frontend/settings/local/component.ts
Labels: cncf-cla: yes, size/S, approved, lgtm

#6374 Bump angular stuffs from 12.2.1 to 12.2.2.
  package-lock.json
  package.json
Labels: cncf-cla: yes, size/L, approved, lgtm

#6375 Update dependencies and regenerate lockfile
  .github/workflows/cd-workflow.yml
  .github/workflows/ci-helm-workflow.yml
  .github/workflows/ci-workflow.yml
  aio/gulp/gocommand.js
  aio/scripts/conf.sh
  aio/scripts/start-cluster.sh
  package-lock.json
  package.json
  src/app/backend/plugin/apis/v1alpha1/zz_generated.deepcopy.go
Labels: cncf-cla: yes, size/XXL, approved, lgtm
