Repository kubernetes/dashboard, pull requests merged in 2021-02, with the labels that each got.

#5785 Fix typo in developer/text-conventions.md
  docs/developer/text-conventions.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#5771 Ingress Detail: Now the endpoint(s) is/are shown and the TLS Secret, if any
  i18n/de/messages.de.xlf
  i18n/fr/messages.fr.xlf
  i18n/ja/messages.ja.xlf
  i18n/ko/messages.ko.xlf
  i18n/messages.xlf
  i18n/zh-Hans/messages.zh-Hans.xlf
  i18n/zh-Hant-HK/messages.zh-Hant-HK.xlf
  i18n/zh-Hant/messages.zh-Hant.xlf
  package.json
  src/app/frontend/common/components/endpoint/external/component.ts
  src/app/frontend/common/components/ingressrulelist/component.ts
  src/app/frontend/common/components/ingressrulelist/template.html
  src/app/frontend/resource/discovery/ingress/detail/template.html
  src/app/frontend/typings/root.api.ts
Labels: approved, cncf-cla: yes, language/de, language/fr, language/ja, language/ko, language/zh, lgtm, size/XXL

#5789 Use select component as theme picker
  src/app/frontend/settings/local/component.ts
  src/app/frontend/settings/local/template.html
Labels: approved, cncf-cla: yes, lgtm, size/M

#5788 Pods image pull secrets
  i18n/de/messages.de.xlf
  i18n/fr/messages.fr.xlf
  i18n/ja/messages.ja.xlf
  i18n/ko/messages.ko.xlf
  i18n/messages.xlf
  i18n/zh-Hans/messages.zh-Hans.xlf
  i18n/zh-Hant-HK/messages.zh-Hant-HK.xlf
  i18n/zh-Hant/messages.zh-Hant.xlf
  src/app/backend/resource/pod/detail.go
  src/app/frontend/resource/workloads/pod/detail/component.ts
  src/app/frontend/resource/workloads/pod/detail/template.html
  src/app/frontend/typings/root.api.ts
Labels: approved, cncf-cla: yes, language/de, language/fr, language/ja, language/ko, language/zh, lgtm, size/XXL

#5790 Add i18n attrbute for "Security Context"
  i18n/de/messages.de.xlf
  i18n/fr/messages.fr.xlf
  i18n/ja/messages.ja.xlf
  i18n/ko/messages.ko.xlf
  i18n/messages.xlf
  i18n/zh-Hans/messages.zh-Hans.xlf
  i18n/zh-Hant-HK/messages.zh-Hant-HK.xlf
  i18n/zh-Hant/messages.zh-Hant.xlf
  src/app/frontend/common/components/container/template.html
Labels: approved, cncf-cla: yes, language/de, language/fr, language/ja, language/ko, language/zh, lgtm, size/XXL

#5779 Update Traditional Chinese translations and fix typo
  i18n/zh-Hant/messages.zh-Hant.xlf
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/M

#5791 Update Japanese translations
  i18n/ja/messages.ja.xlf
Labels: approved, cncf-cla: yes, language/ja, lgtm, size/M

#5798 Fix error on the Ingress Detail page
  src/app/frontend/common/components/ingressrulelist/component.ts
Labels: approved, cncf-cla: yes, language/de, language/fr, language/ja, language/ko, language/zh, lgtm, size/XS

#5792 update Chinese translations
  i18n/zh-Hans/messages.zh-Hans.xlf
Labels: approved, cncf-cla: yes, language/zh, lgtm, size/M

#5799 Add the link for getting-started
  docs/developer/getting-started.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5797 Use allocatable resources rather than total capacity.
  src/app/backend/resource/node/detail.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5804 Update Japanese
  i18n/ja/messages.ja.xlf
Labels: approved, cncf-cla: yes, language/ja, lgtm, size/M

#5806 Code block highlighting on docs/developer
  docs/developer/code-conventions.md
  docs/developer/getting-started.md
  docs/developer/internationalization.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#5802 Separate commands from output in docs/user
  docs/user/access-control/README.md
  docs/user/access-control/creating-sample-user.md
  docs/user/accessing-dashboard/README.md
  docs/user/certificate-management.md
  docs/user/installation.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#5808 Code block highlighting on README.md at root.
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#5809 Code block highlighting on docs/common.
  docs/common/faq.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#5810 Code block highlighting on docs/plugins.
  docs/plugins/README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#5803 Hardcoded ConfigMap name in helm chart
  aio/deploy/helm-chart/kubernetes-dashboard/Chart.yaml
  aio/deploy/helm-chart/kubernetes-dashboard/templates/configmap.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#5682 Add namespace related options to global settings
  angular.json
  i18n/de/messages.de.xlf
  i18n/fr/messages.fr.xlf
  i18n/ja/messages.ja.xlf
  i18n/ko/messages.ko.xlf
  i18n/messages.xlf
  i18n/zh-Hans/messages.zh-Hans.xlf
  i18n/zh-Hant-HK/messages.zh-Hant-HK.xlf
  i18n/zh-Hant/messages.zh-Hant.xlf
  src/app/backend/settings/api/types.go
  src/app/frontend/_theming.scss
  src/app/frontend/common/components/module.ts
  src/app/frontend/common/components/namespace/component.ts
  src/app/frontend/common/components/namespace/template.html
  src/app/frontend/common/services/global/globalsettings.ts
  src/app/frontend/common/services/global/notifications.ts
  src/app/frontend/common/services/guard/login.ts
  src/app/frontend/index.scss
  src/app/frontend/login/component.ts
  src/app/frontend/resource/cluster/namespace/detail/actionbar/component.ts
  src/app/frontend/resource/cluster/namespace/detail/actionbar/template.html
  src/app/frontend/resource/cluster/persistentvolume/detail/source/template.html
  src/app/frontend/settings/global/component.ts
  src/app/frontend/settings/global/namespace/adddialog/dialog.ts
  src/app/frontend/settings/global/namespace/adddialog/template.html
  src/app/frontend/settings/global/namespace/component.ts
  src/app/frontend/settings/global/namespace/editdialog/dialog.ts
  src/app/frontend/settings/global/namespace/editdialog/template.html
  src/app/frontend/settings/global/namespace/style.scss
  src/app/frontend/settings/global/namespace/template.html
  src/app/frontend/settings/global/service.ts
  src/app/frontend/settings/global/template.html
  src/app/frontend/settings/module.ts
  src/app/frontend/shared.module.ts
  src/app/frontend/typings/root.api.ts
Labels: approved, cncf-cla: yes, language/de, language/fr, language/ja, language/ko, language/zh, lgtm, size/XXL

#5812 Prepare for v2.2.0 release
  README.md
  aio/deploy/alternative.yaml
  aio/deploy/alternative/06_dashboard-deployment.yaml
  aio/deploy/recommended.yaml
  aio/deploy/recommended/06_dashboard-deployment.yaml
  aio/gulp/conf.js
  docs/user/installation.md
  package-lock.json
  package.json
Labels: approved, cncf-cla: yes, lgtm, size/S

#5813 Bump Dashboard Helm version
  aio/deploy/helm-chart/kubernetes-dashboard/Chart.yaml
  aio/deploy/helm-chart/kubernetes-dashboard/README.md
  aio/deploy/helm-chart/kubernetes-dashboard/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/S

#5817 Bump k8s modules to 0.20.4
  aio/scripts/conf.sh
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, size/M

#5827 Hide pagination controls if there is only one page
  i18n/messages.xlf
  src/app/frontend/common/components/resourcelist/clusterrole/template.html
  src/app/frontend/common/components/resourcelist/clusterrolebinding/template.html
  src/app/frontend/common/components/resourcelist/configmap/template.html
  src/app/frontend/common/components/resourcelist/crd/template.html
  src/app/frontend/common/components/resourcelist/crdobject/template.html
  src/app/frontend/common/components/resourcelist/cronjob/template.html
  src/app/frontend/common/components/resourcelist/daemonset/template.html
  src/app/frontend/common/components/resourcelist/deployment/template.html
  src/app/frontend/common/components/resourcelist/event/template.html
  src/app/frontend/common/components/resourcelist/horizontalpodautoscaler/template.html
  src/app/frontend/common/components/resourcelist/ingress/template.html
  src/app/frontend/common/components/resourcelist/job/template.html
  src/app/frontend/common/components/resourcelist/namespace/template.html
  src/app/frontend/common/components/resourcelist/networkpolicy/template.html
  src/app/frontend/common/components/resourcelist/node/template.html
  src/app/frontend/common/components/resourcelist/persistentvolume/template.html
  src/app/frontend/common/components/resourcelist/persistentvolumeclaim/template.html
  src/app/frontend/common/components/resourcelist/plugin/template.html
  src/app/frontend/common/components/resourcelist/pod/template.html
  src/app/frontend/common/components/resourcelist/replicaset/template.html
  src/app/frontend/common/components/resourcelist/replicationcontroller/template.html
  src/app/frontend/common/components/resourcelist/role/template.html
  src/app/frontend/common/components/resourcelist/rolebinding/template.html
  src/app/frontend/common/components/resourcelist/secret/template.html
  src/app/frontend/common/components/resourcelist/service/template.html
  src/app/frontend/common/components/resourcelist/serviceaccount/template.html
  src/app/frontend/common/components/resourcelist/statefulset/template.html
  src/app/frontend/common/components/resourcelist/storageclass/template.html
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#5832 move some library to devDependencies
  package.json
Labels: approved, cncf-cla: yes, lgtm, size/S

#5834 Fix null/undefined object assign error
  package-lock.json
  package.json
  src/app/frontend/common/components/volumemount/component.ts
Labels: approved, cncf-cla: yes, size/XXL
