Repository kubernetes/dashboard, pull requests merged in 2022-10, with the labels that each got.

#7490 Move about page to footer
  modules/web/cypress/integration/specs/nav.spec.ts
  modules/web/cypress/pages/navbarPage.ts
  modules/web/i18n/de/messages.de.xlf
  modules/web/i18n/es/messages.es.xlf
  modules/web/i18n/fr/messages.fr.xlf
  modules/web/i18n/ja/messages.ja.xlf
  modules/web/i18n/ko/messages.ko.xlf
  modules/web/i18n/messages.xlf
  modules/web/i18n/zh-Hans/messages.zh-Hans.xlf
  modules/web/i18n/zh-Hant-HK/messages.zh-Hant-HK.xlf
  modules/web/i18n/zh-Hant/messages.zh-Hant.xlf
  modules/web/src/_theming.scss
  modules/web/src/about/actionbar/component.ts
  modules/web/src/about/actionbar/template.html
  modules/web/src/about/component.spec.ts
  modules/web/src/about/module.ts
  modules/web/src/about/routing.ts
  modules/web/src/about/template.html
  modules/web/src/chrome/footer/component.ts
  modules/web/src/chrome/footer/style.scss
  modules/web/src/chrome/footer/template.html
  modules/web/src/chrome/module.ts
  modules/web/src/chrome/nav/template.html
  modules/web/src/chrome/routing.ts
  modules/web/src/chrome/template.html
  modules/web/src/index.scss
Labels: cncf-cla: yes, size/XL, approved, lgtm, language/ja, language/zh, language/ko, language/fr, language/de

#7491 Add support for multiarch docker build and deploy
  Makefile
  hack/docker/docker.compose.yaml
  hack/include/config.mk
  hack/include/deploy.mk
  modules/api/Dockerfile
  modules/api/Makefile
  modules/api/hack/include/config.mk
  modules/web/Dockerfile
  modules/web/Makefile
  modules/web/hack/include/config.mk
Labels: cncf-cla: yes, size/L, approved, lgtm, language/ja, language/zh, language/ko, language/fr, language/de

#7506 fix:change toleration from master to control-plane
  charts/alternative.yaml
  charts/alternative/06_dashboard-deployment.yaml
  charts/alternative/08_scraper-deployment.yaml
  charts/head.yaml
  charts/head/06_dashboard-deployment.yaml
  charts/head/08_scraper-deployment.yaml
  charts/recommended.yaml
  charts/recommended/06_dashboard-deployment.yaml
  charts/recommended/08_scraper-deployment.yaml
  hack/test-resources/kubernetes-dashboard-local.yaml
Labels: cncf-cla: yes, size/S, approved, lgtm
