Repository kubernetes/dashboard, pull requests merged in 2022-05, with the labels that each got.

#7068 docs: deploy `helm` with name `kubernetes-dashboard`
  aio/deploy/helm-chart/kubernetes-dashboard/Chart.yaml
  aio/deploy/helm-chart/kubernetes-dashboard/README.md
Labels: cncf-cla: yes, size/S, approved, lgtm

#7054 Update Japanese translation (Line 1-1593)
  i18n/ja/messages.ja.xlf
Labels: cncf-cla: yes, size/L, approved, lgtm, language/ja

#6920 Add support for IngressClass [#5232]
  i18n/de/messages.de.xlf
  i18n/es/messages.es.xlf
  i18n/fr/messages.fr.xlf
  i18n/ja/messages.ja.xlf
  i18n/ko/messages.ko.xlf
  i18n/messages.xlf
  i18n/zh-Hans/messages.zh-Hans.xlf
  i18n/zh-Hant-HK/messages.zh-Hant-HK.xlf
  i18n/zh-Hant/messages.zh-Hant.xlf
  src/app/backend/api/types.go
  src/app/backend/handler/apihandler.go
  src/app/backend/resource/common/resourcechannels.go
  src/app/backend/resource/ingressclass/common.go
  src/app/backend/resource/ingressclass/detail.go
  src/app/backend/resource/ingressclass/detail_test.go
  src/app/backend/resource/ingressclass/list.go
  src/app/backend/resource/ingressclass/list_test.go
  src/app/frontend/chrome/nav/template.html
  src/app/frontend/chrome/routing.ts
  src/app/frontend/common/components/module.ts
  src/app/frontend/common/components/resourcelist/groupids.ts
  src/app/frontend/common/components/resourcelist/ingressclass/component.ts
  src/app/frontend/common/components/resourcelist/ingressclass/template.html
  src/app/frontend/common/services/resource/endpoint.ts
  src/app/frontend/index.messages.ts
  src/app/frontend/overview/template.html
  src/app/frontend/resource/discovery/ingressclass/detail/component.ts
  src/app/frontend/resource/discovery/ingressclass/detail/style.scss
  src/app/frontend/resource/discovery/ingressclass/detail/template.html
  src/app/frontend/resource/discovery/ingressclass/list/component.ts
  src/app/frontend/resource/discovery/ingressclass/module.ts
  src/app/frontend/resource/discovery/ingressclass/routing.ts
  src/app/frontend/resource/discovery/template.html
  src/app/frontend/search/template.html
  src/app/frontend/typings/root.api.ts
  src/app/frontend/typings/root.ui.ts
Labels: cncf-cla: yes, size/XXL, approved, lgtm, language/ja, language/zh, language/ko, language/fr, language/de

#7079 Update Japanese translation(Line 1594-2887)
  i18n/ja/messages.ja.xlf
Labels: cncf-cla: yes, size/L, approved, lgtm, language/ja

#7096 Update Japanese translation(Line 2888-5094)
  i18n/ja/messages.ja.xlf
Labels: cncf-cla: yes, size/L, approved, lgtm, language/ja

#7117 Update messages.de.xlf
  i18n/de/messages.de.xlf
Labels: cncf-cla: yes, size/XS, approved, lgtm, language/de

#7053 Bump angular staffs to 13.3.5
  package-lock.json
  package.json
Labels: cncf-cla: yes, size/L, approved, lgtm

#7073 Bump k8s modules to 0.24.0
  Makefile
  aio/scripts/conf.sh
  go.mod
  go.sum
Labels: cncf-cla: yes, size/L, approved, lgtm

#7102 chore(deps): Included dependency review
  .github/workflows/depsreview.yaml
Labels: cncf-cla: yes, size/S, approved, lgtm

#6967 Update docs for 1.24+
  aio/develop/npm-command.sh
  docs/user/access-control/creating-sample-user.md
Labels: cncf-cla: yes, size/XS, approved, lgtm

#7140 Update dependencies and prepare for v2.6.0 release
  .github/dependabot.yml
  Makefile
  README.md
  aio/deploy/alternative.yaml
  aio/deploy/alternative/06_dashboard-deployment.yaml
  aio/deploy/alternative/08_scraper-deployment.yaml
  aio/deploy/helm-chart/kubernetes-dashboard/Chart.yaml
  aio/deploy/helm-chart/kubernetes-dashboard/values.yaml
  aio/deploy/recommended.yaml
  aio/deploy/recommended/06_dashboard-deployment.yaml
  aio/deploy/recommended/08_scraper-deployment.yaml
  docs/user/installation.md
  go.mod
  go.sum
  package-lock.json
  package.json
  src/app/frontend/common/components/chips/component.ts
  src/app/frontend/common/components/namespace/component.ts
  src/app/frontend/common/components/resourcelist/clusterrolebinding/component.ts
  src/app/frontend/common/components/resourcelist/rolebinding/component.ts
  src/app/frontend/common/resources/list.ts
  src/app/frontend/common/services/global/pinner.ts
  src/app/frontend/resource/cluster/clusterrolebinding/detail/component.ts
  src/app/frontend/settings/global/component.ts
Labels: cncf-cla: yes, size/XXL, approved
