Repository kubernetes/dashboard, pull requests merged in 2022-12, with the labels that each got.

#7543 Hide node port 0 and update Go dependencies
  modules/api/go.mod
  modules/api/go.sum
  modules/common/tools/go.mod
  modules/common/tools/go.sum
  modules/web/go.mod
  modules/web/go.sum
  modules/web/i18n/ko/messages.ko.xlf
  modules/web/src/common/components/endpoint/internal/template.html
Labels: cncf-cla: yes, size/XL, approved, lgtm, language/ko

#7549 Fix HTTP headers display, restore Go static check and fix typo
  Makefile
  modules/api/Makefile
  modules/web/Makefile
  modules/web/pkg/systembanner/manager.go
  modules/web/src/common/components/probe/template.html
Labels: cncf-cla: yes, size/M, approved, lgtm

#7487 ingress paths are now clickable
  modules/web/src/common/components/ingressrulelist/template.html
Labels: cncf-cla: yes, size/S, approved, lgtm

#7563 Setup development container for new architecture
  docs/developer/getting-started.md
  hack/develop/Dockerfile
  hack/develop/gosu-command.sh
  hack/develop/npm-command.sh
  hack/develop/run-dev-container.sh
  modules/web/i18n/ja/README.md
Labels: cncf-cla: yes, size/L, approved, lgtm, language/ja
