Repository kubernetes/dashboard, pull requests merged in 2022-04, with the labels that each got.

#6962 ci(helm): remove local subchart tgz, upgrade helm ci dependencies, add gitignore for subcharts.
  .github/workflows/ci-helm-workflow.yml
  .gitignore
  aio/deploy/helm-chart/kubernetes-dashboard/Chart.yaml
  aio/deploy/helm-chart/kubernetes-dashboard/charts/metrics-server-3.5.0.tgz
Labels: cncf-cla: yes, size/S, approved, lgtm

#6963 Update issue templates and project config
  .browserslistrc
  .eslintignore
  .eslintrc.yaml
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/cleanup.md
  .github/ISSUE_TEMPLATE/enhancement.md
  .github/ISSUE_TEMPLATE/failing-test.md
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/ISSUE_TEMPLATE/issue.md
  .github/ISSUE_TEMPLATE/support.md
  .github/workflows/cd-workflow.yml
  .github/workflows/ci-workflow.yml
  .golangci.yml
  .stylelintrc.yaml
  Makefile
  OWNERS_ALIASES
  docs/developer/code-conventions.md
  docs/developer/getting-started.md
  package-lock.json
  package.json
Labels: cncf-cla: yes, size/L, approved, lgtm

#6972 Update issue templates
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/bug-report.yaml
  .github/ISSUE_TEMPLATE/cleanup.md
  .github/ISSUE_TEMPLATE/cleanup.yaml
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/ISSUE_TEMPLATE/feature-request.yaml
  .github/ISSUE_TEMPLATE/support.md
  .github/ISSUE_TEMPLATE/support.yaml
Labels: cncf-cla: yes, size/L, approved

#6973 Fix issue templates
  .github/ISSUE_TEMPLATE/bug-report.yaml
  .github/ISSUE_TEMPLATE/cleanup.yaml
Labels: cncf-cla: yes

#6974 Fix issue templates config
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/cleanup.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature-request.yml
Labels: cncf-cla: yes, size/S, approved

#6976 Remove ts-ignore and fix errors in dependencies
  package-lock.json
  package.json
  src/app/frontend/common/components/chips/component.ts
  src/app/frontend/common/services/global/globalsettings.ts
Labels: cncf-cla: yes, size/XL, approved, lgtm

#6971 Remove unused import and useless conditional expression
  .eslintrc.yaml
  src/app/frontend/chrome/userpanel/component.ts
  src/app/frontend/common/components/breadcrumbs/component.ts
  src/app/frontend/common/dialogs/config/dialog.ts
  src/app/frontend/common/pipes/stripansi.ts
  src/app/frontend/common/resources/resource.ts
  src/app/frontend/resource/cluster/persistentvolume/detail/component.ts
Labels: cncf-cla: yes, size/S, approved, lgtm

#6953 allow set custom clusterIP
  aio/deploy/helm-chart/kubernetes-dashboard/Chart.yaml
  aio/deploy/helm-chart/kubernetes-dashboard/templates/service.yaml
  aio/deploy/helm-chart/kubernetes-dashboard/values.yaml
Labels: cncf-cla: yes, size/XS, approved, lgtm

#6989 Small Typo Fix
  src/app/frontend/common/components/date/component.ts
Labels: cncf-cla: yes, size/XS, approved, lgtm

#6992 Bump angular staffs to 13.3.2
  package-lock.json
  package.json
Labels: cncf-cla: yes, size/XXL, approved, lgtm

#6991 Implement the 'Preview' button and the 'Preview Deployment' dialog
  src/app/frontend/common/dialogs/module.ts
  src/app/frontend/common/dialogs/previewdeployment/dialog.ts
  src/app/frontend/common/dialogs/previewdeployment/template.html
  src/app/frontend/create/from/form/component.ts
  src/app/frontend/create/from/form/template.html
Labels: cncf-cla: yes, size/L, approved, lgtm

#6952 Normalize graph values after determining the highest suffix in the whole dataset
  src/app/frontend/common/components/graph/component.ts
Labels: cncf-cla: yes, size/S, approved, lgtm

#6993 Close subscription on destroy
  docs/common/dashboard-arguments.md
  docs/developer/code-conventions.md
  docs/developer/internationalization.md
  i18n/de/messages.de.xlf
  i18n/es/messages.es.xlf
  i18n/fr/messages.fr.xlf
  i18n/ja/messages.ja.xlf
  i18n/ko/messages.ko.xlf
  i18n/messages.xlf
  i18n/zh-Hans/messages.zh-Hans.xlf
  i18n/zh-Hant-HK/messages.zh-Hant-HK.xlf
  i18n/zh-Hant/messages.zh-Hant.xlf
  src/app/backend/api/types.go
  src/app/backend/resource/configmap/list.go
  src/app/backend/resource/logs/logs.go
  src/app/backend/resource/pod/detail.go
  src/app/frontend/common/dialogs/editresource/dialog.ts
  src/app/frontend/common/dialogs/previewdeployment/dialog.ts
  src/app/frontend/common/params/params.ts
  src/app/frontend/common/services/global/params.ts
  src/app/frontend/crd/crdobject/component.ts
  src/app/frontend/create/from/form/component.ts
  src/app/frontend/create/from/form/createsecret/template.html
  src/app/frontend/login/component.spec.ts
Labels: cncf-cla: yes, size/XXL, approved, lgtm, language/ja, language/zh, language/ko, language/fr, language/de

#7007 Update and fix issues with create from view
  i18n/de/messages.de.xlf
  i18n/es/messages.es.xlf
  i18n/fr/messages.fr.xlf
  i18n/ja/messages.ja.xlf
  i18n/ko/messages.ko.xlf
  i18n/messages.xlf
  i18n/zh-Hans/messages.zh-Hans.xlf
  i18n/zh-Hant-HK/messages.zh-Hant-HK.xlf
  i18n/zh-Hant/messages.zh-Hant.xlf
  src/app/backend/errors/localizer.go
  src/app/frontend/common/dialogs/previewdeployment/dialog.ts
  src/app/frontend/common/services/create/service.ts
  src/app/frontend/create/from/file/component.ts
  src/app/frontend/create/from/file/template.html
  src/app/frontend/create/from/form/component.ts
  src/app/frontend/create/from/form/template.html
  src/app/frontend/create/from/input/component.ts
Labels: cncf-cla: yes, size/XXL, approved, lgtm, language/ja, language/zh, language/ko, language/fr, language/de

#7012 Bump angular staffs to 13.3.3
  package-lock.json
  package.json
Labels: cncf-cla: yes, size/XXL, approved, lgtm

#7008 Styling adjustments and fixes
  i18n/de/messages.de.xlf
  i18n/es/messages.es.xlf
  i18n/fr/messages.fr.xlf
  i18n/ja/messages.ja.xlf
  i18n/ko/messages.ko.xlf
  i18n/messages.xlf
  i18n/zh-Hans/messages.zh-Hans.xlf
  i18n/zh-Hant-HK/messages.zh-Hant-HK.xlf
  i18n/zh-Hant/messages.zh-Hant.xlf
  src/app/frontend/_variables.scss
  src/app/frontend/chrome/search/component.ts
  src/app/frontend/chrome/search/template.html
  src/app/frontend/chrome/style.scss
  src/app/frontend/chrome/template.html
  src/app/frontend/common/components/card/style.scss
  src/app/frontend/common/components/chips/component.ts
  src/app/frontend/common/components/chips/style.scss
  src/app/frontend/common/components/resourcelist/configmap/template.html
  src/app/frontend/common/components/resourcelist/crd/template.html
  src/app/frontend/common/components/resourcelist/cronjob/template.html
  src/app/frontend/common/components/resourcelist/daemonset/template.html
  src/app/frontend/common/components/resourcelist/deployment/template.html
  src/app/frontend/common/components/resourcelist/event/template.html
  src/app/frontend/common/components/resourcelist/ingress/template.html
  src/app/frontend/common/components/resourcelist/job/template.html
  src/app/frontend/common/components/resourcelist/node/template.html
  src/app/frontend/common/components/resourcelist/persistentvolume/template.html
  src/app/frontend/common/components/resourcelist/persistentvolumeclaim/template.html
  src/app/frontend/common/components/resourcelist/pod/template.html
  src/app/frontend/common/components/resourcelist/replicaset/template.html
  src/app/frontend/common/components/resourcelist/replicationcontroller/template.html
  src/app/frontend/common/components/resourcelist/secret/template.html
  src/app/frontend/common/components/resourcelist/service/template.html
  src/app/frontend/common/components/resourcelist/statefulset/template.html
  src/app/frontend/common/components/resourcelist/storageclass/template.html
  src/app/frontend/index.scss
Labels: cncf-cla: yes, size/XXL, approved, lgtm, language/ja, language/zh, language/ko, language/fr, language/de

#7029 Bump angular staffs to 13.3.4
  package-lock.json
  package.json
Labels: cncf-cla: yes, size/XXL, approved, lgtm

#7030 Bump k8s modules to 0.23.6
  Makefile
  aio/scripts/conf.sh
  go.mod
  go.sum
  src/app/backend/plugin/client/clientset/versioned/clientset.go
Labels: cncf-cla: yes, size/M, approved, lgtm
