Repository kubernetes/dashboard, pull requests merged in 2022-02, with the labels that each got.

#6750 Fixed indent of selector.matchLabels in serviceMonitor
  aio/deploy/helm-chart/kubernetes-dashboard/Chart.yaml
  aio/deploy/helm-chart/kubernetes-dashboard/templates/servicemonitor.yaml
Labels: cncf-cla: yes, size/XS, approved, lgtm

#6757 Helm: Update CI components, do not run helm lint on chart-testing on master, rename subchart repository
  .github/workflows/ci-helm-workflow.yml
  aio/deploy/helm-chart/.helm-chart-testing.yaml
  aio/deploy/helm-chart/config_repos
  aio/deploy/helm-chart/kubernetes-dashboard/Chart.yaml
  aio/deploy/helm-chart/kubernetes-dashboard/values.yaml
  aio/scripts/helm-release-chart.sh
Labels: cncf-cla: yes, size/S, approved, lgtm

#6767 Bump versions
  Makefile
  README.md
  aio/deploy/alternative.yaml
  aio/deploy/alternative/06_dashboard-deployment.yaml
  aio/deploy/recommended.yaml
  aio/deploy/recommended/06_dashboard-deployment.yaml
  docs/user/installation.md
  package.json
Labels: cncf-cla: yes, size/S, approved, lgtm

#6771 Bump angular staffs to 13.2.1.
  package-lock.json
  package.json
Labels: cncf-cla: yes, size/XXL, approved, lgtm

#6772 Update Helm Chart with v2.5.0
  aio/deploy/helm-chart/kubernetes-dashboard/Chart.yaml
  aio/deploy/helm-chart/kubernetes-dashboard/values.yaml
Labels: cncf-cla: yes, size/XS, approved, lgtm

#6587 Feat/spanish localization
  angular.json
  docs/developer/internationalization.md
  i18n/es/OWNERS
  i18n/es/messages.es.xlf
  i18n/locale_conf.json
  package.json
  src/app/frontend/index.config.ts
Labels: cncf-cla: yes, size/XXL, approved, lgtm

#6793 Bump angular staffs to 13.2.2.
  i18n/es/messages.es.xlf
  i18n/messages.xlf
  package-lock.json
  package.json
Labels: cncf-cla: yes, size/XXL, approved, lgtm

#6783 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: cncf-cla: yes, size/XS, approved, lgtm

#6680 Update Chinese translation
  i18n/zh-Hans/messages.zh-Hans.xlf
Labels: cncf-cla: yes, size/L, approved, lgtm, language/zh

#6800 Remove token check and add user info
  i18n/de/messages.de.xlf
  i18n/es/messages.es.xlf
  i18n/fr/messages.fr.xlf
  i18n/ja/messages.ja.xlf
  i18n/ko/messages.ko.xlf
  i18n/messages.xlf
  i18n/zh-Hans/messages.zh-Hans.xlf
  i18n/zh-Hant-HK/messages.zh-Hant-HK.xlf
  i18n/zh-Hant/messages.zh-Hant.xlf
  package.json
  src/app/backend/auth/api/types.go
  src/app/backend/auth/manager.go
  src/app/backend/auth/manager_test.go
  src/app/backend/client/api/types.go
  src/app/backend/client/manager.go
  src/app/backend/plugin/config_test.go
  src/app/frontend/chrome/userpanel/component.ts
  src/app/frontend/chrome/userpanel/style.scss
  src/app/frontend/chrome/userpanel/template.html
  src/app/frontend/common/services/global/authentication.ts
  src/app/frontend/index.config.ts
  src/app/frontend/index.scss
  src/app/frontend/login/component.ts
  src/app/frontend/typings/root.api.ts
  src/app/frontend/typings/root.ui.ts
Labels: cncf-cla: yes, size/XXL, approved, lgtm, language/ja, language/zh, language/ko, language/fr, language/de

#6801 Strip ANSI codes from logs
  src/app/frontend/common/pipes/module.ts
  src/app/frontend/common/pipes/stripansi.ts
  src/app/frontend/logs/template.html
Labels: cncf-cla: yes, size/S, approved, lgtm

#6821 update README.md for japnese traslation.
  i18n/ja/README.md
Labels: cncf-cla: yes, size/XS, approved, lgtm, language/ja

#6829 Bump angular staffs to 13.2.3 and 4.
  package-lock.json
  package.json
Labels: cncf-cla: yes, size/XXL, approved, lgtm

#6831 Bump k8s modules to 0.24.4
  Makefile
  aio/scripts/conf.sh
  go.mod
  go.sum
  package.json
Labels: cncf-cla: yes, size/M, approved, lgtm

#6837 Fixed indentation of annotations.
  aio/deploy/helm-chart/kubernetes-dashboard/Chart.yaml
  aio/deploy/helm-chart/kubernetes-dashboard/templates/servicemonitor.yaml
Labels: cncf-cla: yes, size/XS, approved, lgtm

#6839 Helm chart: test serviceMonitor and fix annotation indent.
  .github/workflows/ci-helm-workflow.yml
  aio/deploy/helm-chart/kubernetes-dashboard/Chart.yaml
  aio/deploy/helm-chart/kubernetes-dashboard/ci/servicemonitor-values.yaml
  aio/deploy/helm-chart/kubernetes-dashboard/templates/servicemonitor.yaml
Labels: cncf-cla: yes, size/S, approved, lgtm

#6850 Bump angular staffs to 13.2.4 and 5
  package-lock.json
  package.json
Labels: cncf-cla: yes, size/XXL, approved, lgtm

#6840 Fix bug in multiple removal from crd versions list
  src/app/backend/resource/customresourcedefinition/v1/common.go
  src/app/backend/resource/customresourcedefinition/v1/list_test.go
Labels: cncf-cla: yes, size/M, approved, lgtm

#6852 Add untrim pipe to allow string indent in templates
  src/app/frontend/common/pipes/module.ts
  src/app/frontend/common/pipes/untrim.ts
  src/app/frontend/logs/template.html
Labels: cncf-cla: yes, size/M, approved, lgtm
