Repository kubernetes/dashboard, pull requests merged in 2022-08, with the labels that each got.

#7189 fix: fix panic while RsaKeyHolder secret is nil
  src/app/backend/auth/basic_test.go
  src/app/backend/auth/jwe/keyholder.go
  src/app/backend/auth/jwe/keyholder_test.go
Labels: cncf-cla: yes, size/S, approved, lgtm

#7314 Set timeout in terminalSessions
  src/app/backend/auth/basic_test.go
  src/app/backend/handler/terminal.go
Labels: cncf-cla: yes, size/S, approved, lgtm

#7349 Update bug template
  .github/ISSUE_TEMPLATE/bug-report.yml
Labels: cncf-cla: yes, size/S, approved, lgtm

#7350 Revert ng-in-viewport to 6.1.5
  package-lock.json
  package.json
Labels: cncf-cla: yes, size/XXL, approved, lgtm

#7111 Show Capacity in the node list and node detail
  src/app/frontend/common/components/resourcelist/node/component.ts
  src/app/frontend/common/components/resourcelist/node/template.html
  src/app/frontend/resource/cluster/node/detail/template.html
Labels: cncf-cla: yes, size/M, approved, lgtm

#7093 Add barebones support for generic ephemeral volume
  src/app/frontend/typings/volume.api.ts
Labels: cncf-cla: yes, size/S, approved, lgtm

#7358 Revert "Show Cluster status with cumulative node resources"
  src/app/backend/resource/node/detail.go
  src/app/backend/resource/node/list.go
  src/app/backend/resource/node/list_test.go
  src/app/frontend/common/components/clusterstatus/component.ts
  src/app/frontend/common/components/clusterstatus/style.scss
  src/app/frontend/common/components/clusterstatus/template.html
  src/app/frontend/common/components/graph/helper.ts
  src/app/frontend/common/components/module.ts
  src/app/frontend/common/resources/groupedlist.ts
  src/app/frontend/overview/component.ts
  src/app/frontend/overview/template.html
  src/app/frontend/resource/cluster/component.ts
  src/app/frontend/resource/cluster/template.html
  src/app/frontend/typings/root.api.ts
  src/app/frontend/typings/root.ui.ts
Labels: cncf-cla: yes, size/L, approved

#7355 Update Go version to 1.19
  .github/workflows/cd-workflow.yml
  .github/workflows/ci-workflow.yml
  Makefile
  aio/develop/Dockerfile
  aio/scripts/conf.sh
  go.mod
  go.sum
  src/app/backend/auth/api/types.go
  src/app/backend/auth/jwe/keyholder.go
  src/app/backend/errors/localizer.go
  src/app/backend/plugin/client/clientset/versioned/fake/register.go
  src/app/backend/plugin/client/clientset/versioned/scheme/register.go
  src/app/backend/resource/common/namespace.go
  src/app/backend/resource/common/pod.go
  src/app/backend/resource/cronjob/jobs_test.go
  src/app/backend/resource/deployment/oldreplicasets.go
  src/app/backend/resource/horizontalpodautoscaler/list_test.go
  src/app/backend/resource/node/common.go
Labels: cncf-cla: yes, size/M, approved, lgtm

#7359 v2.6.1
  Makefile
  README.md
  aio/deploy/alternative.yaml
  aio/deploy/alternative/06_dashboard-deployment.yaml
  aio/deploy/recommended.yaml
  aio/deploy/recommended/06_dashboard-deployment.yaml
  docs/user/installation.md
  i18n/de/messages.de.xlf
  i18n/es/messages.es.xlf
  i18n/fr/messages.fr.xlf
  i18n/ja/messages.ja.xlf
  i18n/ko/messages.ko.xlf
  i18n/messages.xlf
  i18n/zh-Hans/messages.zh-Hans.xlf
  i18n/zh-Hant-HK/messages.zh-Hant-HK.xlf
  i18n/zh-Hant/messages.zh-Hant.xlf
  package-lock.json
  package.json
Labels: cncf-cla: yes, size/XXL, approved, lgtm, language/ja, language/zh, language/ko, language/fr, language/de

#7360 Update Helm chart to use v2.6.1
  aio/deploy/helm-chart/kubernetes-dashboard/Chart.yaml
  aio/deploy/helm-chart/kubernetes-dashboard/values.yaml
Labels: cncf-cla: yes, size/XS, approved, lgtm

#7152 Support custom rules for read-only mode
  aio/deploy/helm-chart/kubernetes-dashboard/Chart.yaml
  aio/deploy/helm-chart/kubernetes-dashboard/templates/clusterrole-readonly.yaml
  aio/deploy/helm-chart/kubernetes-dashboard/values.yaml
Labels: cncf-cla: yes, size/XS, approved, lgtm

#7379 Fix golang 1.19.0 update
  aio/develop/Dockerfile
  docs/developer/getting-started.md
  i18n/de/messages.de.xlf
  i18n/es/messages.es.xlf
  i18n/fr/messages.fr.xlf
  i18n/ja/messages.ja.xlf
  i18n/ko/messages.ko.xlf
  i18n/messages.xlf
  i18n/zh-Hans/messages.zh-Hans.xlf
  i18n/zh-Hant-HK/messages.zh-Hant-HK.xlf
  i18n/zh-Hant/messages.zh-Hant.xlf
Labels: cncf-cla: yes, size/XXL, approved, lgtm, language/ja, language/zh, language/ko, language/fr, language/de

#7370 feat: added additional rules option to role
  aio/deploy/helm-chart/kubernetes-dashboard/Chart.yaml
  aio/deploy/helm-chart/kubernetes-dashboard/templates/role.yaml
  aio/deploy/helm-chart/kubernetes-dashboard/values.yaml
Labels: cncf-cla: yes, size/XS, approved, lgtm

#7231 Update German translation.
  i18n/de/messages.de.xlf
Labels: cncf-cla: yes, size/L, approved, lgtm, language/de

#7413 Add ziyi-xie to Japanese i18n reviewers
  i18n/ja/OWNERS
Labels: cncf-cla: yes, size/XS, approved, lgtm, language/ja

#7415 Update Japanese translation
  i18n/ja/messages.ja.xlf
Labels: cncf-cla: yes, size/L, approved, lgtm, language/ja

#7414 Fix tags in German translation
  i18n/de/messages.de.xlf
Labels: cncf-cla: yes, size/XS, approved, lgtm, language/de
