Repository kubernetes/dashboard, pull requests merged in 2022-09, with the labels that each got.

#7427 Update Korean translation (lines 1001-1500)
  i18n/ko/messages.ko.xlf
Labels: cncf-cla: yes, size/XS, approved, lgtm, language/ko

#7428 Update Korean translation (lines 1501-2000) (#7427)
  i18n/ko/messages.ko.xlf
Labels: cncf-cla: yes, size/M, approved, lgtm, language/ko

#7433 Update Korean translation (lines 3501-4000) (#7427)
  i18n/ko/messages.ko.xlf
Labels: cncf-cla: yes, size/S, approved, lgtm, language/ko

#7432 Update Korean translation (lines 4001-4500)
  i18n/ko/messages.ko.xlf
Labels: cncf-cla: yes, size/S, approved, lgtm, language/ko

#7434 Update Korean translation (lines 4501-5000)
  i18n/ko/messages.ko.xlf
Labels: cncf-cla: yes, size/M, approved, lgtm, language/ko

#7436 Update Korean translation (lines 3001-3500)
  i18n/ko/messages.ko.xlf
Labels: cncf-cla: yes, size/M, approved, lgtm, language/ko

#7440 Update Korean localization dashboard(5001-5500)
  i18n/ko/messages.ko.xlf
Labels: cncf-cla: yes, size/M, approved, lgtm, language/ko

#7435 Update Korean translation (lines 2501-3000)
  i18n/ko/messages.ko.xlf
Labels: cncf-cla: yes, size/M, approved, lgtm, language/ko

#7443 Update Korean translation (lines 501-1000)
  i18n/ko/messages.ko.xlf
Labels: cncf-cla: yes, size/M, approved, lgtm, language/ko

#7446 Korean localization for dashboard(5501-6000)
  i18n/ko/messages.ko.xlf
Labels: cncf-cla: yes, size/M, approved, lgtm, language/ko

#7447 Korean localization for dashboard(6000-6662)
  i18n/ko/messages.ko.xlf
Labels: cncf-cla: yes, size/L, approved, lgtm, language/ko

#7316 Bump k8s modules to 0.25.0 and prepare for 2.7.0 release
  Makefile
  aio/deploy/alternative.yaml
  aio/deploy/alternative/06_dashboard-deployment.yaml
  aio/deploy/recommended.yaml
  aio/deploy/recommended/06_dashboard-deployment.yaml
  aio/scripts/conf.sh
  docs/user/installation.md
  go.mod
  go.sum
  package-lock.json
  package.json
Labels: cncf-cla: yes, size/L, approved, lgtm, priority/important-soon

#7416 Updated Simplified Chinese translation
  i18n/zh-Hans/messages.zh-Hans.xlf
Labels: cncf-cla: yes, size/XL, approved, lgtm, language/zh

#7465 Use batch/v1 for fetching cronjob jobs
  modules/api/pkg/resource/cronjob/jobs.go
Labels: cncf-cla: yes, size/XS, approved, lgtm

#7466 GitHub Workflows security hardening
  .github/workflows/cd-helm.yml
Labels: cncf-cla: yes, size/XS, approved, lgtm

#7469 Helm update v2.7.0
  charts/helm-chart/kubernetes-dashboard/Chart.yaml
  charts/helm-chart/kubernetes-dashboard/values.yaml
Labels: cncf-cla: yes, size/XS, approved, lgtm

#7477 fix: update Secret with non-latin1 UTF-8 string
  modules/web/package.json
  modules/web/src/resource/config/secret/detail/edit/component.ts
  modules/web/yarn.lock
Labels: cncf-cla: yes, size/S, approved, lgtm

#7478 Build updates
  Makefile
  modules/web/.husky/pre-commit
  modules/web/.husky/pre-push
  modules/web/.yarnrc.yml
  modules/web/Makefile
Labels: cncf-cla: yes, size/M, approved, lgtm

#7476 Update config and dependencies
  .github/dependabot.yml
  modules/api/go.mod
  modules/api/go.sum
  modules/go.work.sum
  modules/web/Makefile
  modules/web/angular.json
  modules/web/jest.config.js
  modules/web/package.json
  modules/web/src/_dark.scss
  modules/web/src/_light.scss
  modules/web/src/_theming.scss
  modules/web/src/common/components/module.ts
  modules/web/src/common/dialogs/module.ts
  modules/web/src/create/from/form/component.ts
  modules/web/src/create/from/form/createnamespace/dialog.ts
  modules/web/src/create/from/form/createsecret/dialog.ts
  modules/web/src/create/from/form/deploylabel/component.ts
  modules/web/src/create/from/form/environmentvariables/component.ts
  modules/web/src/create/from/form/module.ts
  modules/web/src/create/from/form/portmappings/component.ts
  modules/web/src/create/from/form/validator/validators.ts
  modules/web/src/settings/global/component.ts
  modules/web/src/settings/global/namespace/component.ts
  modules/web/tsconfig.spec.json
  modules/web/yarn.lock
Labels: cncf-cla: yes, size/XXL, approved, do-not-merge/invalid-commit-message

#7479 Get rid of ng-in-viewport dependency
  modules/api/Makefile
  modules/web/i18n/de/messages.de.xlf
  modules/web/i18n/es/messages.es.xlf
  modules/web/i18n/fr/messages.fr.xlf
  modules/web/i18n/ja/messages.ja.xlf
  modules/web/i18n/ko/messages.ko.xlf
  modules/web/i18n/messages.xlf
  modules/web/i18n/zh-Hans/messages.zh-Hans.xlf
  modules/web/i18n/zh-Hant-HK/messages.zh-Hant-HK.xlf
  modules/web/i18n/zh-Hant/messages.zh-Hant.xlf
  modules/web/package.json
  modules/web/src/_dark.scss
  modules/web/src/_light.scss
  modules/web/src/_theming.scss
  modules/web/src/_variables.scss
  modules/web/src/chrome/nav/item/component.ts
  modules/web/src/chrome/nav/style.scss
  modules/web/src/chrome/nav/template.html
  modules/web/src/common/components/graph/component.ts
  modules/web/src/common/components/graph/template.html
  modules/web/src/common/components/graphcard/component.spec.ts
  modules/web/src/common/directives/isvisible/directive.ts
  modules/web/src/common/directives/module.ts
  modules/web/src/index.scss
  modules/web/src/logs/template.html
  modules/web/src/shared.module.ts
  modules/web/yarn.lock
Labels: cncf-cla: yes, size/L, approved, lgtm, language/ja, language/zh, language/ko, language/fr, language/de

#7481 check the existence of the http member of a ingress rule before iterating through it
  modules/api/pkg/resource/ingress/filter.go
Labels: cncf-cla: yes, size/XS, approved, lgtm
