Repository kubernetes/dashboard, pull requests merged in 2022-01, with the labels that each got.

#6649 Fix node event (/node/{name}/event) can not get the whole node event
  src/app/backend/resource/event/common.go
Labels: cncf-cla: yes, size/S, approved, lgtm

#6681 Bump angular staffs from 13.1.1 to 13.1.2.
  i18n/de/messages.de.xlf
  i18n/fr/messages.fr.xlf
  i18n/ja/messages.ja.xlf
  i18n/ko/messages.ko.xlf
  i18n/messages.xlf
  i18n/zh-Hans/messages.zh-Hans.xlf
  i18n/zh-Hant-HK/messages.zh-Hant-HK.xlf
  i18n/zh-Hant/messages.zh-Hant.xlf
  package-lock.json
  package.json
Labels: cncf-cla: yes, size/XXL, approved, lgtm, language/ja, language/zh, language/ko, language/fr, language/de

#6676 Add a Service Monitor to the Helm Chart
  aio/deploy/helm-chart/kubernetes-dashboard/Chart.yaml
  aio/deploy/helm-chart/kubernetes-dashboard/templates/servicemonitor.yaml
  aio/deploy/helm-chart/kubernetes-dashboard/values.yaml
Labels: cncf-cla: yes, size/M, approved, lgtm

#6682 Fix development container
  aio/develop/npm-command.sh
  aio/develop/run-npm-on-container.sh
  docs/developer/getting-started.md
Labels: cncf-cla: yes, size/M, approved, lgtm

#6684 Update npm packeges in dependencies
  aio/develop/gosu-command.sh
  package-lock.json
  package.json
Labels: cncf-cla: yes, size/XXL, approved, lgtm

#6687 Change containerSecurityContext rendering and add docs
  aio/deploy/helm-chart/kubernetes-dashboard/Chart.yaml
  aio/deploy/helm-chart/kubernetes-dashboard/templates/deployment.yaml
  aio/deploy/helm-chart/kubernetes-dashboard/values.yaml
Labels: cncf-cla: yes, size/M, approved, lgtm

#6683 Sort namespaces in selector menu alphabetically
  src/app/frontend/common/components/namespace/component.ts
Labels: cncf-cla: yes, size/XS, approved, lgtm

#6692 Update README.md for Japanese translation
  i18n/ja/README.md
Labels: cncf-cla: yes, size/XS, approved, lgtm, language/ja

#6695 package.json: Add override for colors@1.40.0
  package.json
Labels: cncf-cla: yes, size/XS, approved, lgtm

#6698 Small Typo Fix
  README.md
Labels: cncf-cla: yes, size/XS, approved, lgtm

#6690 Update npm packeges in devDependencies
  package-lock.json
  package.json
Labels: cncf-cla: yes, size/XXL, approved, lgtm

#6699 Support npm v7 and nodejs v14 for backward compatibility.
  package.json
Labels: cncf-cla: yes, size/XS, approved, lgtm

#6726 Fix syntax of sentence
  docs/common/dashboard-arguments.md
Labels: cncf-cla: yes, size/XS, approved, lgtm

#6592 Add events on Ingress detail view
  src/app/backend/handler/apihandler.go
  src/app/frontend/resource/discovery/ingress/detail/component.ts
  src/app/frontend/resource/discovery/ingress/detail/template.html
Labels: cncf-cla: yes, size/S, approved, lgtm

#6688 Cleanup frontend dependencies and update Kubernetes dependencies
  Makefile
  aio/scripts/conf.sh
  angular.json
  go.mod
  go.sum
  package-lock.json
  package.json
  src/app/frontend/_dark.scss
  src/app/frontend/_theming.scss
Labels: cncf-cla: yes, size/XXL, approved, lgtm, language/ja

#6733 Fix an issue with CRD retrieval
  src/app/backend/resource/customresourcedefinition/v1/common.go
  src/app/backend/resource/customresourcedefinition/v1/list.go
  src/app/backend/resource/customresourcedefinition/v1/list_test.go
  src/app/backend/resource/customresourcedefinition/v1/objects.go
  src/app/frontend/common/errors/errors.ts
Labels: cncf-cla: yes, size/M, approved, lgtm

#6736 Translate ingress details page and etc. into Japanese.
  i18n/ja/messages.ja.xlf
Labels: cncf-cla: yes, size/M, approved, lgtm, language/ja

#6734 Fix logs autorefresh
  src/app/frontend/logs/component.ts
Labels: cncf-cla: yes, size/S, approved, lgtm

#6658 Services detail page now shows the ingressess related to it
  src/app/backend/handler/apihandler.go
  src/app/backend/resource/ingress/filter.go
  src/app/backend/resource/ingress/list.go
  src/app/backend/resource/service/ingress.go
  src/app/frontend/resource/discovery/ingress/detail/template.html
  src/app/frontend/resource/discovery/service/detail/component.ts
  src/app/frontend/resource/discovery/service/detail/template.html
Labels: cncf-cla: yes, size/L, approved, lgtm
