Repository kubernetes/dashboard, pull requests merged in 2023-03, with the labels that each got.

#7626 Document helm chart PodSecurityPolicy deprecation and PodSecurityAdmission alternative
  charts/helm-chart/kubernetes-dashboard/Chart.yaml
  charts/helm-chart/kubernetes-dashboard/README.md
  charts/helm-chart/kubernetes-dashboard/values.yaml
Labels: cncf-cla: yes, size/S, approved

#7661 Disable e2e job
  .github/workflows/ci-global.yml
Labels: cncf-cla: yes, size/XS, approved, lgtm

#7627 Fix Scale Resource (part 2)
  modules/api/pkg/handler/apihandler.go
  modules/web/src/common/services/global/verber.ts
Labels: cncf-cla: yes, size/XS, approved, lgtm

#7654 [zh] Change i18n text in messages.xlf
  modules/web/i18n/zh-Hans/messages.zh-Hans.xlf
Labels: cncf-cla: yes, size/L, approved, lgtm, language/zh

#7645 Support auto skipping login page
  modules/web/src/common/params/params.ts
  modules/web/src/common/services/guard/auth.ts
  modules/web/src/login/component.spec.ts
  modules/web/src/login/component.ts
Labels: cncf-cla: yes, size/S, approved, lgtm

#7656 Improve French I18N
  modules/web/i18n/fr/messages.fr.xlf
Labels: cncf-cla: yes, size/XL, approved, lgtm, language/fr

#7678 Bump k8s modules to v0.26.3
  modules/api/go.mod
  modules/api/go.sum
  modules/common/certificates/go.mod
  modules/common/certificates/go.sum
  modules/common/tools/go.mod
  modules/common/tools/go.sum
  modules/web/go.mod
  modules/web/go.sum
Labels: cncf-cla: yes, size/M, approved, lgtm

#7689 Bump kindest/node image to 1.26.3
  .github/workflows/ci-helm.yml
  hack/scripts/conf.sh
Labels: cncf-cla: yes, size/XS, approved, lgtm
