Repository kubernetes/dashboard, pull requests merged in 2023-01, with the labels that each got.

#7570 Update Japanese translation
  modules/web/i18n/ja/messages.ja.xlf
Labels: cncf-cla: yes, size/L, approved, lgtm, language/ja

#7574 Enable npm update check with dependabot
  .github/dependabot.yml
Labels: cncf-cla: yes, size/XS, approved, lgtm

#7575 Add go.mod update check for tools and web
  .github/dependabot.yml
Labels: cncf-cla: yes, size/S, approved, lgtm

#7554 Added helm chart optional containers
  charts/helm-chart/kubernetes-dashboard/Chart.yaml
  charts/helm-chart/kubernetes-dashboard/templates/deployment.yaml
  charts/helm-chart/kubernetes-dashboard/values.yaml
Labels: cncf-cla: yes, size/S, approved, lgtm

#7584 Fix Scale Resource UI
  modules/web/src/common/dialogs/scaleresource/dialog.ts
Labels: cncf-cla: yes, size/XS, approved, lgtm
