Repository kubernetes/dashboard, pull requests merged in 2023-06, with the labels that each got.

#7753 Fix - translation ID
  modules/web/i18n/de/messages.de.xlf
  modules/web/i18n/es/messages.es.xlf
  modules/web/i18n/fr/messages.fr.xlf
  modules/web/i18n/ja/messages.ja.xlf
  modules/web/i18n/ko/messages.ko.xlf
  modules/web/i18n/messages.xlf
  modules/web/i18n/zh-Hans/messages.zh-Hans.xlf
  modules/web/i18n/zh-Hant-HK/messages.zh-Hant-HK.xlf
  modules/web/i18n/zh-Hant/messages.zh-Hant.xlf
Labels: cncf-cla: yes, size/S, approved, lgtm, language/ja, language/zh, language/ko, language/fr, language/de

#7756 Specify bit size to int32
  modules/api/pkg/scaling/scale.go
Labels: cncf-cla: yes, size/XS, approved, lgtm

#7755 Bump kind version to 0.19.0 and node image to 1.27.2.
  .github/workflows/ci-helm.yml
  hack/scripts/conf.sh
Labels: cncf-cla: yes, approved, lgtm

#7757 Prevent to run postinstall for yarn during dependabot check
  modules/web/.yarnrc.yml
  modules/web/hack/postinstall.sh
Labels: cncf-cla: yes, size/S, approved, lgtm

#7821 Bump xterm from 4.18.0 to 5.1.0
  modules/web/package.json
  modules/web/src/shell/component.ts
  modules/web/yarn.lock
Labels: cncf-cla: yes, size/S, approved, lgtm

#7823 chore: pkg imported more than once
  modules/api/pkg/api/types.go
  modules/api/pkg/plugin/detail_test.go
  modules/api/pkg/plugin/list_test.go
  modules/api/pkg/resource/customresourcedefinition/common.go
  modules/api/pkg/resource/daemonset/detail.go
Labels: cncf-cla: yes, size/S, approved, lgtm

#7822 Bump ng-extract-i18n-merge from 1.4.0 to 2.7.0
  modules/web/angular.json
  modules/web/i18n/de/messages.de.xlf
  modules/web/i18n/es/messages.es.xlf
  modules/web/i18n/fr/messages.fr.xlf
  modules/web/i18n/ja/messages.ja.xlf
  modules/web/i18n/ko/messages.ko.xlf
  modules/web/i18n/messages.xlf
  modules/web/i18n/zh-Hans/messages.zh-Hans.xlf
  modules/web/i18n/zh-Hant-HK/messages.zh-Hant-HK.xlf
  modules/web/i18n/zh-Hant/messages.zh-Hant.xlf
  modules/web/package.json
  modules/web/yarn.lock
Labels: cncf-cla: yes, size/XXL, approved, lgtm, language/ja, language/zh, language/ko, language/fr, language/de

#7899 feat(helm-chart): support readinessprobe
  charts/helm-chart/kubernetes-dashboard/Chart.yaml
  charts/helm-chart/kubernetes-dashboard/templates/deployment.yaml
  charts/helm-chart/kubernetes-dashboard/values.yaml
Labels: cncf-cla: yes, size/M, approved, lgtm

#7900 Bump k8s modules to 0.27.3
  .github/workflows/ci-helm.yml
  hack/scripts/conf.sh
  modules/api/go.mod
  modules/api/go.sum
  modules/common/certificates/go.mod
  modules/common/certificates/go.sum
  modules/common/tools/go.mod
  modules/common/tools/go.sum
  modules/web/go.mod
  modules/web/go.sum
Labels: cncf-cla: yes, size/M, approved, lgtm
