Repository kubernetes/dashboard, pull requests merged in 2023-08, with the labels that each got.

#8186 Bump k8s modules to 0.28.0
  .github/workflows/ci-helm.yml
  .github/workflows/ci.yml
  hack/scripts/conf.sh
  modules/api/go.mod
  modules/api/go.sum
  modules/common/certificates/go.mod
  modules/common/certificates/go.sum
  modules/common/tools/go.mod
  modules/common/tools/go.sum
  modules/metrics-scraper/go.mod
  modules/metrics-scraper/go.sum
  modules/web/go.mod
  modules/web/go.sum
Labels: cncf-cla: yes, size/L, approved, lgtm

#8103 fix: multiple helm chart improvements
  README.md
  charts/helm-chart/kubernetes-dashboard/Chart.yaml
  charts/helm-chart/kubernetes-dashboard/README.md
  charts/helm-chart/kubernetes-dashboard/_templates_old/ingress.yaml
  charts/helm-chart/kubernetes-dashboard/ci/default-values.yaml
  charts/helm-chart/kubernetes-dashboard/templates/NOTES.txt
  charts/helm-chart/kubernetes-dashboard/templates/networking/ingress.yaml
  charts/helm-chart/kubernetes-dashboard/templates/security/networkpolicy.yaml
  charts/helm-chart/kubernetes-dashboard/values.yaml
  charts/kubernetes-dashboard.yaml
Labels: cncf-cla: yes, size/L, approved

#8119 fix(chart): fix servicemonitor wrong indentation
  charts/helm-chart/kubernetes-dashboard/Chart.yaml
  charts/helm-chart/kubernetes-dashboard/templates/extras/servicemonitor.yaml
Labels: cncf-cla: yes, size/XS, approved, lgtm

#8207 Fix cypress config
  .gitignore
  modules/web/.gitignore
  modules/web/cypress.config.ts
Labels: cncf-cla: yes, size/XS, approved

#8106 Update Angular to v16
  .gitignore
  Makefile
  hack/include/build.mk
  modules/web/.eslintrc.yaml
  modules/web/.gitignore
  modules/web/angular.json
  modules/web/cypress.config.cjs
  modules/web/cypress.config.ts
  modules/web/cypress/plugins/cy-ts-preprocessor.ts
  modules/web/cypress/plugins/index.ts
  modules/web/cypress/support/index.ts
  modules/web/cypress/tsconfig.json
  modules/web/hack/postinstall.sh
  modules/web/i18n/de/messages.de.xlf
  modules/web/i18n/es/messages.es.xlf
  modules/web/i18n/fr/messages.fr.xlf
  modules/web/i18n/ja/messages.ja.xlf
  modules/web/i18n/ko/messages.ko.xlf
  modules/web/i18n/messages.xlf
  modules/web/i18n/zh-Hans/messages.zh-Hans.xlf
  modules/web/i18n/zh-Hant-HK/messages.zh-Hant-HK.xlf
  modules/web/i18n/zh-Hant/messages.zh-Hant.xlf
  modules/web/package.json
  modules/web/src/common/services/guard/auth.ts
  modules/web/src/common/services/guard/candeactivate.ts
  modules/web/src/common/services/guard/login.ts
  modules/web/src/common/services/guard/search.ts
  modules/web/src/index.scss
  modules/web/tsconfig.app.json
  modules/web/tsconfig.json
  modules/web/yarn.lock
Labels: cncf-cla: yes, size/XXL, approved, lgtm, language/ja, language/zh, language/ko, language/fr, language/de

#8227 Bump k8s modules to 0.28.1
  .github/dependabot.yml
  modules/api/go.mod
  modules/api/go.sum
  modules/common/certificates/go.mod
  modules/common/certificates/go.sum
  modules/common/tools/go.mod
  modules/common/tools/go.sum
  modules/metrics-scraper/go.mod
  modules/metrics-scraper/go.sum
  modules/web/go.mod
  modules/web/go.sum
Labels: cncf-cla: yes, size/M, approved, lgtm
