Repository kubernetes/dashboard, pull requests merged in 2023-02, with the labels that each got.

#7620 Update OWNERS_ALIASES
  OWNERS_ALIASES
Labels: cncf-cla: yes, size/S, approved, lgtm

#7619 Update web dependencies
  .github/workflows/cd-global.yml
  .github/workflows/ci-global.yml
  .github/workflows/ci-web.yml
  docs/developer/getting-started.md
  hack/develop/Dockerfile
  modules/web/package.json
  modules/web/src/test.base.ts
  modules/web/tsconfig.json
  modules/web/yarn.lock
Labels: cncf-cla: yes, size/XXL, approved, lgtm

#7621 Fix build in development container
  hack/develop/run-command.sh
Labels: cncf-cla: yes, size/XS, approved, lgtm

#7628 Update Japanese translation guide
  modules/web/i18n/ja/README.md
Labels: cncf-cla: yes, size/S, approved, lgtm, language/ja

#7629 Fix port number for dashboard
  modules/web/i18n/ja/README.md
Labels: cncf-cla: yes, size/XS, approved, lgtm, language/ja
