Repository kubernetes/dashboard, pull requests merged in 2024-10, with the labels that each got.

#8971 feat(chart): Disable Kong Manager by default
  charts/kubernetes-dashboard/values.yaml
Labels: kind/feature, cncf-cla: yes, size/XS, approved, lgtm

#9138 docs: warn users about https requirement
  docs/user/access-control/creating-sample-user.md
Labels: cncf-cla: yes, size/XS, approved, kind/documentation, lgtm

#9490 feat: add full support for labels and annotations in helm chart
  charts/kubernetes-dashboard/Chart.yaml
  charts/kubernetes-dashboard/templates/_helpers.tpl
  charts/kubernetes-dashboard/templates/_tplvalues.tpl
  charts/kubernetes-dashboard/templates/config/gateway.yaml
  charts/kubernetes-dashboard/templates/config/settings.yaml
  charts/kubernetes-dashboard/templates/deployments/api.yaml
  charts/kubernetes-dashboard/templates/deployments/auth.yaml
  charts/kubernetes-dashboard/templates/deployments/metrics-scraper.yaml
  charts/kubernetes-dashboard/templates/deployments/web.yaml
  charts/kubernetes-dashboard/templates/extras/servicemonitor.yaml
  charts/kubernetes-dashboard/templates/networking/ingress.yaml
  charts/kubernetes-dashboard/templates/rbac/api/role.yaml
  charts/kubernetes-dashboard/templates/rbac/api/rolebinding.yaml
  charts/kubernetes-dashboard/templates/rbac/api/serviceaccount.yaml
  charts/kubernetes-dashboard/templates/rbac/metrics-scraper/clusterrole.yaml
  charts/kubernetes-dashboard/templates/rbac/metrics-scraper/clusterrolebinding.yaml
  charts/kubernetes-dashboard/templates/rbac/metrics-scraper/serviceaccount.yaml
  charts/kubernetes-dashboard/templates/rbac/web/role.yaml
  charts/kubernetes-dashboard/templates/rbac/web/rolebinding.yaml
  charts/kubernetes-dashboard/templates/rbac/web/serviceaccount.yaml
  charts/kubernetes-dashboard/templates/secrets/csrf.yaml
  charts/kubernetes-dashboard/templates/security/networkpolicy.yaml
  charts/kubernetes-dashboard/templates/security/pdb.yaml
  charts/kubernetes-dashboard/templates/services/api.yaml
  charts/kubernetes-dashboard/templates/services/auth.yaml
  charts/kubernetes-dashboard/templates/services/metrics-scraper.yaml
  charts/kubernetes-dashboard/templates/services/web.yaml
  charts/kubernetes-dashboard/values.yaml
Labels: cncf-cla: yes, size/L, approved, lgtm, kind/cleanup

#9514 chore(chart): bump modules and helm chart
  charts/kubernetes-dashboard/Chart.yaml
  charts/kubernetes-dashboard/values.yaml
Labels: kind/feature, cncf-cla: yes, size/S, approved, lgtm

#9359 chore(deps-dev): bump typescript-eslint modules to 8.8.0
  modules/web/.eslintrc.yaml
  modules/web/package.json
  modules/web/src/common/dialogs/editresource/dialog.ts
  modules/web/src/common/dialogs/previewdeployment/dialog.ts
  modules/web/src/common/services/global/loader.ts
  modules/web/src/crd/crdobject/component.ts
  modules/web/src/typings/volume.api.ts
  modules/web/yarn.lock
Labels: cncf-cla: yes, size/L, approved, lgtm, dependencies

#9548 fix: the divisor field in resourceFieldRefs should be a string
  charts/kubernetes-dashboard/templates/deployments/api.yaml
  charts/kubernetes-dashboard/templates/deployments/auth.yaml
  charts/kubernetes-dashboard/templates/deployments/metrics-scraper.yaml
  charts/kubernetes-dashboard/templates/deployments/web.yaml
Labels: kind/bug, cncf-cla: yes, size/S, approved, lgtm

#9562 chore: release v7.9.0
  charts/kubernetes-dashboard/Chart.yaml
  charts/kubernetes-dashboard/values.yaml
Labels: kind/feature, cncf-cla: yes, size/S, approved, lgtm

#9599 fix(api): ssar resource kind name and resource updates
  hack/docker/dev.compose.yml
  modules/api/go.mod
  modules/api/go.sum
  modules/auth/go.mod
  modules/auth/go.sum
  modules/common/client/cache/client/common/resourcelister_options.go
  modules/common/client/go.mod
  modules/common/client/go.sum
  modules/common/client/verber.go
  modules/web/go.mod
  modules/web/go.sum
  modules/web/src/common/components/namespace/component.ts
Labels: kind/bug, cncf-cla: yes, size/M, approved, lgtm

#9610 fix(signin button): signin button is clickable when token is autofilled by browser
  modules/web/src/login/component.spec.ts
  modules/web/src/login/template.html
Labels: kind/bug, cncf-cla: yes, size/XS, approved, lgtm

#9621 chore(chart): release 7.10.0
  charts/kubernetes-dashboard/Chart.yaml
  charts/kubernetes-dashboard/values.yaml
Labels: kind/feature, cncf-cla: yes, approved, lgtm
