Repository kubernetes/dashboard, pull requests merged in 2024-09, with the labels that each got.

#9465 feat: Add drain node endpoint
  modules/api/go.mod
  modules/api/go.sum
  modules/api/pkg/handler/apihandler.go
  modules/api/pkg/resource/node/drain.go
  modules/api/schema/swagger.json
  modules/web/schema/schema.graphql
Labels: kind/feature, cncf-cla: yes, size/XL, approved

#9467 feat: bump chart to v7.6.0
  charts/kubernetes-dashboard/Chart.yaml
  charts/kubernetes-dashboard/values.yaml
Labels: kind/feature, cncf-cla: yes, size/XS, approved

#9468 fix: Bump chart to v7.6.1 and change drain endpoint method to PUT
  charts/kubernetes-dashboard/Chart.yaml
  charts/kubernetes-dashboard/values.yaml
  modules/api/pkg/handler/apihandler.go
  modules/api/schema/swagger.json
  modules/web/schema/schema.graphql
Labels: kind/feature, cncf-cla: yes, size/M, approved

#9443 docs: Update creating-sample-user.md
  docs/user/access-control/creating-sample-user.md
Labels: cncf-cla: yes, size/XS, approved, kind/documentation, lgtm

#9380 feat(chart): add supported settings to values.yaml based on settings.go
  charts/kubernetes-dashboard/values.yaml
Labels: kind/feature, cncf-cla: yes, size/XS, approved, lgtm

#9353 feat(auth): support specifying api server host in auth module
  modules/auth/main.go
  modules/auth/pkg/args/args.go
Labels: kind/feature, cncf-cla: yes, size/S, approved, lgtm

#9486 Fix incorrect resource divisors in Helm templates
  charts/kubernetes-dashboard/templates/deployments/api.yaml
  charts/kubernetes-dashboard/templates/deployments/auth.yaml
  charts/kubernetes-dashboard/templates/deployments/metrics-scraper.yaml
  charts/kubernetes-dashboard/templates/deployments/web.yaml
Labels: kind/bug, cncf-cla: yes, size/S, approved, lgtm
