Repository kubernetes/dashboard, pull requests merged in 2024-05, with the labels that each got.

#9010 chore(deps): bump k8s modules to v0.30.0
  modules/api/go.mod
  modules/api/go.sum
  modules/auth/go.mod
  modules/auth/go.sum
  modules/common/certificates/go.mod
  modules/common/certificates/go.sum
  modules/common/client/go.mod
  modules/common/client/go.sum
  modules/common/errors/go.mod
  modules/common/errors/go.sum
  modules/common/helpers/go.mod
  modules/common/helpers/go.sum
  modules/common/tools/go.mod
  modules/common/tools/go.sum
  modules/common/types/go.mod
  modules/common/types/go.sum
  modules/metrics-scraper/go.mod
  modules/metrics-scraper/go.sum
  modules/web/go.mod
  modules/web/go.sum
Labels: cncf-cla: yes, size/XL, approved, lgtm, dependencies

#9018 feat: Add pod allocated resources
  modules/api/pkg/resource/node/detail.go
  modules/api/pkg/resource/pod/common.go
  modules/api/pkg/resource/pod/list.go
  modules/api/schema/swagger.json
  modules/web/schema/schema.graphql
Labels: kind/feature, cncf-cla: yes, size/L, approved

#8989 feat(chart): Set `GOMAXPROCS` and `GOMEMLIMIT` environment variables
  charts/kubernetes-dashboard/templates/deployments/api.yaml
  charts/kubernetes-dashboard/templates/deployments/auth.yaml
  charts/kubernetes-dashboard/templates/deployments/metrics-scraper.yaml
  charts/kubernetes-dashboard/templates/deployments/web.yaml
Labels: kind/feature, cncf-cla: yes, size/M, approved
