Repository kubernetes/dashboard, pull requests merged in 2024-03, with the labels that each got.

#8734 chore: Update CD pipeline
  .github/workflows/cd-api.yml
  .github/workflows/cd-auth.yml
  .github/workflows/cd-metrics-scraper.yml
  .github/workflows/cd-web.yml
  .github/workflows/cd.yml
  .github/workflows/ci.yml
Labels: cncf-cla: yes, size/L, approved, lgtm, kind/cleanup

#8641 Fix nodejs and npm installation in dev container
  hack/develop/Dockerfile
Labels: cncf-cla: yes, size/XS, approved, lgtm

#8738 wip: Fix web module image
  modules/web/Dockerfile
Labels: kind/bug, cncf-cla: yes, size/XS, do-not-merge/work-in-progress, approved

#8744 docs: Rewrite development docs
  .github/workflows/ci.yml
  DEVELOPMENT.md
  README.md
  docs/README.md
  docs/common/faq.md
  docs/common/internationalization.md
  docs/developer/README.md
  docs/developer/architecture.md
  docs/developer/code-conventions.md
  docs/developer/dependency-management.md
  docs/developer/getting-started.md
  docs/developer/release-procedures.md
  docs/developer/text-conventions.md
  hack/develop/run-dev-container.sh
Labels: cncf-cla: yes, size/XL, approved, kind/documentation, lgtm

#8747 fix: Fix web builder
  .github/workflows/ci.yml
  .github/workflows/pr.yml
  Makefile
  hack/docker/docker.compose.yaml
  hack/include/build.mk
  modules/web/Dockerfile
Labels: kind/bug, cncf-cla: yes, size/M, approved, lgtm

#8746 feat: Add Helm CD action
  .github/workflows/cd-helm.yml
Labels: kind/feature, cncf-cla: yes, size/L, approved

#8748 feat: Update helm chart
  Makefile
  README.md
  charts/kubernetes-dashboard/Chart.yaml
  charts/kubernetes-dashboard/templates/deployments/web.yaml
  charts/kubernetes-dashboard/values.yaml
  docs/user/access-control/README.md
  hack/docker/dev.compose.yml
Labels: kind/feature, cncf-cla: yes, size/M, approved, lgtm

#8754 fix(web): fix locale-config default value
  hack/docker/dev.compose.yml
  hack/docker/docker.compose.yaml
  modules/web/pkg/args/args.go
Labels: kind/bug, cncf-cla: yes, size/XS, approved, lgtm

#8757 feat(chart): update helm chart and bump to 7.0.1
  Makefile
  charts/kubernetes-dashboard/Chart.yaml
  charts/kubernetes-dashboard/templates/_helpers.tpl
  charts/kubernetes-dashboard/templates/config/settings.yaml
  charts/kubernetes-dashboard/templates/deployments/api.yaml
  charts/kubernetes-dashboard/templates/deployments/auth.yaml
  charts/kubernetes-dashboard/templates/deployments/metrics-scraper.yaml
  charts/kubernetes-dashboard/templates/deployments/web.yaml
  charts/kubernetes-dashboard/templates/networking/ingress.yaml
  charts/kubernetes-dashboard/templates/rbac/web/role.yaml
  charts/kubernetes-dashboard/templates/secrets/csrf.yaml
  charts/kubernetes-dashboard/values.yaml
Labels: kind/feature, cncf-cla: yes, size/M, approved, lgtm

#8761 feat: allow overriding ingress tls secret name
  charts/kubernetes-dashboard/Chart.yaml
  charts/kubernetes-dashboard/templates/networking/ingress.yaml
  charts/kubernetes-dashboard/values.yaml
Labels: kind/feature, cncf-cla: yes, size/XS, approved, lgtm

#8763 feat(chart): update web, auth images and bump chart
  .github/workflows/cd-helm.yml
  charts/kubernetes-dashboard/Chart.yaml
  charts/kubernetes-dashboard/values.yaml
  modules/web/src/chrome/userpanel/style.scss
Labels: kind/feature, cncf-cla: yes, size/S, approved

#8764 Point documentation to correct NGINX controller
  charts/kubernetes-dashboard/README.md
Labels: cncf-cla: yes, size/XS, approved, lgtm

#8766 feat(api): add full proxy mode to api module
  docs/common/arguments.md
  hack/scripts/conf.sh
  hack/scripts/start-cluster.sh
  hack/test-resources/kubernetes-dashboard-local.yaml
  modules/api/main.go
  modules/api/pkg/args/args.go
  modules/api/pkg/handler/apihandler.go
  modules/web/Makefile
  modules/web/src/chrome/userpanel/component.ts
  modules/web/src/common/services/global/authentication.ts
  modules/web/src/common/services/global/interceptor.ts
  modules/web/src/common/services/global/me.ts
  modules/web/src/common/services/global/module.ts
Labels: kind/feature, cncf-cla: yes, size/L, approved, lgtm

#8769 feat(chart): bump chart to 7.1.2
  charts/kubernetes-dashboard/Chart.yaml
  charts/kubernetes-dashboard/values.yaml
Labels: kind/feature, cncf-cla: yes, size/XS, approved, lgtm

#8821 chore: fix some typos
  charts/kubernetes-dashboard/README.md
  hack/develop/run-dev-container.sh
Labels: cncf-cla: yes, size/XS, approved, lgtm

#8840 fix: login guard and me service initialization
  modules/auth/pkg/routes/me/me.go
  modules/web/src/common/components/chips/component.ts
  modules/web/src/common/services/global/authentication.ts
  modules/web/src/common/services/global/loader.ts
  modules/web/src/common/services/global/me.ts
  modules/web/src/common/services/global/module.ts
  modules/web/src/common/services/guard/auth.ts
  modules/web/src/common/services/guard/login.ts
  modules/web/src/systemjs.d.ts
Labels: kind/bug, cncf-cla: yes, size/L, approved, lgtm
