Repository kubernetes/dashboard, pull requests merged in 2024-01, with the labels that each got.

#8582 Misguide the timezone for logs
  modules/web/src/logs/template.html
Labels: cncf-cla: yes, size/XS, approved, lgtm

#8590 Add separator for ingress host
  modules/web/src/common/components/resourcelist/ingress/template.html
Labels: cncf-cla: yes, size/XS, approved, lgtm

#8221 [helm] Add ServiceMonitor relabel Configs
  charts/helm-chart/kubernetes-dashboard/Chart.yaml
  charts/helm-chart/kubernetes-dashboard/templates/extras/servicemonitor.yaml
  charts/helm-chart/kubernetes-dashboard/values.yaml
Labels: cncf-cla: yes, size/S, approved, lgtm

#8610 Bump stylelint staffs
  modules/web/.stylelintrc.yaml
  modules/web/package.json
  modules/web/yarn.lock
Labels: cncf-cla: yes, size/L, approved, lgtm

#8631 Bump k8s modules to 0.29.1
  modules/api/go.mod
  modules/api/go.sum
  modules/common/certificates/go.mod
  modules/common/certificates/go.sum
  modules/common/tools/go.mod
  modules/common/tools/go.sum
  modules/metrics-scraper/go.mod
  modules/metrics-scraper/go.sum
Labels: cncf-cla: yes, size/L, approved, lgtm

#8423 Update nodejs install method
  hack/develop/Dockerfile
Labels: cncf-cla: yes, size/S, approved, lgtm, lifecycle/stale

#8516 Update Korean translation: Horizontal Pod Autoscaler
  modules/web/i18n/ko/messages.ko.xlf
Labels: cncf-cla: yes, size/XS, approved, lgtm, language/ko

#7583 The Delete a Resource UI should have an opt-in "delete now" checkbox
  modules/api/pkg/client/api/types.go
  modules/api/pkg/client/verber.go
  modules/api/pkg/client/verber_test.go
  modules/api/pkg/handler/apihandler.go
  modules/web/i18n/de/messages.de.xlf
  modules/web/i18n/es/messages.es.xlf
  modules/web/i18n/fr/messages.fr.xlf
  modules/web/i18n/ja/messages.ja.xlf
  modules/web/i18n/ko/messages.ko.xlf
  modules/web/i18n/messages.xlf
  modules/web/i18n/zh-Hans/messages.zh-Hans.xlf
  modules/web/i18n/zh-Hant-HK/messages.zh-Hant-HK.xlf
  modules/web/i18n/zh-Hant/messages.zh-Hant.xlf
  modules/web/src/common/dialogs/deleteresource/dialog.ts
  modules/web/src/common/dialogs/deleteresource/template.html
  modules/web/src/common/services/global/verber.ts
Labels: cncf-cla: yes, size/L, approved, lgtm, language/ja, language/zh, language/ko, language/fr, language/de

#8642 Fix translation files
  modules/web/i18n/de/messages.de.xlf
  modules/web/i18n/es/messages.es.xlf
  modules/web/i18n/fr/messages.fr.xlf
  modules/web/i18n/ja/messages.ja.xlf
  modules/web/i18n/ko/messages.ko.xlf
  modules/web/i18n/messages.xlf
  modules/web/i18n/zh-Hans/messages.zh-Hans.xlf
  modules/web/i18n/zh-Hant-HK/messages.zh-Hant-HK.xlf
  modules/web/i18n/zh-Hant/messages.zh-Hant.xlf
Labels: cncf-cla: yes, size/XL, approved, lgtm, language/ja, language/zh, language/ko, language/fr, language/de

#8319 Replace todo ctx with request ctx in GetPluginSource
  modules/api/pkg/plugin/detail.go
  modules/api/pkg/plugin/detail_test.go
  modules/api/pkg/plugin/handler.go
Labels: cncf-cla: yes, size/S, approved, lgtm, kind/cleanup
