Repository kubernetes/dashboard, pull requests merged in 2024-04, with the labels that each got.

#8827 ci: Fix CodeQL check and ignore codecov token error
  .github/workflows/ci.yml
Labels: kind/bug, cncf-cla: yes, size/XS, approved, lgtm

#8879 fix: api schema and update kong chart config
  charts/kubernetes-dashboard/values.yaml
  modules/api/pkg/handler/apihandler.go
  modules/api/schema/swagger.json
  modules/web/schema/schema.graphql
Labels: kind/bug, cncf-cla: yes, size/M, approved, lgtm

#8869 feat(chart): add automountServiceAccountToken to deployment specs in Helm chart
  charts/kubernetes-dashboard/templates/deployments/api.yaml
  charts/kubernetes-dashboard/templates/deployments/auth.yaml
  charts/kubernetes-dashboard/templates/deployments/metrics-scraper.yaml
  charts/kubernetes-dashboard/templates/deployments/web.yaml
  charts/kubernetes-dashboard/values.yaml
Labels: kind/feature, cncf-cla: yes, size/S, approved, lgtm

#8881 fix(api): role/clusterole/podlist endpoints
  .github/workflows/cd-helm.yml
  modules/api/Makefile
  modules/api/pkg/handler/apihandler.go
  modules/api/pkg/resource/dataselect/dataselect.go
  modules/api/pkg/resource/node/detail.go
  modules/api/pkg/resource/node/detail_test.go
  modules/api/pkg/resource/pod/common_test.go
  modules/api/pkg/resource/pod/container.go
  modules/api/pkg/resource/pod/list.go
  modules/api/pkg/resource/pod/list_test.go
  modules/api/pkg/resource/service/pods_test.go
  modules/api/schema/swagger.json
  modules/common/csrf/middleware_gin.go
  modules/web/schema/schema.graphql
Labels: kind/bug, cncf-cla: yes, size/L, approved, lgtm

#8870 feat(chart): allow setting priorityClassName on deployments
  charts/kubernetes-dashboard/templates/deployments/api.yaml
  charts/kubernetes-dashboard/templates/deployments/auth.yaml
  charts/kubernetes-dashboard/templates/deployments/metrics-scraper.yaml
  charts/kubernetes-dashboard/templates/deployments/web.yaml
  charts/kubernetes-dashboard/values.yaml
Labels: kind/feature, cncf-cla: yes, size/S, approved, lgtm

#8882 feat(chart): bump chart version to 7.2.0
  charts/kubernetes-dashboard/Chart.yaml
  charts/kubernetes-dashboard/templates/_helpers.tpl
  charts/kubernetes-dashboard/templates/deployments/api.yaml
  charts/kubernetes-dashboard/templates/deployments/auth.yaml
  charts/kubernetes-dashboard/templates/secrets/csrf.yaml
  charts/kubernetes-dashboard/values.yaml
Labels: kind/feature, cncf-cla: yes, size/S, approved, lgtm

#8884 fix(api): pod detail endpoint returns invalid container status for init containers
  modules/api/pkg/resource/pod/detail.go
Labels: kind/bug, cncf-cla: yes, size/XS, approved, lgtm

#8900 feat: refactor verber and fix client-side throttling due to client init misconfiguration
  Makefile
  modules/api/go.mod
  modules/api/go.sum
  modules/api/pkg/handler/apihandler.go
  modules/api/pkg/integration/metric/manager.go
  modules/api/pkg/integration/metric/sidecar/client.go
  modules/api/pkg/resource/cronjob/list.go
  modules/api/pkg/resource/cronjob/list_test.go
  modules/api/pkg/resource/statefulset/list.go
  modules/auth/go.mod
  modules/auth/go.sum
  modules/common/certificates/go.mod
  modules/common/certificates/go.sum
  modules/common/client/auth.go
  modules/common/client/client.go
  modules/common/client/go.mod
  modules/common/client/go.sum
  modules/common/client/init.go
  modules/common/client/types.go
  modules/common/client/verber.go
  modules/common/client/verber_test.go
  modules/common/csrf/go.mod
  modules/common/csrf/go.sum
  modules/common/errors/go.mod
  modules/common/errors/go.sum
  modules/common/helpers/go.mod
  modules/common/helpers/go.sum
  modules/common/tools/go.mod
  modules/common/tools/go.sum
  modules/common/types/common.go
  modules/common/types/go.mod
  modules/common/types/go.sum
  modules/metrics-scraper/go.mod
  modules/metrics-scraper/go.sum
  modules/web/go.mod
  modules/web/go.sum
  modules/web/src/common/components/resourcelist/replicationcontroller/component.ts
  modules/web/src/common/components/resourcelist/replicationcontroller/template.html
  modules/web/src/resource/workloads/replicationcontroller/list/component.ts
  modules/web/src/typings/root.api.ts
Labels: kind/feature, cncf-cla: yes, size/XXL, approved, lgtm

#8902 chore(chart): bump chart to 7.3.1
  charts/kubernetes-dashboard/Chart.yaml
  charts/kubernetes-dashboard/values.yaml
Labels: cncf-cla: yes, size/S, approved, lgtm, kind/cleanup

#8913 feat(api): improve pod container status logic and add simplified status to pod details
  modules/api/pkg/resource/pod/container.go
  modules/api/pkg/resource/pod/detail.go
  modules/api/schema/swagger.json
  modules/web/.meshrc.yml
  modules/web/schema/schema.graphql
Labels: kind/feature, cncf-cla: yes, size/L, approved, lgtm

#8943 chore: fix some typos in comments
  docs/common/faq.md
  docs/user/labels.md
  modules/api/pkg/resource/container/logs_test.go
  modules/api/pkg/resource/dataselect/stdcomparabletypes.go
  modules/api/pkg/resource/limitrange/detail.go
  modules/api/pkg/resource/pod/detail.go
  modules/common/client/init.go
Labels: cncf-cla: yes, size/S, approved, lgtm, kind/cleanup

#8979 chore: fix struct name in comment
  modules/api/pkg/resource/common/resourcechannels.go
Labels: cncf-cla: yes, size/XS, approved, kind/documentation, lgtm
