Repository kubernetes/dashboard, pull requests merged in 2024-06, with the labels that each got.

#9113 feat: add support for delete propagation policy
  modules/api/pkg/handler/apihandler.go
  modules/api/schema/swagger.json
  modules/common/client/types.go
  modules/common/client/verber.go
  modules/web/.meshrc.yml
  modules/web/i18n/de/messages.de.xlf
  modules/web/i18n/es/messages.es.xlf
  modules/web/i18n/fr/messages.fr.xlf
  modules/web/i18n/ja/messages.ja.xlf
  modules/web/i18n/ko/messages.ko.xlf
  modules/web/i18n/messages.xlf
  modules/web/i18n/zh-Hans/messages.zh-Hans.xlf
  modules/web/i18n/zh-Hant-HK/messages.zh-Hant-HK.xlf
  modules/web/i18n/zh-Hant/messages.zh-Hant.xlf
  modules/web/schema/schema.graphql
  modules/web/src/_theming.scss
  modules/web/src/common/dialogs/deleteresource/dialog.ts
  modules/web/src/common/dialogs/deleteresource/styles.scss
  modules/web/src/common/dialogs/deleteresource/template.html
  modules/web/src/common/services/global/verber.ts
Labels: kind/feature, cncf-cla: yes, size/XL, approved, lgtm, language/ja, language/zh, language/ko, language/fr, language/de

#9056 docs: Remove base-url
  docs/common/arguments.md
Labels: cncf-cla: yes, size/XS, approved, kind/documentation, lgtm

#9117 feat(chart): bump chart to 7.5.0
  charts/kubernetes-dashboard/Chart.lock
  charts/kubernetes-dashboard/Chart.yaml
  charts/kubernetes-dashboard/templates/networking/ingress.yaml
  charts/kubernetes-dashboard/templates/security/networkpolicy.yaml
  charts/kubernetes-dashboard/values.yaml
Labels: kind/feature, cncf-cla: yes, size/M, approved, lgtm

#9132 fix: update cosmtrek/air project link to air-verse/air
  modules/api/dev.Dockerfile
  modules/auth/dev.Dockerfile
  modules/common/tools/Makefile
  modules/common/tools/go.mod
  modules/common/tools/go.sum
  modules/common/tools/main.go
  modules/metrics-scraper/dev.Dockerfile
  modules/web/dev.go.Dockerfile
Labels: kind/bug, cncf-cla: yes, size/S, approved, lgtm
