Repository kubernetes/dashboard, pull requests merged in 2025-01, with the labels that each got.

#9794 chore(deps): Bump k8s modules to 0.32.0
  .github/workflows/cd-helm.yml
  .github/workflows/ci-helm.yml
  .github/workflows/ci.yml
  hack/include/config.mk
  modules/api/go.mod
  modules/api/go.sum
  modules/auth/go.mod
  modules/auth/go.sum
  modules/common/certificates/go.mod
  modules/common/certificates/go.sum
  modules/common/client/go.mod
  modules/common/client/go.sum
  modules/common/csrf/go.mod
  modules/common/csrf/go.sum
  modules/common/errors/go.mod
  modules/common/errors/go.sum
  modules/common/helpers/go.mod
  modules/common/helpers/go.sum
  modules/common/tools/go.mod
  modules/common/tools/go.sum
  modules/common/types/go.mod
  modules/common/types/go.sum
  modules/metrics-scraper/go.mod
  modules/metrics-scraper/go.sum
  modules/web/go.mod
  modules/web/go.sum
Labels: cncf-cla: yes, size/XXL, approved, lgtm, dependencies

#9849 chore(chart): release 7.10.1
  charts/kubernetes-dashboard/Chart.lock
  charts/kubernetes-dashboard/Chart.yaml
  charts/kubernetes-dashboard/values.yaml
Labels: cncf-cla: yes, size/M, approved, lgtm, kind/cleanup

#9851 docs: Fixing redirects from docs/user-guide which were removed in website repo
  charts/kubernetes-dashboard/values.yaml
  modules/web/src/create/from/form/createsecret/template.html
  modules/web/src/create/from/form/template.html
Labels: cncf-cla: yes, size/S, approved, kind/documentation, lgtm

#9067 fix: workload charts are black for certain languages
  modules/web/src/common/components/workloadstatus/component.ts
Labels: cncf-cla: yes, size/XS, approved, lgtm

#9881 Cronjob status.lastSuccessfulTime not populated by a manually triggered job
  modules/api/pkg/resource/cronjob/jobs.go
Labels: cncf-cla: yes, size/S, approved, lgtm

#9903 chore(chart): release 7.10.2
  charts/kubernetes-dashboard/Chart.yaml
  charts/kubernetes-dashboard/templates/services/api.yaml
  charts/kubernetes-dashboard/templates/services/auth.yaml
  charts/kubernetes-dashboard/templates/services/metrics-scraper.yaml
  charts/kubernetes-dashboard/templates/services/web.yaml
Labels: kind/feature, cncf-cla: yes, size/S, approved, lgtm

#9904 chore(chart): release 7.10.3
  charts/kubernetes-dashboard/Chart.yaml
  charts/kubernetes-dashboard/templates/services/api.yaml
  charts/kubernetes-dashboard/templates/services/auth.yaml
  charts/kubernetes-dashboard/templates/services/metrics-scraper.yaml
  charts/kubernetes-dashboard/templates/services/web.yaml
  charts/kubernetes-dashboard/values.yaml
Labels: kind/feature, cncf-cla: yes, size/M, approved, lgtm

#9863 fix: use correct Kong service port for ingress based on TLS settings
  charts/kubernetes-dashboard/templates/networking/ingress.yaml
Labels: kind/bug, cncf-cla: yes, size/S, approved, lgtm
