Repository kubernetes/dashboard, pull requests merged in 2025-03, with the labels that each got.

#10009 feat: Pod Disruption Budget API
  modules/api/pkg/handler/apihandler.go
  modules/api/pkg/resource/common/resourcechannels.go
  modules/api/pkg/resource/poddisruptionbudget/common.go
  modules/api/pkg/resource/poddisruptionbudget/detail.go
  modules/api/pkg/resource/poddisruptionbudget/detail_test.go
  modules/api/pkg/resource/poddisruptionbudget/list.go
  modules/api/pkg/resource/poddisruptionbudget/list_test.go
  modules/api/schema/swagger.json
  modules/common/types/resourcekind.go
  modules/web/i18n/de/messages.de.xlf
  modules/web/i18n/es/messages.es.xlf
  modules/web/i18n/fr/messages.fr.xlf
  modules/web/i18n/ja/messages.ja.xlf
  modules/web/i18n/ko/messages.ko.xlf
  modules/web/i18n/messages.xlf
  modules/web/i18n/zh-Hans/messages.zh-Hans.xlf
  modules/web/i18n/zh-Hant-HK/messages.zh-Hant-HK.xlf
  modules/web/i18n/zh-Hant/messages.zh-Hant.xlf
  modules/web/schema/schema.graphql
Labels: kind/feature, cncf-cla: yes, size/XXL, approved, language/ja, language/zh, language/ko, language/fr, language/de

#10011 chore(chart): release 7.11.0
  charts/kubernetes-dashboard/Chart.yaml
  charts/kubernetes-dashboard/values.yaml
Labels: kind/feature, cncf-cla: yes, size/XS, approved, lgtm

#10014 fix(client): GVR core resources caching
  modules/common/client/verber.go
Labels: kind/bug, cncf-cla: yes, size/XS, approved, lgtm

#10015 chore(chart): release 7.11.1
  charts/kubernetes-dashboard/Chart.yaml
  charts/kubernetes-dashboard/values.yaml
Labels: kind/feature, cncf-cla: yes, size/XS, approved, lgtm
